// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.DeadSpace.Notify.Prototypes;
using Robust.Shared.Prototypes;
using Robust.Shared.Configuration;
using Content.Shared.DeadSpace.CCCCVars;
using Content.Client.Options.UI;
using System.Numerics;
using Content.Client.DeadSpace.Notify;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]

public sealed partial class PingTab : Control
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager prototypeManager = default!;
    [Dependency] private readonly IConfigurationManager cfg = default!;
    private bool _isSaveNeeded = false;
    private string _searchText = string.Empty;
    private void AddCheckBox(ReceiveNotifySystem helper, string checkBoxName, string id, bool savedSelection)
    {
        CheckBox newCheckBox = new CheckBox() { Text = checkBoxName }; //Loc.GetString(checkBoxName) };
        newCheckBox.Pressed = savedSelection;
        newCheckBox.OnToggled += _ =>
        {
            _isSaveNeeded = true;
            helper.SetValueAccess(id, newCheckBox.Pressed);
        };

        PingsCont.AddChild(newCheckBox);
    }
    private void AddSaveButton(Button ourButton, IConfigurationManager cfg, ReceiveNotifySystem helper)
    {
        ourButton.OnPressed += _ =>
        {
            if (_isSaveNeeded)
            {
                _isSaveNeeded = false;
                cfg.SetCVar(CCCCVars.SysNotifyCvar, helper.PairListToString(helper.GetDictionaryAccess()));
                cfg.SaveToFile();
            }
        };
    }
    private bool ButtonIsVisible(CheckBox button)
    {
        return string.IsNullOrEmpty(_searchText) || button.Text == null || button.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
    }
    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text;

        foreach (var child in PingsCont.Children)
        {
            if (child is CheckBox button)
                button.Visible = ButtonIsVisible(button);
        }
        // Reset scroll bar so they can see the relevant results.
        ScrollContainer.SetScrollValue(Vector2.Zero);
    }
    public PingTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        try
        {
            if (_entityManager.TrySystem<ReceiveNotifySystem>(out var helper))
            {
                helper.EnsureInitialized();
                AddSaveButton(SaveButton, cfg, helper);
                foreach (var proto in prototypeManager.EnumeratePrototypes<GhostRoleGroupNotify>())
                {
                    AddCheckBox(helper, proto.Name, proto.ID, helper.GetValueAccess(proto.ID));
                }
            }
        }
        catch (NullReferenceException)
        {
            // Entity systems are not initialized on the main menu
        }

        var sounds = prototypeManager.EnumeratePrototypes<SoundForPing>();
        var soundPingEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var sound in sounds)
        {
            soundPingEntries.Add(new OptionDropDownCVar<string>.ValueOption(sound.Path, sound.Name));
        }
        Control.AddOptionCheckBox(CCCCVars.SysNotifyPerm, GetPingPermission);
        Control.AddOptionDropDown(CCCCVars.SysNotifySoundPath, DropDownSoundPing, soundPingEntries);
        Control.AddOptionSlider(
            CCCCVars.SysNotifyCoolDown,
            SliderCooldownForPing,
            0,
            10);
        SearchBar.OnTextChanged += OnSearchTextChanged;
        Control.Initialize();
    }
}