- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 5h
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  #start-backmen: currency
  minBankBalance: 250 # DS14-value
  maxBankBalance: 350 # DS14-value
  wageDepartment: Medical
  wage: 200 # DS14-value
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: Chemistryist
      # DS14-End

- type: startingGear
  id: ChemistGear
  equipment:
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    # head: ClothingHeadHatMedBeretChemist # DS14
    belt: ChemBag
    pocket1: HandLabeler
    eyes: ClothingEyesGlassesChemical
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ChemistChameleonOutfit
  job: Chemist
  equipment:
    head: ClothingHeadHatMedBeretChemist # DS14
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabChem
    gloves: ClothingHandsGlovesLatex
