// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using Content.Shared.DeadSpace.ConsoleCraft;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Prototypes;
using Robust.Shared.Map;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.ConsoleCraft;

[GenerateTypedNameReferences]
public sealed partial class ConsoleCraftConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    private SpriteSystem? _spriteSystem;
    private EntityUid? _previewEntity;

    public event Action<string>? OnBlueprintSelected;
    public event Action? OnBackPressed;
    public event Action? OnCraftPressed;
    public event Action? OnEjectPressed;
    public event Action? OnDismantlePressed;

    public ConsoleCraftConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BackButton.OnPressed += _ => OnBackPressed?.Invoke();
        CraftButton.OnPressed += _ => OnCraftPressed?.Invoke();
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
        DismantleButton.OnPressed += _ => OnDismantlePressed?.Invoke();
    }

    public void UpdateState(ConsoleCraftConsoleState state, IEntityManager entMan)
    {
        _spriteSystem ??= _sysMan.GetEntitySystem<SpriteSystem>();

        NoStationLabel.Visible = state.NoStation;

        var showingDetail = state.SelectedRecipeId != null && !state.NoStation;
        ListPanel.Visible = !showingDetail;
        DetailPanel.Visible = showingDetail;

        if (!showingDetail)
        {
            DeletePreviewEntity();
            PopulateBlueprintList(state.AvailableRecipes);
        }
        else
        {
            PopulateDetailView(state, entMan);
        }
    }

    private void PopulateBlueprintList(List<ConsoleCraftBlueprintEntry> recipes)
    {
        BlueprintListContainer.RemoveAllChildren();

        if (recipes.Count == 0)
        {
            BlueprintListContainer.AddChild(new Label
            {
                Text = Loc.GetString("consolecraft-no-blueprints-loaded"),
                StyleClasses = { "LabelSubText" },
            });
            return;
        }

        foreach (var entry in recipes.OrderBy(r => r.Name))
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 8,
            };

            var nameLabel = new Label
            {
                Text = string.IsNullOrEmpty(entry.Name) ? entry.RecipeId : entry.Name,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            var usesText = entry.RemainingCrafts.HasValue
                ? Loc.GetString("consolecraft-uses-remaining", ("count", entry.RemainingCrafts.Value))
                : Loc.GetString("consolecraft-uses-infinite");

            var usesColor = entry.RemainingCrafts is <= 1 ? "#FF9900" : "#AAFFAA";

            var usesLabel = new RichTextLabel { VerticalAlignment = VAlignment.Center };
            usesLabel.SetMessage(FormattedMessage.FromMarkupPermissive($"[color={usesColor}]{usesText}[/color]"));

            var selectBtn = new Button
            {
                Text = Loc.GetString("consolecraft-select-button"),
                MinWidth = 80,
            };

            var capturedId = entry.RecipeId;
            selectBtn.OnPressed += _ => OnBlueprintSelected?.Invoke(capturedId);

            row.AddChild(nameLabel);
            row.AddChild(usesLabel);
            row.AddChild(selectBtn);

            if (!string.IsNullOrEmpty(entry.Description))
                row.ToolTip = entry.Description;

            BlueprintListContainer.AddChild(row);
        }
    }

    private void PopulateDetailView(ConsoleCraftConsoleState state, IEntityManager entMan)
    {
        if (state.CraftItemProtoId != null &&
            _proto.TryIndex<EntityPrototype>(state.CraftItemProtoId, out var entityProto))
        {
            ItemNameLabel.Text = entityProto.Name;

            if (_spriteSystem != null)
            {
                var currentProto = _previewEntity.HasValue && entMan.EntityExists(_previewEntity.Value)
                    ? entMan.GetComponent<MetaDataComponent>(_previewEntity.Value).EntityPrototype?.ID
                    : null;

                if (currentProto != state.CraftItemProtoId)
                {
                    DeletePreviewEntity();

                    var dummy = entMan.SpawnEntity(state.CraftItemProtoId, MapCoordinates.Nullspace);
                    _previewEntity = dummy;
                    ItemSpriteView.SetEntity(dummy);
                }
            }
        }
        else
        {
            ItemNameLabel.Text = string.Empty;
            ItemSpriteView.SetEntity(null);
            DeletePreviewEntity();
        }

        RequiredContainer.RemoveAllChildren();
        foreach (var req in state.RequiredStatus)
        {
            var color = req.Satisfied ? "#00FF88" : "#FF6666";
            var label = new RichTextLabel();
            label.SetMessage(FormattedMessage.FromMarkupPermissive(
                $"[color={color}]● {req.Label}  {req.Inserted}/{req.Required}[/color]"));
            RequiredContainer.AddChild(label);
        }

        ModulesContainer.RemoveAllChildren();
        if (state.ModuleStatus.Count == 0)
        {
            ModulesContainer.AddChild(new Label
            {
                Text = Loc.GetString("consolecraft-no-modules"),
                StyleClasses = { "LabelSubText" },
            });
        }
        else
        {
            var idx = 1;
            foreach (var mod in state.ModuleStatus)
            {
                var label = new Label
                {
                    Text = $"{idx}. {mod.Description}",
                    FontColorOverride = Color.FromHex(mod.Inserted ? "#00FF88" : "#AAAAAA"),
                    HorizontalExpand = true,
                };
                ModulesContainer.AddChild(label);
                idx++;
            }
        }

        if (state.CraftInProgress)
        {
            StatusLabel.Text = Loc.GetString("consolecraft-crafting");
            StatusLabel.FontColorOverride = Color.Yellow;
        }
        else if (state.NoStation)
        {
            StatusLabel.Text = Loc.GetString("consolecraft-no-station-warning");
            StatusLabel.FontColorOverride = Color.Red;
        }
        else if (state.CanCraft)
        {
            var usesInfo = state.SelectedBlueprintRemainingCrafts.HasValue
                ? Loc.GetString("consolecraft-uses-remaining",
                    ("count", state.SelectedBlueprintRemainingCrafts.Value))
                : Loc.GetString("consolecraft-uses-infinite");
            StatusLabel.Text = $"{Loc.GetString("consolecraft-ready")} — {usesInfo}";
            StatusLabel.FontColorOverride = state.SelectedBlueprintRemainingCrafts is <= 1
                ? Color.Orange
                : Color.LimeGreen;
        }
        else
        {
            StatusLabel.Text = Loc.GetString("consolecraft-missing-materials");
            StatusLabel.FontColorOverride = Color.OrangeRed;
        }

        CraftButton.Disabled = !state.CanCraft || state.CraftInProgress || state.NoStation;
        EjectButton.Disabled = state.CraftInProgress;
        BackButton.Disabled = state.CraftInProgress;
        DismantleButton.Disabled = !state.CanDismantle || state.CraftInProgress || state.NoStation;
    }

    private void DeletePreviewEntity()
    {
        if (_previewEntity.HasValue)
        {
            if (_entMan.EntityExists(_previewEntity.Value))
                _entMan.DeleteEntity(_previewEntity.Value);
            _previewEntity = null;
        }
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            DeletePreviewEntity();

        base.Dispose(disposing);
    }
}
