using System.Linq;
using Content.Client.Decals.UI;
using Content.Client.DeadSpace.Stylesheets;
using Content.Shared.Administration;
using Content.Shared.Corvax.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Shared.DeadSpace.Languages.Prototypes;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;

        private readonly List<TTSVoicePrototype> _voices; // Corvax-TTS
        private readonly List<LanguagePrototype> _languages; // DS14-Languages
        public Action<string>? OnVoiceChange; // Corvax-TTS
        private static readonly ProtoId<LanguagePrototype> FirstLanguageId = "GeneralLanguage"; // DS14-Languages

        // DS14-announce-start
        private LineEdit? _colorHexEdit;
        private Button? _colorPreviewBtn;
        private PaletteColorPicker? _colorPalette;
        private LineEdit? _soundPathEdit;
        private LineEdit? _soundVolumeEdit;
        private LineEdit? _senderEdit;

        private const int MaxSenderLength = 32;

        private const int ColorShortLength = 3;
        private const int ColorLongLength = 6;

        private const float MinSoundVolume = 1f;
        private const float MaxSoundVolume = 10f;
        private const float DefaultSoundVolume = 5f;

        private const int TargetAllId = 0;
        private const int TargetServerId = 1;
        private const int FirstMapTargetId = 10;
        private const string OptionBalanceSpacerStyle = "DS14AnnounceOptionBalanceSpacer";
        // DS14-announce-end

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // DS14-announce-start
            _colorHexEdit = SafeFind<LineEdit>("ColorHex", c => c.OnTextChanged += OnColorTextChanged);
            _colorPreviewBtn = SafeFind<Button>("ColorPreview", c => c.OnPressed += OnColorPreviewPressed);
            _soundPathEdit = SafeFind<LineEdit>("SoundPath", c => c.OnTextChanged += OnSoundPathChanged);
            _soundVolumeEdit = SafeFind<LineEdit>("SoundVolume", c => c.OnTextChanged += OnSoundVolumeChanged);
            _senderEdit = SafeFind<LineEdit>("Sender", c => c.OnTextChanged += OnSenderChanged);

            AddDs14OptionStyles(VoiceSelector, LanguageSelector, AnnounceMethod);
            VoiceSelector.Filterable = true;
            CenterButtonText(AnnounceButton);
            CenterOptionButtonText(AnnounceMethod);
            BalanceOptionButtonTriangle(AnnounceMethod);
            EnableTTS.Label.AddStyleClass(DeadSpaceMenuSheetlet.ProfileLabel);
            CustomTTS.Label.AddStyleClass(DeadSpaceMenuSheetlet.ProfileLabel);
            KeepWindowOpen.Label.AddStyleClass(DeadSpaceMenuSheetlet.ProfileLabel);
            UpdateColorPreview();
            SetAnnouncementTargets([]);
            // DS14-announce-end
            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            VoiceSelector.OnItemSelected += AnnounceMethodOnOnTTSItemSelected;
            LanguageSelector.OnItemSelected += AnnounceMethodOnLanguageSelected; // DS14-Languages
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;

            var protoManager = IoCManager.Resolve<IPrototypeManager>(); // DS14-Languages

            // Corvax-TTS-Start
            _voices = protoManager // DS14-Languages
                .EnumeratePrototypes<TTSVoicePrototype>()
                .OrderBy(o => Loc.GetString(o.Name))
                .ToList();
            for (var i = 0; i < _voices.Count; i++)
            {
                var name = Loc.GetString(_voices[i].Name);
                VoiceSelector.AddItem(name);
                VoiceSelector.SetItemMetadata(i, _voices[i].ID);
            }
            // Corvax-TTS-End

            // DS14-Languages-start
            _languages = protoManager.EnumeratePrototypes<LanguagePrototype>()
                .OrderBy(o => Loc.GetString(o.Name))
                .ToList();

            var defaultLanguage = _languages.FirstOrDefault(l => l.ID == FirstLanguageId);
            if (defaultLanguage != null)
            {
                _languages.Remove(defaultLanguage);
                _languages.Insert(0, defaultLanguage);
            }

            for (var i = 0; i < _languages.Count; i++)
            {
                var name = Loc.GetString(_languages[i].Name);
                LanguageSelector.AddItem(name);
                LanguageSelector.SetItemMetadata(i, _languages[i].ID);
            }
            // DS14-Languages-end
        }

        // DS14-announce-start
        private T? SafeFind<T>(string name, Action<T>? init = null) where T : Control
        {
            var ctrl = FindControl<T>(name);
            if (ctrl == null)
            {
                Logger.Warning($"AdminAnnounceWindow: control '{name}' not found.");
                return null;
            }

            init?.Invoke(ctrl);
            return ctrl;
        }

        private void OnColorTextChanged(LineEdit.LineEditEventArgs args)
        {
            if (_colorHexEdit == null) return;

            var t = _colorHexEdit.Text.Trim();
            if (t.StartsWith('#'))
                t = t[1..];

            t = new string(t.Where(Uri.IsHexDigit).ToArray());
            if (t.Length > ColorLongLength)
                t = t[..ColorLongLength];

            if (_colorHexEdit.Text != t)
                _colorHexEdit.Text = t;

            UpdateColorPreview();
        }

        private void UpdateColorPreview()
        {
            if (_colorPreviewBtn == null)
                return;

            if (!TryGetPreviewColor(out var color))
            {
                _colorPreviewBtn.StyleBoxOverride = BuildColorPreviewStyle(Color.FromHex("#0b1118"));
                return;
            }

            _colorPreviewBtn.StyleBoxOverride = BuildColorPreviewStyle(color);
        }

        private bool TryGetPreviewColor(out Color color)
        {
            color = default;
            if (_colorHexEdit == null)
                return false;

            var t = _colorHexEdit.Text.Trim();
            if (t.Length != ColorShortLength && t.Length != ColorLongLength)
                return false;

            try
            {
                color = Color.FromHex("#" + t);
                return true;
            }
            catch
            {
                return false;
            }
        }

        private static StyleBoxFlat BuildColorPreviewStyle(Color color)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = color,
                BorderColor = Color.FromHex("#3b4e60"),
                BorderThickness = new Thickness(1),
            };
        }

        private void OnColorPreviewPressed(BaseButton.ButtonEventArgs args)
        {
            if (_colorHexEdit == null)
                return;

            if (_colorPalette == null)
            {
                _colorPalette = new PaletteColorPicker();
                _colorPalette.PaletteList.OnItemSelected += OnPaletteColorSelected;
                _colorPalette.OpenCenteredLeft();
                return;
            }

            if (_colorPalette.IsOpen)
                _colorPalette.Close();
            else
                _colorPalette.Open();
        }

        private void OnPaletteColorSelected(ItemList.ItemListSelectedEventArgs args)
        {
            if (_colorHexEdit == null)
                return;

            var selected = args.ItemList.GetSelected().FirstOrDefault();
            if (selected?.Metadata is not Color color)
                return;

            _colorHexEdit.Text = color.ToHexNoAlpha().TrimStart('#');
            UpdateColorPreview();
        }

        private void OnSoundPathChanged(LineEdit.LineEditEventArgs args)
        {
            if (_soundPathEdit == null)
                return;
            var filtered = new string(_soundPathEdit.Text
                .Where(c => char.IsLetterOrDigit(c) || c is '/' or '.' or '_' or '-')
                .ToArray());
            if (_soundPathEdit.Text != filtered)
                _soundPathEdit.Text = filtered;
        }

        private void OnSoundVolumeChanged(LineEdit.LineEditEventArgs args)
        {
            if (_soundVolumeEdit == null) return;

            if (float.TryParse(_soundVolumeEdit.Text, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var vol))
            {
                vol = Math.Clamp(vol, MinSoundVolume, MaxSoundVolume);
                _soundVolumeEdit.Text = vol.ToString(System.Globalization.CultureInfo.InvariantCulture);
            }
        }

        private void OnSenderChanged(LineEdit.LineEditEventArgs args)
        {
            if (_senderEdit == null) return;

            var t = new string(_senderEdit.Text.Where(c => !char.IsControl(c)).ToArray());
            if (t.Length > MaxSenderLength)
                t = t[..MaxSenderLength];
            if (_senderEdit.Text != t)
                _senderEdit.Text = t;
        }

        private static void AddDs14OptionStyles(params OptionButton[] options)
        {
            foreach (var option in options)
            {
                option.AddStyleClass(DeadSpaceMenuSheetlet.ProfileControl);
                if (!option.OptionStyleClasses.Contains(DeadSpaceMenuSheetlet.ProfileControl))
                    option.OptionStyleClasses.Add(DeadSpaceMenuSheetlet.ProfileControl);
            }
        }

        private static void CenterButtonText(Button button)
        {
            button.TextAlign = Label.AlignMode.Center;
            button.Label.HorizontalExpand = true;
            button.Label.HorizontalAlignment = HAlignment.Stretch;
            button.Label.Align = Label.AlignMode.Center;
        }

        private static void CenterOptionButtonText(Control control)
        {
            if (control is Label label &&
                label.StyleClasses.Contains(OptionButton.StyleClassOptionButton))
            {
                label.HorizontalExpand = true;
                label.Align = Label.AlignMode.Center;
                return;
            }

            foreach (var child in control.Children)
            {
                CenterOptionButtonText(child);
            }
        }

        private static void BalanceOptionButtonTriangle(OptionButton option)
        {
            var hBox = option.Children.OfType<BoxContainer>().FirstOrDefault();
            if (hBox == null ||
                hBox.Children.Any(child => child.StyleClasses.Contains(OptionBalanceSpacerStyle)))
            {
                return;
            }

            var spacer = new Control
            {
                MinWidth = 18,
                SetWidth = 18,
                MouseFilter = MouseFilterMode.Ignore
            };
            spacer.AddStyleClass(OptionBalanceSpacerStyle);
            hBox.AddChild(spacer);
            spacer.SetPositionInParent(0);
        }

        public void SetAnnouncementTargets(IReadOnlyList<AdminAnnounceTargetEntry> targets)
        {
            var previous = SelectedTarget;
            var selectedId = TargetAllId;
            var index = 0;
            var mapId = FirstMapTargetId;

            AnnounceMethod.Clear();
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-target-all"), TargetAllId);
            AnnounceMethod.SetItemMetadata(index++, AdminAnnounceTargetSelection.All);

            foreach (var target in targets)
            {
                var selection = new AdminAnnounceTargetSelection(AdminAnnounceType.Map, target.Grid);

                AnnounceMethod.AddItem(target.Name, mapId);
                AnnounceMethod.SetItemMetadata(index++, selection);

                if (previous.Type == AdminAnnounceType.Map && previous.Grid == target.Grid)
                    selectedId = mapId;

                mapId++;
            }

            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"), TargetServerId);
            AnnounceMethod.SetItemMetadata(index, AdminAnnounceTargetSelection.Server);

            if (previous.Type == AdminAnnounceType.Server)
                selectedId = TargetServerId;

            AnnounceMethod.SelectId(selectedId);
            CenterOptionButtonText(AnnounceMethod);
            CenterNestedButtonText(AnnounceMethod.OptionsScroll);
        }

        private static void CenterNestedButtonText(Control control)
        {
            if (control is Button button)
                CenterButtonText(button);

            foreach (var child in control.Children)
            {
                CenterNestedButtonText(child);
            }
        }
        // DS14-announce-end

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            // DS14-announce: keep custom sender editable for every target mode.
            Announcer.Editable = true;
        }

        // Corvax-TTS-Start
        private void AnnounceMethodOnOnTTSItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            VoiceSelector.SelectId(args.Id);
        }
        // Corvax-TTS-End

        // DS14-Languages-start
        private void AnnounceMethodOnLanguageSelected(OptionButton.ItemSelectedEventArgs args)
        {
            LanguageSelector.SelectId(args.Id);
        }

        public string ColorHexText
        {
            get
            {
                var t = _colorHexEdit?.Text.Trim() ?? "";
                return (t.Length == ColorShortLength || t.Length == ColorLongLength) ? t : "";
            }
        }

        public string SoundPathText => _soundPathEdit?.Text ?? "";
        public string SenderText => _senderEdit?.Text ?? "";
        public AdminAnnounceTargetSelection SelectedTarget
        {
            get
            {
                if (AnnounceMethod.ItemCount == 0)
                    return AdminAnnounceTargetSelection.All;

                return AnnounceMethod.SelectedMetadata is AdminAnnounceTargetSelection selection
                    ? selection
                    : AdminAnnounceTargetSelection.All;
            }
        }

        public float SoundVolumeValue
        {
            get
            {
                if (_soundVolumeEdit != null &&
                    float.TryParse(_soundVolumeEdit.Text, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var volume))
                {
                    return Math.Clamp(volume, MinSoundVolume, MaxSoundVolume);
                }
                return DefaultSoundVolume;
            }
        }

        public override void Close()
        {
            _colorPalette?.Close();
            base.Close();
        }
        // DS14-announce-end
    }
}
