using System;
using System.Collections.Generic;
using Content.Shared.DeadSpace.CartridgeLoader.Cartridges;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using System.Numerics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ScannerProgramUiFragment : BoxContainer
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private List<ScannedDocument> _documents = new();
    private int _selectedIndex = -1;
    private int _editingIndex = -1;

    public event Action<int>? OnDocumentDeleted;
    public event Action<int, string>? OnDocumentRenamed;
    public event Action? OnAllDeleted;

    public ScannerProgramUiFragment()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        ScannerTitle.Text = Loc.GetString("scanner-program-title");
        DetailTitle.Text = Loc.GetString("scanner-program-document-title");
        ClearAllBtn.Text = Loc.GetString("scanner-program-clear");
        BackBtn.Text = Loc.GetString("scanner-program-back");

        ClearAllBtn.OnPressed += _ => OnAllDeleted?.Invoke();
        BackBtn.OnPressed += _ => ShowList();
    }

    public void UpdateState(List<ScannedDocument> documents, int selectedIndex)
    {
        _documents = documents;

        if (selectedIndex >= 0)
            _selectedIndex = selectedIndex;
        else if (_selectedIndex >= _documents.Count)
            _selectedIndex = _documents.Count - 1;

        if (_editingIndex >= _documents.Count)
            _editingIndex = -1;

        DocumentList.RemoveAllChildren();

        for (int i = 0; i < _documents.Count; i++)
        {
            var doc = _documents[i];
            var index = i;

            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                Margin = new Thickness(2),
                StyleClasses = { "DS14MenuListRow" },
            };

            var row = new BoxContainer
            {
                HorizontalExpand = true,
                Orientation = LayoutOrientation.Horizontal,
            };

            if (_editingIndex == index)
            {
                var editBox = new LineEdit
                {
                    Text = doc.Name ?? Loc.GetString("scanner-program-document-number", ("number", index + 1)),
                    HorizontalExpand = true,
                    MinSize = new Vector2(0, 28),
                };

                var confirmBtn = new Button
                {
                    Text = Loc.GetString("scanner-program-ok"),
                    MinSize = new Vector2(36, 28),
                };
                confirmBtn.OnPressed += _ =>
                {
                    var newName = editBox.Text.Trim();
                    if (!string.IsNullOrWhiteSpace(newName))
                    {
                        _editingIndex = -1;
                        OnDocumentRenamed?.Invoke(index, newName);
                    }
                };

                editBox.OnKeyBindDown += args =>
                {
                    if (args.Function == "TextSubmit")
                    {
                        var newName = editBox.Text.Trim();
                        if (!string.IsNullOrWhiteSpace(newName))
                        {
                            _editingIndex = -1;
                            OnDocumentRenamed?.Invoke(index, newName);
                        }
                    }
                };

                row.AddChild(editBox);
                row.AddChild(confirmBtn);
            }
            else
            {
                var nameLabel = new Label
                {
                    Text = doc.Name ?? Loc.GetString("scanner-program-document-number", ("number", index + 1)),
                    HorizontalExpand = true,
                    ClipText = true,
                    MinSize = new Vector2(0, 28),
                };

                var viewBtn = new Button
                {
                    Text = Loc.GetString("scanner-program-view"),
                    MinSize = new Vector2(50, 28),
                };
                viewBtn.OnPressed += _ =>
                {
                    _selectedIndex = index;
                    ShowDetail(index);
                };

                var renameBtn = new Button
                {
                    Text = Loc.GetString("scanner-program-rename"),
                    MinSize = new Vector2(60, 28),
                };
                renameBtn.OnPressed += _ =>
                {
                    _editingIndex = index;
                    UpdateState(_documents, -1);
                };

                var deleteBtn = new Button
                {
                    Text = "X",
                    MinSize = new Vector2(28, 28),
                };
                deleteBtn.OnPressed += _ => OnDocumentDeleted?.Invoke(index);

                row.AddChild(nameLabel);
                row.AddChild(viewBtn);
                row.AddChild(renameBtn);
                row.AddChild(deleteBtn);
            }

            panel.AddChild(row);
            DocumentList.AddChild(panel);
        }

        if (DetailView.Visible)
            UpdateDetailContent();
    }

    private void ShowList()
    {
        ListView.Visible = true;
        DetailView.Visible = false;
    }

    private void ShowDetail(int index)
    {
        ListView.Visible = false;
        DetailView.Visible = true;
        UpdateDetailContent();
    }

    private void UpdateDetailContent()
    {
        if (_selectedIndex < 0 || _selectedIndex >= _documents.Count)
        {
            DetailContent.SetMessage(string.Empty);
            return;
        }

        var doc = _documents[_selectedIndex];
        var text = doc.Content;

        if (doc.Signatures.Count > 0)
            text += $"\n\n[color=#4169E1][italic]{string.Join(", ", doc.Signatures)}[/italic][/color]";

        if (doc.StampedBy.Count > 0)
        {
            text += $"\n\n[color=gray]{Loc.GetString("scanner-program-stamps")}[/color]";
            foreach (var stamp in doc.StampedBy)
            {
                var stampName = string.IsNullOrEmpty(stamp.StampedName)
                    ? Loc.GetString("scanner-program-unknown")
                    : GetStampDisplayText(stamp.StampedName);
                text += $"\n[color={stamp.StampedColor.ToHex()}]{stampName}[/color]";
            }
        }

        DetailContent.SetMessage(FormattedMessage.FromMarkupPermissive(text));
    }

    private string GetStampDisplayText(string stampName)
    {
        return _loc.TryGetString(stampName, out var localized) ? localized : stampName;
    }
}
