using System.Numerics;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Thief;
using Robust.Client.GameObjects;

namespace Content.Client.Thief;

[GenerateTypedNameReferences]
public sealed partial class ThiefBackpackSet : Control
{
    private static readonly Vector2 MinimumIconSize = new(64f, 64f);
    private static readonly Vector2 IconScale = new(2f, 2f);

    public ThiefBackpackSet(ThiefBackpackSetInfo set, SpriteSystem spriteSystem)
    {
        RobustXamlLoader.Load(this);

        var texture = spriteSystem.Frame0(set.Sprite);
        Icon.Texture = texture;
        Icon.TextureScale = IconScale;
        Icon.SetSize = Vector2.Max(texture.Size * IconScale, MinimumIconSize);
        SetName.Text = Loc.GetString(set.Name);
        SetDescription.Text = Loc.GetString(set.Description);
        SetButton.Text = Loc.GetString(set.Selected ? "thief-backpack-button-deselect" : "thief-backpack-button-select");
        // DS14-start: selected state uses the common semantic button palette and all pseudo-states.
        if (set.Selected)
            SetButton.AddStyleClass(StyleClass.Positive);
        // DS14-end
    }
}
