using System.Numerics;
using System.Text;
using Content.Client.DeadSpace.Chat;
using Content.Client.UserInterface.Systems.Chat.Controls;
using Content.Shared.Chat;
using Content.Shared.Input;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.UserInterface.Systems.Chat.Widgets;

[GenerateTypedNameReferences]
[Virtual]
public partial class ChatBox : UIWidget
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly ILogManager _log = default!;

    private readonly ISawmill _sawmill;
    private readonly ChatUIController _controller;

    public bool Main { get; set; }

    public ChatSelectChannel SelectedChannel => ChatInput.ChannelSelector.SelectedChannel;
    // DS14-start
    private ChatBox? _ownerChat;
    private Vector2 _ownerMinSize;
    private Vector2 _ownerSetSize;
    private bool _ownerChannelSelectorVisible;
    private bool _ownerFilterButtonVisible;
    private bool _ownerVisible;
    private bool _ownerMain;
    public event Action<bool>? OnCycleChatChannel;
    // DS14-end

    public ChatBox()
    {
        RobustXamlLoader.Load(this);
        _sawmill = _log.GetSawmill("chat");
        ChatInput.Input.OnTextEntered += OnTextEntered;
        ChatInput.Input.OnKeyBindDown += OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged += OnTextChanged;
        ChatInput.Input.OnFocusEnter += OnFocusEnter;
        ChatInput.Input.OnFocusExit += OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect += OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter += OnChannelFilter;
        ChatInput.FilterButton.Popup.OnNewHighlights += OnNewHighlights;
        _controller = UserInterfaceManager.GetUIController<ChatUIController>();
        _controller.MessageAdded += OnMessageAdded;
        _controller.HighlightsUpdated += OnHighlightsUpdated;
        _controller.RegisterChat(this);
    }

    private void OnTextEntered(LineEditEventArgs args)
    {
        _controller.SendMessage(this, SelectedChannel);
    }

    private void OnMessageAdded(ChatMessage msg)
    {
        _sawmill.Debug($"{msg.Channel}: {msg.Message}");
        if (!ChatInput.FilterButton.Popup.IsActive(msg.Channel))
        {
            return;
        }

        if (msg is { Read: false, AudioPath: { } })
            _entManager.System<AudioSystem>().PlayGlobal(msg.AudioPath, Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));

        msg.Read = true;

        var color = msg.MessageColorOverride ?? msg.Channel.TextColor();

        // DS14-start
        var wrappedMessage = msg.WrappedMessage;
        string? commandLinkPrefix = null;
        if (_entManager.SystemOrNull<ChatEntityCommandLinkSystem>() is { } commandLinks &&
            commandLinks.TryGetPrefix(msg, out var prefix))
        {
            commandLinkPrefix = prefix;
        }

        AddLine(wrappedMessage, color, commandLinkPrefix);
        // DS14-end
    }

    private void OnHighlightsUpdated(string highlights)
    {
        ChatInput.FilterButton.Popup.UpdateHighlights(highlights);
    }

    private void OnChannelSelect(ChatSelectChannel channel)
    {
        _controller.UpdateSelectedChannel(this);
    }

    public void Repopulate()
    {
        Contents.Clear();

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }
    }

    private void OnChannelFilter(ChatChannel channel, bool active)
    {
        Contents.Clear();

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }

        if (active)
        {
            _controller.ClearUnfilteredUnreads(channel);
        }
    }

    private void OnNewHighlights(string highlighs)
    {
        _controller.UpdateHighlights(highlighs);
    }

    public void AddLine(string message, Color color, string? commandLinkPrefix = null) // DS14
    {
        var formatted = new FormattedMessage(3);
        formatted.PushColor(color);
        // DS14-start
        if (commandLinkPrefix != null)
        {
            if (!formatted.TryAddMarkup(commandLinkPrefix, out var prefixError))
            {
                _sawmill.Warning($"Invalid trusted chat command-link markup, dropping prefix: {prefixError}\n{commandLinkPrefix}");
            }
            else
            {
                formatted.AddText(" ");
            }

            message = EscapeCommandLinkMarkup(message);
        }

        if (!formatted.TryAddMarkup(message, out var error))
        {
            _sawmill.Warning($"Invalid chat markup, falling back to permissive parsing: {error}\n{message}");
            formatted.AddMarkupPermissive(message);
        }
        // DS14-end
        formatted.Pop();
        // DS14-start
        if (commandLinkPrefix != null)
            Contents.AddMessage(formatted, ChatEntityCommandLinkSystem.TagsWithCommandLinks);
        else
            Contents.AddMessage(formatted);
        // DS14-end
    }

    // DS14-start
    private static string EscapeCommandLinkMarkup(string message)
    {
        StringBuilder? builder = null;

        for (var i = 0; i < message.Length; i++)
        {
            if (message[i] != '[' ||
                IsEscaped(message, i) ||
                !StartsCommandLinkTag(message, i))
            {
                builder?.Append(message[i]);
                continue;
            }

            builder ??= new StringBuilder(message.Length + 1).Append(message, 0, i);
            builder.Append('\\');
            builder.Append(message[i]);
        }

        return builder?.ToString() ?? message;
    }

    private static bool StartsCommandLinkTag(string message, int bracketIndex)
    {
        return StartsTag(message, bracketIndex, "cmdlink") ||
               StartsTag(message, bracketIndex, "/cmdlink");
    }

    private static bool StartsTag(string message, int bracketIndex, string tagName)
    {
        var tagStart = bracketIndex + 1;
        if (tagStart + tagName.Length > message.Length)
            return false;

        if (!message.AsSpan(tagStart, tagName.Length).Equals(tagName, StringComparison.OrdinalIgnoreCase))
            return false;

        var delimiterIndex = tagStart + tagName.Length;
        return delimiterIndex >= message.Length ||
               message[delimiterIndex] is ']' or '=' or ' ' or '\t' or '/';
    }

    private static bool IsEscaped(string message, int index)
    {
        var backslashes = 0;
        for (var i = index - 1; i >= 0 && message[i] == '\\'; i--)
        {
            backslashes++;
        }

        return backslashes % 2 == 1;
    }
    // DS14-end

    public void Focus(ChatSelectChannel? channel = null)
    {
        var input = ChatInput.Input;
        var selectStart = Index.End;

        if (channel != null)
            ChatInput.ChannelSelector.Select(channel.Value);
        input.GrabKeyboardFocus();
        input.IgnoreNext = true;

        input.CursorPosition = input.Text.Length;
        input.SelectionStart = selectStart.GetOffset(input.Text.Length);
    }

    public void CycleChatChannel(bool forward)
    {
        var idx = Array.IndexOf(ChannelSelectorPopup.ChannelSelectorOrder, SelectedChannel);
        do
        {
            // go over every channel until we find one we can actually select.
            idx += forward ? 1 : -1;
            idx = MathHelper.Mod(idx, ChannelSelectorPopup.ChannelSelectorOrder.Length);
        } while ((_controller.SelectableChannels & ChannelSelectorPopup.ChannelSelectorOrder[idx]) == 0);

        SafelySelectChannel(ChannelSelectorPopup.ChannelSelectorOrder[idx]);
        OnCycleChatChannel?.Invoke(forward); // DS14
    }

    public void SafelySelectChannel(ChatSelectChannel toSelect)
    {
        toSelect = _controller.MapLocalIfGhost(toSelect);
        if ((_controller.SelectableChannels & toSelect) == 0)
            return;

        ChatInput.ChannelSelector.Select(toSelect);
    }

    private void OnInputKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.TextReleaseFocus)
        {
            ChatInput.Input.ReleaseKeyboardFocus();
            ChatInput.Input.Clear();
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelForward)
        {
            CycleChatChannel(true);
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelBackward)
        {
            CycleChatChannel(false);
            args.Handle();
        }
    }

    private void OnTextChanged(LineEditEventArgs args)
    {
        // Update channel select button to correct channel if we have a prefix.
        _controller.UpdateSelectedChannel(this);

        // Warn typing indicator about change
        _controller.NotifyChatTextChange();
    }

    private void OnFocusEnter(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(true);
    }

    private void OnFocusExit(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(false);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing) return;
        ClearInputs(); // DS14
        _controller.UnregisterChat(this);
        ChatInput.Input.OnTextEntered -= OnTextEntered;
        ChatInput.Input.OnKeyBindDown -= OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged -= OnTextChanged;
        ChatInput.ChannelSelector.OnChannelSelect -= OnChannelSelect;
    }

    // DS14-start
    public void SetInputs(ref ChatBox args)
    {
        ClearInputs();
        _ownerChat = args;
        _ownerMinSize = args.MinSize;
        _ownerSetSize = args.SetSize;
        _ownerChannelSelectorVisible = args.ChatInput.ChannelSelector.Visible;
        _ownerFilterButtonVisible = args.ChatInput.FilterButton.Visible;
        _ownerVisible = args.Visible;
        _ownerMain = args.Main;
        Main = args.Main;
        args.Main = false;
        args.Visible = false;
        args.MinSize = new Vector2(0, 0);
        args.SetSize = new Vector2(0, 0);
        args.ChatInput.Input.OnKeyBindDown += OnInputKeyBindDown;
        args.ChatInput.Input.OnTextChanged += PopOutSetText;
        args.ChatInput.Input.OnTextEntered += PopOutOnTextEntered;
        args.ChatInput.FilterButton.Popup.OnChannelFilter += OnChannelFilter;
        args.ChatInput.FilterButton.Popup.OnNewHighlights += OnNewHighlights;
        args.OnCycleChatChannel += CycleChatChannel;
        ChatInput.ChannelSelector.OnChannelSelect += OnPopOutChannelSelect;
        args.ChatInput.ChannelSelector.OnChannelSelect += OnOwnerChannelSelect;
        args.ChatInput.ChannelSelector.Visible = false;
        args.ChatInput.FilterButton.Visible = false;
    }

    public void ClearInputs()
    {
        if (_ownerChat is not { } owner)
            return;

        owner.ChatInput.Input.OnKeyBindDown -= OnInputKeyBindDown;
        owner.ChatInput.Input.OnTextChanged -= PopOutSetText;
        owner.ChatInput.Input.OnTextEntered -= PopOutOnTextEntered;
        owner.ChatInput.FilterButton.Popup.OnChannelFilter -= OnChannelFilter;
        owner.ChatInput.FilterButton.Popup.OnNewHighlights -= OnNewHighlights;
        owner.OnCycleChatChannel -= CycleChatChannel;
        ChatInput.ChannelSelector.OnChannelSelect -= OnPopOutChannelSelect;
        owner.ChatInput.ChannelSelector.OnChannelSelect -= OnOwnerChannelSelect;
        owner.MinSize = _ownerMinSize;
        owner.SetSize = _ownerSetSize;
        owner.ChatInput.ChannelSelector.Visible = _ownerChannelSelectorVisible;
        owner.ChatInput.FilterButton.Visible = _ownerFilterButtonVisible;
        owner.Visible = _ownerVisible;
        owner.Main = _ownerMain;
        Main = false;
        _ownerChat = null;
    }

    public void PopOutSetText(LineEditEventArgs args)
    {
        ChatInput.Input.SetText(args.Text, false);
    }
    public void PopOutOnTextEntered(LineEditEventArgs args)
    {
        ChatInput.Input.Clear();
    }

    private void OnPopOutChannelSelect(ChatSelectChannel channel)
    {
        _ownerChat?.ChatInput.ChannelSelector.Select(channel);
    }

    private void OnOwnerChannelSelect(ChatSelectChannel channel)
    {
        ChatInput.ChannelSelector.Select(channel);
    }
    // DS14-end
}
