using System.Linq;
using System.Numerics;
using Content.Client.GameTicking.Managers;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.DeadSpace.PatrolTablet;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.DeadSpace.PatrolTablet;

[GenerateTypedNameReferences]
public sealed partial class PatrolTabletWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    private readonly SpriteSystem _sprite;
    private readonly ClientGameTicker _gameTicker;

    public Action<string, string>? OnRenameSquad;
    public Action<string>? OnBulkAssignSquad;
    public Action? OnClearList;
    public Action<string>? OnClearSquad;
    public Action<string>? OnDeleteSquad;
    public Action<string, string>? OnCreateSquad;

    public PatrolTabletWindow()
    {
        MinSize = SetSize = new Vector2(900, 600);
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _sprite = _entManager.System<SpriteSystem>();
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();

        Title = Loc.GetString("patrol-tablet-title");
        ClearListButton.OnPressed += _ => OnClearList?.Invoke();
        CreateSquadButton.OnPressed += _ => OpenCreateSquadDialog();

        UpdateShiftTime();
    }

    private void OpenCreateSquadDialog()
    {
        var dialog = new CreateSquadDialog(_sprite, _prototype);
        dialog.OnCreate += (name, iconId) =>
        {
            OnCreateSquad?.Invoke(name, iconId);
            dialog.Close();
        };
        dialog.OnClose += dialog.Close;
    }

    private void UpdateShiftTime()
    {
        var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
        ShiftTimeLabel.SetMarkup(Loc.GetString("patrol-tablet-shift-time",
            ("time", stationTime.ToString(@"hh\:mm\:ss"))));
    }

    public void UpdateState(PatrolTabletUpdateState state)
    {
        UpdateShiftTime();
        UpdateOfficers(state.Officers);
        UpdateSquads(state.Squads);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        UpdateShiftTime();
    }

    private void UpdateOfficers(List<PatrolOfficerInfo> officers)
    {
        OfficersContainer.RemoveAllChildren();

        foreach (var officer in officers)
        {
            var entry = new OfficerEntryControl(officer, _sprite, _prototype);
            OfficersContainer.AddChild(entry);
        }
    }

    private void UpdateSquads(List<PatrolSquadDef> squads)
    {
        ZonesContainer.RemoveAllChildren();

        foreach (var squad in squads)
        {
            var entry = new SquadEntryControl(squad, _sprite, _prototype, OnRenameSquad);
            entry.OnBulkAssignSquad += squadId => OnBulkAssignSquad?.Invoke(squadId);
            entry.OnClearSquad += squadId => OnClearSquad?.Invoke(squadId);
            entry.OnDeleteSquad += squadId => OnDeleteSquad?.Invoke(squadId);
            ZonesContainer.AddChild(entry);
        }
    }
}

public sealed class CreateSquadDialog : DefaultWindow
{
    private readonly SpriteSystem _sprite;
    private readonly IPrototypeManager _prototype;
    private readonly LineEdit _nameInput;
    private string _selectedIconId = string.Empty;

    public Action<string, string>? OnCreate;

    public CreateSquadDialog(SpriteSystem sprite, IPrototypeManager prototype)
    {
        _sprite = sprite;
        _prototype = prototype;

        Title = Loc.GetString("patrol-tablet-create-squad");
        MinSize = new Vector2(360, 340);
        SetSize = new Vector2(360, 340);

        var rootBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10),
            SeparationOverride = 8,
        };

        rootBox.AddChild(new Label
        {
            Text = Loc.GetString("patrol-tablet-squad-name-label"),
            FontColorOverride = Color.FromHex("#00A2E8"),
        });

        _nameInput = new LineEdit
        {
            PlaceHolder = Loc.GetString("patrol-tablet-squad-name-placeholder"),
            MinSize = new Vector2(0, 24),
        };
        rootBox.AddChild(_nameInput);

        rootBox.AddChild(new Label
        {
            Text = Loc.GetString("patrol-tablet-icon-label"),
            FontColorOverride = Color.FromHex("#00A2E8"),
        });

        var iconGrid = new GridContainer
        {
            Columns = 6,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        var iconGroup = new ButtonGroup();
        var icons = _prototype.EnumeratePrototypes<SecurityIconPrototype>()
            .Where(i => !i.Abstract && i.ID.StartsWith("DeadSpaceSquadIcon"))
            .ToList();

        foreach (var icon in icons)
        {
            var iconName = icon.ID["DeadSpaceSquadIcon".Length..];
            var btn = new Button
            {
                MinSize = new Vector2(42, 28),
                MaxSize = new Vector2(42, 28),
                Group = iconGroup,
                ToolTip = iconName,
            };

            var texRect = new TextureRect
            {
                Texture = _sprite.Frame0(icon.Icon),
                TextureScale = new Vector2(2.5f, 2.5f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            };
            btn.AddChild(texRect);

            var capturedId = icon.ID;
            btn.OnPressed += _ =>
            {
                _selectedIconId = capturedId;
            };

            iconGrid.AddChild(btn);
        }

        var scroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        scroll.AddChild(iconGrid);
        rootBox.AddChild(scroll);

        var buttonRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
        };

        var createButton = new Button
        {
            Text = Loc.GetString("patrol-tablet-create-button"),
            MinWidth = 80,
            MinHeight = 24,
        };
        createButton.OnPressed += _ =>
        {
            var name = _nameInput.Text.Trim();
            if (string.IsNullOrWhiteSpace(name) || string.IsNullOrEmpty(_selectedIconId))
                return;
            if (name.Length > 30)
                name = name[..30];
            OnCreate?.Invoke(name, _selectedIconId);
        };
        buttonRow.AddChild(createButton);

        var cancelButton = new Button
        {
            Text = Loc.GetString("patrol-tablet-cancel-button"),
            MinWidth = 80,
            MinHeight = 24,
        };
        cancelButton.OnPressed += _ => Close();
        buttonRow.AddChild(cancelButton);

        rootBox.AddChild(buttonRow);
        Contents.AddChild(rootBox);

        OpenCentered();
    }
}

public sealed partial class OfficerEntryControl : PanelContainer
{
    private PatrolOfficerInfo _officer;
    private readonly SpriteSystem _sprite;
    private readonly IPrototypeManager _prototype;

    public OfficerEntryControl(
        PatrolOfficerInfo officer,
        SpriteSystem sprite,
        IPrototypeManager prototype)
    {
        _officer = officer;
        _sprite = sprite;
        _prototype = prototype;

        MinHeight = 36;
        Margin = new Thickness(0, 0, 0, 2);

        BuildUI();
    }

    private void BuildUI()
    {
        var styleBox = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1a1a2e"),
            BorderColor = Color.FromHex("#3F48CC"),
            BorderThickness = new Thickness(1),
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 6,
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
        };
        PanelOverride = styleBox;

        var mainBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
            VerticalAlignment = VAlignment.Center,
        };

        if (!string.IsNullOrEmpty(_officer.SquadIcon) &&
            _prototype.TryIndex<SecurityIconPrototype>(_officer.SquadIcon, out var iconProto))
        {
            var iconRect = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
                Texture = _sprite.Frame0(iconProto.Icon),
                SetSize = new Vector2(16, 16),
            };
            mainBox.AddChild(iconRect);
        }

        var infoBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };

        var nameLabel = new Label
        {
            Text = _officer.Name,
            FontColorOverride = Color.FromHex("#ffffff"),
            StyleClasses = { StyleClass.LabelKeyText },
            HorizontalExpand = true,
        };
        infoBox.AddChild(nameLabel);

        var jobLabel = new Label
        {
            Text = _officer.JobTitle,
            FontColorOverride = Color.FromHex("#aaaaaa"),
            HorizontalExpand = true,
        };
        infoBox.AddChild(jobLabel);

        mainBox.AddChild(infoBox);

        AddChild(mainBox);
    }
}

public sealed partial class SquadEntryControl : PanelContainer
{
    private PatrolSquadDef _squad;
    private readonly SpriteSystem _sprite;
    private readonly IPrototypeManager _prototype;
    private readonly Action<string, string>? _onRenameSquad;
    private bool _expanded;

    public Action<string>? OnBulkAssignSquad;
    public Action<string>? OnClearSquad;
    public Action<string>? OnDeleteSquad;

    public SquadEntryControl(
        PatrolSquadDef squad,
        SpriteSystem sprite,
        IPrototypeManager prototype,
        Action<string, string>? onRenameSquad = null)
    {
        _squad = squad;
        _sprite = sprite;
        _prototype = prototype;
        _onRenameSquad = onRenameSquad;
        MinHeight = 44;
        Margin = new Thickness(0, 0, 0, 2);

        BuildUI();
    }

    private void ToggleExpand()
    {
        _expanded = !_expanded;
        RemoveAllChildren();
        BuildUI();
    }

    private void BuildUI()
    {
        var styleBox = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1a1a2e"),
            BorderColor = Color.FromHex("#3F48CC"),
            BorderThickness = new Thickness(1),
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
        };
        PanelOverride = styleBox;

        var outerBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 4,
        };

        var topRow = new ContainerButton
        {
            HorizontalExpand = true,
        };
        var topRowHBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        var expandArrow = new Label
        {
            Text = _expanded ? "▼" : "▶",
            FontColorOverride = Color.FromHex("#00A2E8"),
            VerticalAlignment = VAlignment.Center,
            MinSize = new Vector2(16, 0),
        };
        topRowHBox.AddChild(expandArrow);

        if (_prototype.TryIndex<SecurityIconPrototype>(_squad.IconId, out var iconProto))
        {
            var iconRect = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
                Texture = _sprite.Frame0(iconProto.Icon),
                SetSize = new Vector2(16, 16),
            };
            topRowHBox.AddChild(iconRect);
        }

        var nameLabel = new Label
        {
            Text = _squad.Name,
            FontColorOverride = Color.FromHex("#ffffff"),
            HorizontalExpand = true,
        };
        topRowHBox.AddChild(nameLabel);

        topRow.AddChild(topRowHBox);
        topRow.OnPressed += _ => ToggleExpand();
        outerBox.AddChild(topRow);

        var bottomRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        var assignAllButton = new Button
        {
            Text = Loc.GetString("patrol-tablet-assign-all"),
            MinWidth = 70,
            MinHeight = 22,
            ToolTip = Loc.GetString("patrol-tablet-assign-all-tooltip"),
        };
        var capturedSquadId = _squad.SquadId;
        assignAllButton.OnPressed += _ =>
        {
            OnBulkAssignSquad?.Invoke(capturedSquadId);
        };
        bottomRow.AddChild(assignAllButton);

        var renameButton = new Button
        {
            Text = "✎",
            MinSize = new Vector2(24, 22),
            ToolTip = Loc.GetString("patrol-tablet-rename-squad"),
        };
        renameButton.OnPressed += _ =>
        {
            var dialog = new DialogWindow(
                Loc.GetString("patrol-tablet-rename-squad"),
                new List<QuickDialogEntry>
                {
                    new("squadName", QuickDialogEntryType.ShortText,
                        Loc.GetString("patrol-tablet-rename-squad"),
                        string.Empty)
                });
            dialog.OnConfirmed += results =>
            {
                if (results.TryGetValue("squadName", out var newName) && !string.IsNullOrWhiteSpace(newName))
                {
                    newName = newName.Trim();
                    if (newName.Length > 30)
                        newName = newName[..30];
                    _onRenameSquad?.Invoke(capturedSquadId, newName);
                }
            };
        };
        bottomRow.AddChild(renameButton);

        var clearSquadButton = new Button
        {
            Text = "✕",
            MinSize = new Vector2(24, 22),
            ToolTip = Loc.GetString("patrol-tablet-clear-squad"),
        };
        clearSquadButton.OnPressed += _ =>
        {
            OnClearSquad?.Invoke(capturedSquadId);
        };
        bottomRow.AddChild(clearSquadButton);

        var deleteSquadButton = new Button
        {
            Text = "🗑",
            MinSize = new Vector2(24, 22),
            ToolTip = Loc.GetString("patrol-tablet-delete-squad"),
        };
        deleteSquadButton.OnPressed += _ =>
        {
            OnDeleteSquad?.Invoke(capturedSquadId);
        };
        bottomRow.AddChild(deleteSquadButton);

        var countLabel = new Label
        {
            Text = _squad.AssignedCount > 0
                ? Loc.GetString("patrol-tablet-squad-count", ("count", _squad.AssignedCount))
                : Loc.GetString("patrol-tablet-squad-empty"),
            FontColorOverride = _squad.AssignedCount > 0 ? Color.FromHex("#00ff88") : Color.FromHex("#666666"),
            VerticalAlignment = VAlignment.Center,
        };
        bottomRow.AddChild(countLabel);

        outerBox.AddChild(bottomRow);

        if (_expanded && _squad.Members.Count > 0)
        {
            var memberBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 2,
                Margin = new Thickness(24, 2, 0, 0),
            };

            foreach (var memberName in _squad.Members)
            {
                var memberLabel = new Label
                {
                    Text = "• " + memberName,
                    FontColorOverride = Color.FromHex("#cccccc"),
                };
                memberBox.AddChild(memberLabel);
            }

            outerBox.AddChild(memberBox);
        }
        else if (_expanded)
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("patrol-tablet-squad-empty"),
                FontColorOverride = Color.FromHex("#666666"),
                Margin = new Thickness(24, 2, 0, 0),
            };
            outerBox.AddChild(emptyLabel);
        }

        AddChild(outerBox);
    }
}
