// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Globalization;
using System.Numerics;
using Content.Shared.DeadSpace.BSAConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.DeadSpace.BSAConsole;

[GenerateTypedNameReferences]
public sealed partial class BSAConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action<MapCoordinates>? OnFirePressed;
    public event Action<BSAConsoleViewMode>? OnSwitchViewPressed;
    public event Action<NetEntity>? OnSelectGridPressed;
    public event Action? OnEjectDiskPressed;

    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    private BSAConsoleUiState? _lastState;
    private Popup _dropdownPopup = default!;
    private BoxContainer _dropdownContainer = default!;

    private MapCoordinates? _crosshairCoordinates;
    private NetEntity? _trackedGridUid;
    private Vector2 _trackedGridOffset;
    private bool _updatingCoordinateFields;
    private bool _coordinateError;
    private bool _showingGridMap;

    private static readonly Color BgPanel = Color.FromHex("#1A1A24");
    private static readonly Color Border = Color.FromHex("#2a2a35");
    private static readonly Color Green = Color.FromHex("#54D98C");
    private static readonly Color GreenDark = Color.FromHex("#2A4A2A");
    private static readonly Color GreenBg = Color.FromHex("#1A2A1A");
    private static readonly Color Red = Color.FromHex("#D95454");
    private static readonly Color Gold = Color.FromHex("#D9A83C");
    private static readonly Color Muted = Color.FromHex("#3C3C50");
    private static readonly Color Orange = Color.FromHex("#D98C3C");
    private static readonly Color OrangeBg = Color.FromHex("#2A1A0A");
    private static readonly Color OrangeBorder = Color.FromHex("#4A2A0A");

    public BSAConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ViewModeButton.OnPressed += _ => ToggleDropdown();
        FireButton.OnPressed += _ => FireAtEnteredCoordinates();
        EjectDiskButton.OnPressed += _ => OnEjectDiskPressed?.Invoke();
        CoordinateX.OnTextChanged += _ => OnCoordinateTextChanged();
        CoordinateY.OnTextChanged += _ => OnCoordinateTextChanged();
        RadarScreen.OnMapClick += OnMapClicked;
        GridMapScreen.OnMapClick += OnMapClicked;

        BuildDropdownPopup();
    }

    public void UpdateState(BSAConsoleUiState state)
    {
        var resetTarget = _lastState == null ||
            _lastState.CurrentViewMode != state.CurrentViewMode ||
            _lastState.SelectedGridUid != state.SelectedGridUid ||
            _lastState.RadarState?.MapId != state.RadarState?.MapId;

        _lastState = state;

        if (resetTarget)
        {
            ClearTarget();
            RadarScreen.Offset = Vector2.Zero;
            RadarScreen.TargetOffset = Vector2.Zero;
        }

        UpdateConnection(state);
        UpdateCooldown(state);
        UpdateViewLabel(state);
        UpdateRadar(state);
        UpdateDisk(state);
        UpdateTrackedCrosshair(state);
        UpdateCrosshair();
    }

    private void UpdateConnection(BSAConsoleUiState state)
    {
        if (state.IsConnected)
        {
            BSAConnectionLabel.Text = state.BSAName ?? "БСА";
            BSAConnectionLabel.FontColorOverride = Green;
            FireButton.Disabled = state.IsOnCooldown || state.HasPendingShot || state.RadarState == null;

            if (!_coordinateError)
                ErrorLabel.Visible = false;
        }
        else
        {
            BSAConnectionLabel.Text = "НЕТ СВЯЗИ";
            BSAConnectionLabel.FontColorOverride = Red;
            ErrorLabel.Text = "ПОДКЛЮЧИТЕ СЕТЬ";
            ErrorLabel.Visible = true;
            FireButton.Disabled = true;
        }
    }

    private void UpdateCooldown(BSAConsoleUiState state)
    {
        if (state.HasPendingShot)
        {
            var remaining = (int) Math.Ceiling(state.PendingShotTimeLeft);
            CooldownLabel.Text = $"ВЗРЫВ ЧЕРЕЗ: {remaining}с";
            CooldownLabel.FontColorOverride = Color.FromHex("#FF4444");
            CooldownBar.Value = state.PendingShotDelay - state.PendingShotTimeLeft;
            CooldownBar.MaxValue = state.PendingShotDelay;
            StatusPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#3A1A1A"),
                BorderColor = Color.FromHex("#5A2A2A"),
                BorderThickness = new Thickness(1),
            };
            return;
        }

        if (state.IsOnCooldown)
        {
            var remaining = (int) Math.Ceiling(state.CooldownRemaining);
            CooldownLabel.Text = $"ОХЛАЖДЕНИЕ: {remaining}с";
            CooldownLabel.FontColorOverride = Orange;
            CooldownBar.Value = state.CooldownDuration - state.CooldownRemaining;
            CooldownBar.MaxValue = state.CooldownDuration;
            StatusPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = OrangeBg,
                BorderColor = OrangeBorder,
                BorderThickness = new Thickness(1),
            };
            return;
        }

        CooldownLabel.Text = "ГОТОВА";
        CooldownLabel.FontColorOverride = Green;
        CooldownBar.Value = 0;
        StatusPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = GreenBg,
            BorderColor = GreenDark,
            BorderThickness = new Thickness(1),
        };
    }

    private void UpdateViewLabel(BSAConsoleUiState state)
    {
        var modeText = state.CurrentViewMode switch
        {
            BSAConsoleViewMode.MassScannerLocal => "СКАНЕР МАСС",
            BSAConsoleViewMode.MassScannerDisk => "СКАНЕР МАСС ЛОКАЦИИ",
            BSAConsoleViewMode.Grid => state.SelectedGridName ?? "ГРИД",
            _ => "НЕИЗВЕСТНО",
        };

        ViewModeButton.Text = $"РЕЖИМ: {modeText}";
        SelectedGridLabel.Text = state.SelectedGridName ?? string.Empty;
        SelectedGridLabel.Visible = state.CurrentViewMode == BSAConsoleViewMode.Grid &&
            state.SelectedGridUid != null;
    }

    private void UpdateRadar(BSAConsoleUiState state)
    {
        RadarScreen.UpdateState(state.RadarState);

        EntityUid? gridUid = null;
        var showGridMap = state.CurrentViewMode == BSAConsoleViewMode.Grid &&
            state.SelectedGridHasNavMap &&
            state.SelectedGridUid is { } gridNetUid &&
            _entityManager.TryGetEntity(gridNetUid, out gridUid);

        RadarScreen.Visible = !showGridMap;
        GridMapScreen.Visible = showGridMap;

        if (showGridMap && gridUid is { } selectedGrid &&
            (!_showingGridMap || GridMapScreen.MapUid != selectedGrid))
        {
            GridMapScreen.MapUid = selectedGrid;
            GridMapScreen.Offset = Vector2.Zero;
            GridMapScreen.TargetOffset = Vector2.Zero;
            GridMapScreen.ForceNavMapUpdate();
        }

        _showingGridMap = showGridMap;
    }

    private void UpdateDisk(BSAConsoleUiState state)
    {
        if (!state.HasDisk)
        {
            DiskStatusLabel.Text = "ДИСК НЕ ВСТАВЛЕН";
            DiskStatusLabel.FontColorOverride = Gold;
            EjectDiskButton.Visible = false;
            return;
        }

        DiskStatusLabel.Text = state.TargetMapName ?? "НЕКОРРЕКТНЫЙ ДИСК";
        DiskStatusLabel.FontColorOverride = state.TargetMapName == null ? Red : Green;
        EjectDiskButton.Visible = true;
    }

    private void UpdateTrackedCrosshair(BSAConsoleUiState state)
    {
        if (_trackedGridUid == null || state.RadarState == null)
            return;

        var grid = state.RadarState.Grids.Find(entry => entry.GridUid == _trackedGridUid.Value);
        if (grid == null)
        {
            ClearTarget();
            return;
        }

        var worldPosition = grid.Center + new Angle(grid.Rotation).RotateVec(_trackedGridOffset);
        SetTargetCoordinates(new MapCoordinates(worldPosition, new MapId(state.RadarState.MapId)));
    }

    private void UpdateCrosshair()
    {
        Crosshair.SetWorldPosition(
            _crosshairCoordinates,
            _showingGridMap ? GridMapScreen.WorldToScreen : RadarScreen.WorldToScreen);
    }

    private void OnMapClicked(MapCoordinates mapPosition)
    {
        _trackedGridUid = null;

        if (_lastState?.CurrentViewMode == BSAConsoleViewMode.Grid &&
            _lastState.SelectedGridUid is { } selectedGrid &&
            _lastState.RadarState != null)
        {
            var grid = _lastState.RadarState.Grids.Find(entry => entry.GridUid == selectedGrid);
            if (grid != null)
            {
                _trackedGridUid = selectedGrid;
                _trackedGridOffset = new Angle(-grid.Rotation).RotateVec(mapPosition.Position - grid.Center);
            }
        }

        SetTargetCoordinates(mapPosition);
    }

    private void OnCoordinateTextChanged()
    {
        if (_updatingCoordinateFields)
            return;

        _trackedGridUid = null;
        _coordinateError = false;

        if (TryGetEnteredCoordinates(out var coordinates))
            _crosshairCoordinates = coordinates;
        else
            _crosshairCoordinates = null;

        UpdateCrosshair();
    }

    private void FireAtEnteredCoordinates()
    {
        if (!TryGetEnteredCoordinates(out var coordinates))
        {
            _coordinateError = true;
            ErrorLabel.Text = "НЕКОРРЕКТНЫЕ КООРДИНАТЫ";
            ErrorLabel.Visible = true;
            return;
        }

        _coordinateError = false;
        ErrorLabel.Visible = false;
        OnFirePressed?.Invoke(coordinates);
    }

    private bool TryGetEnteredCoordinates(out MapCoordinates coordinates)
    {
        coordinates = default;

        if (_lastState?.RadarState == null ||
            !float.TryParse(CoordinateX.Text, NumberStyles.Float, Inv, out var x) ||
            !float.TryParse(CoordinateY.Text, NumberStyles.Float, Inv, out var y) ||
            !float.IsFinite(x) ||
            !float.IsFinite(y))
        {
            return false;
        }

        coordinates = new MapCoordinates(x, y, new MapId(_lastState.RadarState.MapId));
        return true;
    }

    private void SetTargetCoordinates(MapCoordinates coordinates)
    {
        _crosshairCoordinates = coordinates;
        _updatingCoordinateFields = true;
        CoordinateX.Text = coordinates.X.ToString("F1", Inv);
        CoordinateY.Text = coordinates.Y.ToString("F1", Inv);
        _updatingCoordinateFields = false;
        UpdateCrosshair();
    }

    private void ClearTarget()
    {
        _crosshairCoordinates = null;
        _trackedGridUid = null;
        _trackedGridOffset = Vector2.Zero;
        _coordinateError = false;
        _updatingCoordinateFields = true;
        CoordinateX.Text = string.Empty;
        CoordinateY.Text = string.Empty;
        _updatingCoordinateFields = false;
        UpdateCrosshair();
    }

    private void BuildDropdownPopup()
    {
        _dropdownContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 1,
        };

        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = BgPanel,
                BorderColor = Border,
                BorderThickness = new Thickness(1),
            },
            Children =
            {
                new ScrollContainer
                {
                    MaxHeight = 200,
                    HScrollEnabled = false,
                    Children = { _dropdownContainer },
                },
            },
        };

        _dropdownPopup = new Popup { Children = { panel } };
        _dropdownPopup.OnPopupHide += OnPopupClosed;
    }

    private void ToggleDropdown()
    {
        if (_dropdownPopup.Visible)
            _dropdownPopup.Close();
        else
            OpenDropdown();
    }

    private void OpenDropdown()
    {
        if (_lastState == null)
            return;

        _dropdownContainer.RemoveAllChildren();

        AddScannerButton(
            "СКАНЕР МАСС",
            BSAConsoleViewMode.MassScannerLocal,
            _lastState.CurrentViewMode == BSAConsoleViewMode.MassScannerLocal);

        if (_lastState.TargetMapName != null)
        {
            AddScannerButton(
                "СКАНЕР МАСС ЛОКАЦИИ",
                BSAConsoleViewMode.MassScannerDisk,
                _lastState.CurrentViewMode == BSAConsoleViewMode.MassScannerDisk);
        }

        if (_lastState.AllGrids.Count > 0)
            AddSeparator();

        foreach (var grid in _lastState.AllGrids)
        {
            var button = new Button
            {
                Text = grid.IsDisk ? $"{grid.Name} *" : grid.Name,
                TextAlign = Label.AlignMode.Left,
                MinHeight = 26,
                Disabled = _lastState.CurrentViewMode == BSAConsoleViewMode.Grid &&
                    _lastState.SelectedGridUid == grid.GridUid,
            };

            var gridUid = grid.GridUid;
            button.OnPressed += _ =>
            {
                _dropdownPopup.Close();
                OnSelectGridPressed?.Invoke(gridUid);
            };
            _dropdownContainer.AddChild(button);
        }

        if (_lastState.AllGrids.Count == 0)
        {
            _dropdownContainer.AddChild(new Label
            {
                Text = "  Гриды не найдены",
                FontColorOverride = Muted,
            });
        }

        var globalPosition = ViewModeButton.GlobalPosition;
        globalPosition.Y += ViewModeButton.Size.Y + 1;
        _dropdownContainer.Measure(Window?.Size ?? Vector2Helpers.Infinity);
        var (minimumX, minimumY) = _dropdownContainer.DesiredSize;
        var box = UIBox2.FromDimensions(
            globalPosition,
            new Vector2(Math.Max(minimumX, ViewModeButton.Width), minimumY));

        UserInterfaceManager.ModalRoot.AddChild(_dropdownPopup);
        _dropdownPopup.Open(box);
    }

    private void AddScannerButton(string text, BSAConsoleViewMode mode, bool disabled)
    {
        var button = new Button
        {
            Text = text,
            TextAlign = Label.AlignMode.Left,
            MinHeight = 26,
            Disabled = disabled,
        };

        button.OnPressed += _ =>
        {
            _dropdownPopup.Close();
            OnSwitchViewPressed?.Invoke(mode);
        };

        _dropdownContainer.AddChild(button);
    }

    private void AddSeparator()
    {
        var separator = new PanelContainer
        {
            MinHeight = 1,
            PanelOverride = new StyleBoxFlat { BackgroundColor = Border },
        };
        _dropdownContainer.AddChild(separator);
    }

    private void OnPopupClosed()
    {
        UserInterfaceManager.ModalRoot.RemoveChild(_dropdownPopup);
    }
}
