using Content.Client.Administration.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultWindow
    {
        [Dependency] private readonly IClientAdminManager _adminManager = default!;

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Tabs.SetTabTitle(0, Loc.GetString("ui-options-tab-misc"));
            Tabs.SetTabTitle(1, Loc.GetString("ui-options-tab-graphics"));
            Tabs.SetTabTitle(2, Loc.GetString("ui-options-tab-controls"));
            Tabs.SetTabTitle(3, Loc.GetString("ui-options-tab-audio"));
            Tabs.SetTabTitle(4, Loc.GetString("ui-options-tab-accessibility"));
            // DS14-Start
            Tabs.SetTabTitle(5, Loc.GetString("ui-options-tab-ping"));
            Tabs.SetTabTitle(6, Loc.GetString("ui-options-tab-admin"));
            // DS14-end

            UpdateTabs();
        }

        public void UpdateTabs()
        {
            var isAdmin = _adminManager.IsAdmin(true);
            Tabs.SetTabVisible(6, isAdmin);

            GraphicsTab.Control.ReloadValues();
            MiscTab.Control.ReloadValues();
            AccessibilityTab.Control.ReloadValues();
            AudioTab.Control.ReloadValues();
            PingTab.Control.ReloadValues();//DS14
            AdminOptionsTab.Control.ReloadValues();
        }
    }
}
