// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.PipeShuttle;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.PipeShuttle.UI;

[GenerateTypedNameReferences]
public sealed partial class PipeShuttleWindow : FancyWindow
{
    private int _selectedIndex = -1;
    private bool _travelling;
    private bool _manualMode;

    public event Action<string>? OnDestSelected;

    public PipeShuttleWindow()
    {
        RobustXamlLoader.Load(this);

        CallButton.OnPressed += _ =>
        {
            if (_selectedIndex >= 0 && StopList.Count > _selectedIndex)
            {
                var item = StopList[_selectedIndex];
                if (item.Metadata is string destId && !_manualMode)
                    OnDestSelected?.Invoke(destId);
            }
        };

        StopList.OnItemSelected += args =>
        {
            _selectedIndex = args.ItemIndex;
            CallButton.Disabled = _travelling || _manualMode;
        };
    }

    public void UpdateState(PipeShuttleUiState state)
    {
        StopList.Clear();
        _selectedIndex = -1;
        _travelling = state.Travelling;
        _manualMode = state.ManualMode;
        CallButton.Disabled = true;

        foreach (var dest in state.Destinations)
        {
            var label = Loc.GetString(dest.Name);
            if (state.CurrentDestId == dest.Id)
                label += Loc.GetString("pipe-shuttle-list-current-suffix");
            else if (state.Travelling && state.TargetDestId == dest.Id)
                label += Loc.GetString("pipe-shuttle-list-target-suffix");

            StopList.AddItem(label, metadata: dest.Id);
        }

        if (state.ManualMode)
        {
            StatusLabel.Text = Loc.GetString("pipe-shuttle-status-manual");
            CallButton.Disabled = true;
        }
        else if (state.Travelling)
        {
            var targetName = state.TargetDestId;
            foreach (var d in state.Destinations)
            {
                if (d.Id == state.TargetDestId)
                {
                    targetName = Loc.GetString(d.Name);
                    break;
                }
            }
            StatusLabel.Text = Loc.GetString("pipe-shuttle-status-travelling", ("destination", targetName ?? string.Empty));
            CallButton.Disabled = true;
        }
        else if (state.CurrentDestId != null)
        {
            var currentName = state.CurrentDestId;
            foreach (var d in state.Destinations)
            {
                if (d.Id == state.CurrentDestId)
                {
                    currentName = Loc.GetString(d.Name);
                    break;
                }
            }
            StatusLabel.Text = Loc.GetString("pipe-shuttle-status-docked", ("destination", currentName));
        }
        else
        {
            StatusLabel.Text = Loc.GetString("pipe-shuttle-status-idle");
        }
    }
}
