- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brigmedic # DS14
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  #start-backmen: currency
  minBankBalance: 400 # DS14-value
  maxBankBalance: 500 # DS14-value
  wageDepartment: Security
  wage: 300 # DS14-value
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: BasicAndShuttleControl
      # DS14-End

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetAltSecurityOfficer #ds14
  storage:
    back:
    - Flash
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
    - ERTloadoutSecuritySecondary # DS14

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
