using Content.Client.UserInterface.Controls;
using Content.Shared.Communications;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Communications.UI;

/// <summary>
/// The main menu for the communications console interface.
/// Contains a series of widgets for the alert, announce/broadcast and shuttle functions.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CommunicationsConsoleMenu : FancyWindow
{
    public event Action? OnShuttleCalled;
    public event Action? OnShuttleRecalled;
    public event Action<string>? OnAlertLevelChanged;
    public event Action<string>? OnRadioAnnounce;
    public event Action<string>? OnScreenBroadcast;
    public event Action? OnEmagChannel; // DS14

    public CommunicationsConsoleMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MessagingControls.OnRadioAnnounce += message => OnRadioAnnounce?.Invoke(message);
        MessagingControls.OnScreenBroadcast += message => OnScreenBroadcast?.Invoke(message);

        AlertLevelControls.OnAlertLevelChanged += newLevel => OnAlertLevelChanged?.Invoke(newLevel);

        ShuttleControls.OnShuttleCalled += () => OnShuttleCalled?.Invoke();
        ShuttleControls.OnShuttleRecalled += () => OnShuttleRecalled?.Invoke();

        EmagChannelButton.OnPressed += _ => OnEmagChannel?.Invoke(); // DS14
    }

    /// <summary>
    /// Use the specified prototype ID as an example display in the
    /// UI subsection where users type broadcast messages.
    /// </summary>
    public void SetBroadcastDisplayEntity(EntProtoId broadcastEntityId)
    {
        MessagingControls.SetBroadcastDisplayEntity(broadcastEntityId);
    }

    /// <summary>
    /// Configure UI to be consistent with the input state.
    /// </summary>
    // DS14-start - alert level details are supplied by the server on this branch.
    public void UpdateState(CommunicationsConsoleInterfaceState commsState,
        string currentAlertLevel,
        Color currentAlertColor,
        List<string>? selectableAlertLevels,
        bool canChangeAlertLevel)
    {
        MessagingControls.CanRadioAnnounce = commsState.CanAnnounce;
        MessagingControls.CanScreenBroadcast = commsState.CanBroadcast;

        var alertLevelSelectable = selectableAlertLevels != null && canChangeAlertLevel;
        AlertLevelControls.UpdateAlertLevels(selectableAlertLevels,
            currentAlertLevel,
            currentAlertColor,
            alertLevelSelectable);

        ShuttleControls.UpdateState(commsState.CanCall, commsState.CountdownStarted, commsState.ExpectedCountdownEnd);
    }
    // DS14-end
}
