- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 6h
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 6h
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10h
    - !type:OverallPlaytimeRequirement
      time: 40h
    - !type:AgeRequirement
      requiredAge: 24
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 500 # DS14-value
  maxBankBalance: 700 # DS14-value
  wageDepartment: Command
  wage: 400 # DS14-value
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # DS14-Start
      - type: Skill
        group: HeadEngineer
      # DS14-End

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
    eyes: ClothingEyesGlassesMesonCE #DS14
    ears: ClothingHeadsetCE
    belt: ClothingBeltUtilityEngineering
    socks: ClothingUnderwearSocksChiefEngineer
    gloves: ClothingHandsGlovesColorYellow # DS14
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: ChiefEngineerChameleonOutfit
  job: ChiefEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretEngineering
    mask: ClothingMaskBreath
    neck: ClothingNeckCloakCe
    outerClothing: ClothingOuterWinterCE
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMagAdv
