using System.Numerics;
using Content.Client.Message;
using Content.Shared.CartridgeLoader;
using Content.Shared.DeadSpace.Thief;
using Content.Shared.DeadSpace.Thief.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.DeadSpace.Thief.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ThiefProgramUiFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<ThiefProgramUiAction, int, string, int>? OnActionPressed;

    private bool _requestsTabActive = true;

    public ThiefProgramUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RequestsTabButton.OnPressed += _ => SwitchTab(true);
        UplinkTabButton.OnPressed += _ => SwitchTab(false);
        ExchangeButton.OnPressed += OnExchangePressed;
        UplinkSearchInput.OnTextChanged += _ => RebuildUplink();
    }

    public void UpdateState(ThiefProgramUiState state)
    {
        BalanceLabel.SetMarkup(Loc.GetString("thief-program-balance", ("balance", state.Balance)));
        var percent = state.GoalTarget > 0
            ? Math.Min(100d, (double) state.EarnedTotal / state.GoalTarget * 100d)
            : 0d;
        GoalLabel.SetMarkup(Loc.GetString("thief-program-goal",
            ("earned", state.EarnedTotal), ("target", state.GoalTarget), ("percent", $"{percent:F1}")));
        HintLabel.Text = Loc.GetString("thief-program-carry-hint");

        RebuildRequests(state);
        RebuildUplink();
    }

    private void SwitchTab(bool requests)
    {
        _requestsTabActive = requests;
        RequestsTabButton.Pressed = requests;
        UplinkTabButton.Pressed = !requests;
        RequestsView.Visible = requests;
        UplinkView.Visible = !requests;
    }

    #region Requests tab

    private void RebuildRequests(ThiefProgramUiState state)
    {
        RequestsContainer.RemoveAllChildren();

        if (!state.BeaconLinked)
        {
            AddHint(RequestsContainer, Loc.GetString("thief-program-hint-no-beacon"));
        }

        if (state.Active.Count > 0)
        {
            AddSectionHeader(RequestsContainer, Loc.GetString("thief-program-section-active"));
            foreach (var request in state.Active)
            {
                RequestsContainer.AddChild(BuildActiveRequestRow(request));
            }
        }

        if (state.Offers.Count > 0)
        {
            AddSectionHeader(RequestsContainer, Loc.GetString("thief-program-section-offers"));
            foreach (var request in state.Offers)
            {
                RequestsContainer.AddChild(BuildOfferRow(request));
            }
        }
    }

    private Control BuildOfferRow(ThiefRequestInfo request)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(4),
            StyleClasses = { "DS14MenuListRow" },
        };

        var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };

        var label = new RichTextLabel { HorizontalExpand = true };
        label.SetMarkup(Loc.GetString("thief-program-request-offer",
            ("name", request.GroupName),
            ("count", request.Count),
            ("price", request.TotalPrice),
            ("minutes", request.TimeLimitMinutes)));

        var acceptButton = new Button
        {
            Text = Loc.GetString("thief-program-accept"),
            StyleClasses = { "DS14MenuAction" },
            // Fixed minimal width so long request names cannot squeeze the button.
            MinWidth = 90,
            VerticalAlignment = VAlignment.Center,
        };
        acceptButton.OnPressed += _ =>
            OnActionPressed?.Invoke(ThiefProgramUiAction.Accept, request.Id, string.Empty, 0);

        row.AddChild(label);
        row.AddChild(acceptButton);
        panel.AddChild(row);
        return panel;
    }

    private Control BuildActiveRequestRow(ThiefRequestInfo request)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(4),
            StyleClasses = { "DS14MenuListRow" },
        };

        var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };

        var expired = request.TimeLeftSeconds == ThiefRequestInfo.Expired;

        var label = new RichTextLabel { HorizontalExpand = true };
        label.SetMarkup(expired
            ? Loc.GetString("thief-program-request-expired",
                ("name", request.GroupName),
                ("count", request.Count),
                ("price", request.TotalPrice))
            : Loc.GetString("thief-program-request-active",
                ("name", request.GroupName),
                ("count", request.Count),
                ("price", request.TotalPrice),
                ("minutes", request.TimeLeftSeconds / 60),
                ("seconds", request.TimeLeftSeconds % 60)));

        row.AddChild(label);

        var sellButton = new Button
        {
            Text = Loc.GetString("thief-program-sell"),
            StyleClasses = { "DS14MenuAction" },
            MinWidth = 90,
            VerticalAlignment = VAlignment.Center,
        };
        sellButton.OnPressed += _ =>
            OnActionPressed?.Invoke(ThiefProgramUiAction.Sell, request.Id, string.Empty, 0);
        row.AddChild(sellButton);

        var declineButton = new TextureButton();
        declineButton.AddStyleClass("windowCloseButton");
        declineButton.OnPressed += _ =>
            OnActionPressed?.Invoke(ThiefProgramUiAction.Decline, request.Id, string.Empty, 0);
        row.AddChild(declineButton);

        panel.AddChild(row);
        return panel;
    }

    #endregion

    #region Uplink tab

    private void RebuildUplink()
    {
        UplinkContainer.RemoveAllChildren();

        var query = UplinkSearchInput.Text.Trim();
        var categories = new Dictionary<string, List<ThiefListingPrototype>>();
        foreach (var listing in _prototypeManager.EnumeratePrototypes<ThiefListingPrototype>())
        {
            var name = Loc.GetString(listing.Name);
            if (!string.IsNullOrEmpty(query) &&
                !name.Contains(query, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var category = Loc.GetString(listing.Category);
            if (!categories.TryGetValue(category, out var list))
            {
                list = new List<ThiefListingPrototype>();
                categories[category] = list;
            }

            list.Add(listing);
        }

        foreach (var (category, listings) in categories)
        {
            AddSectionHeader(UplinkContainer, category);
            foreach (var listing in listings)
            {
                UplinkContainer.AddChild(BuildListingRow(listing));
            }
        }
    }

    private Control BuildListingRow(ThiefListingPrototype listing)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(4),
            StyleClasses = { "DS14MenuListRow" },
        };

        var box = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };

        var topRow = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };

        var name = new Label
        {
            Text = Loc.GetString(listing.Name),
            HorizontalExpand = true,
            ClipText = true,
            StyleClasses = { "LabelKeyText" },
        };

        var cost = new Label { Text = Loc.GetString("thief-program-uplink-cost", ("cost", listing.Cost)) };
        topRow.AddChild(name);
        topRow.AddChild(cost);

        var description = new RichTextLabel { MinSize = new Vector2(0, 24) };
        if (listing.Description is { } desc)
            description.SetMarkup(Loc.GetString(desc));

        var buyButton = new Button
        {
            Text = Loc.GetString("thief-program-buy"),
            StyleClasses = { "DS14MenuAction" },
            MinWidth = 90,
            VerticalAlignment = VAlignment.Center,
        };
        buyButton.OnPressed += _ =>
            OnActionPressed?.Invoke(ThiefProgramUiAction.Buy, 0, listing.ID, 0);

        topRow.AddChild(buyButton);

        box.AddChild(topRow);
        box.AddChild(description);
        panel.AddChild(box);
        return panel;
    }

    #endregion

    private void OnExchangePressed(BaseButton.ButtonEventArgs args)
    {
        var amount = 0;
        int.TryParse(ExchangeInput.Text.Trim(), out amount);
        ExchangeInput.Clear();
        OnActionPressed?.Invoke(ThiefProgramUiAction.Exchange, 0, string.Empty, amount);
    }

    private static void AddSectionHeader(BoxContainer container, string text)
    {
        var label = new Label
        {
            Text = text,
            StyleClasses = { "DS14MenuProfileSection" },
            Margin = new Thickness(4, 6, 4, 2),
        };
        container.AddChild(label);
    }

    private static void AddHint(BoxContainer container, string text)
    {
        var label = new Label
        {
            Text = text,
            Margin = new Thickness(4, 2, 4, 2),
            ModulateSelfOverride = Color.FromHex("#c9a227"),
        };
        container.AddChild(label);
    }
}
