using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Communications.UI.Widgets;

/// <summary>
/// A set of controls to change the alert level for a station.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AlertLevelControls : BoxContainer
{
    // DS14-start - the current engine still uses the pre-source-generator IoC pattern.
    [Dependency] private readonly ILocalizationManager _loc = default!;
    // DS14-end

    private bool _alertLevelSelectable;
    private string? _currentAlertLevel;

    public event Action<string>? OnAlertLevelChanged;

    public AlertLevelControls()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AlertLevelSelector.OnItemSelected += args =>
        {
            AlertLevelSelector.Select(args.Id);
            EnableDisableConfirmLevelChangeButton();
        };

        ConfirmAlertLevelButton.OnPressed += _ =>
        {
            var metadata = AlertLevelSelector.GetItemMetadata(AlertLevelSelector.SelectedId);
            if (metadata is string selected)
                OnAlertLevelChanged?.Invoke(selected);
        };

        AlertLevelSelector.Disabled = !_alertLevelSelectable;
    }

    /// <summary>
    /// Updates the UI components to display the current alert level and the
    /// selectable alert levels.
    /// </summary>
    // DS14-start - use server-provided alert IDs and color until alert levels move to Shared.
    public void UpdateAlertLevels(List<string>? selectableAlertLevels,
        string currentAlertLevel,
        Color currentAlertColor,
        bool alertLevelSelectable)
    {
        _alertLevelSelectable = alertLevelSelectable;
        _currentAlertLevel = currentAlertLevel;
        CurrentAlertLevelLabel.Text = GetLocalizedAlertName(currentAlertLevel);
        CurrentAlertLevelLabel.ModulateSelfOverride = currentAlertColor;

        AlertLevelSelector.Disabled = selectableAlertLevels == null || !_alertLevelSelectable;

        // If user had changed the selection, but hadn't pressed the confirm
        // button at the point we received an update message, remember it so it
        // can be re-selected if it is still available.
        string? previousSelection = null;
        if (AlertLevelSelector.ItemCount > 1)
        {
            var metadata = AlertLevelSelector.GetItemMetadata(AlertLevelSelector.SelectedId);
            if (metadata is string selected)
                previousSelection = selected;
        }

        AlertLevelSelector.Clear();
        AlertLevelSelector.AddItem(Loc.GetString("comms-console-change-alert-level-button"));
        AlertLevelSelector.Select(0);

        if (selectableAlertLevels != null)
        {
            foreach (var alert in selectableAlertLevels)
            {
                AlertLevelSelector.AddItem(GetLocalizedAlertName(alert));
                AlertLevelSelector.SetItemMetadata(AlertLevelSelector.ItemCount - 1, alert);

                if (alert == previousSelection)
                    AlertLevelSelector.Select(AlertLevelSelector.ItemCount - 1);
            }
        }

        if (_loc.TryGetString($"comms-console-level-{currentAlertLevel}-flavour-label", out var flavour))
            CurrentAlertLevelFlavorLabel.Text = flavour;
        else
            CurrentAlertLevelFlavorLabel.Text = string.Empty;

        EnableDisableConfirmLevelChangeButton();
    }
    // DS14-end

    /// <summary>
    /// Configure the confirm button to be consistent with the server state and user interactions.
    /// </summary>
    private void EnableDisableConfirmLevelChangeButton()
    {
        var selectedId = AlertLevelSelector.SelectedId;
        ConfirmAlertLevelButton.Disabled = !_alertLevelSelectable || selectedId == 0;
        if (selectedId == 0)
            return;

        var metadata = AlertLevelSelector.GetItemMetadata(selectedId);
        if (metadata is string selected)
            ConfirmAlertLevelButton.Disabled |= selected == _currentAlertLevel;
    }

    private string GetLocalizedAlertName(string alertLevel)
    {
        return _loc.TryGetString($"alert-level-{alertLevel}", out var localized)
            ? localized
            : alertLevel;
    }
}
