using System.Linq;
using System.Numerics;
using Content.Client.DeadSpace.Stylesheets;
using Content.Client.Stylesheets;
using Content.Shared.CartridgeLoader.Cartridges;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Timing;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class MessengerCartridgeUiFragment : BoxContainer
{
    private int _currentChatPartnerId;
    private Dictionary<int, MessengerUserEntry> _users = new();
    private SpriteSystem _spriteSystem = default!;
    private IPrototypeManager _prototypeManager = default!;
    private TimeSpan _lastTypingTime;
    private string _searchText = string.Empty; // DS14
    private bool _isBlocking; // DS14
    private bool _incomingMessagesDisabled; // DS14

    public MessengerCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        var entSysMan = IoCManager.Resolve<IEntitySystemManager>();
        _spriteSystem = entSysMan.GetEntitySystem<SpriteSystem>();
        _prototypeManager = IoCManager.Resolve<IPrototypeManager>();

        SendButton.OnPressed += OnSendPressed;
        BackButton.OnPressed += OnBackPressed;
        BlockButton.OnPressed += OnBlockPressed; // DS14
        ChatToggleButton.OnPressed += OnChatTogglePressed; // DS14
        MessageInput.OnTextEntered += OnMessageInputSubmit;
        MessageInput.OnTextChanged += OnMessageInputTextChanged;
        SearchBar.OnTextChanged += OnSearchTextChanged; // DS14
    }

    // DS14-start
    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text.Trim();
        RebuildUserList();
    }
    // DS14-end

    private void OnMessageInputTextChanged(LineEdit.LineEditEventArgs args)
    {
        var time = IoCManager.Resolve<IGameTiming>().CurTime;
        if (time - _lastTypingTime > TimeSpan.FromSeconds(2))
        {
            _lastTypingTime = time;
            OnTyping?.Invoke();
        }
    }

    public void UpdateState(MessengerStatus status, Dictionary<int, MessengerUserEntry> users, List<MessengerMessageEntry>? messages = null, bool isBlocked = false, bool isBlocking = false, bool incomingMessagesDisabled = false) //DS14
    {
        _users = users ?? new Dictionary<int, MessengerUserEntry>();
        _incomingMessagesDisabled = incomingMessagesDisabled; // DS14

        ConnectedContainer.Visible = status == MessengerStatus.Connected;
        ConnectionLostContainer.Visible = status == MessengerStatus.ConnectionLost;
        ChatToggleButton.Text = _incomingMessagesDisabled
            ? Loc.GetString("messenger-enable-chat")
            : Loc.GetString("messenger-disable-chat"); // DS14

        RebuildUserList(); // DS14

        // DS14-start
        if (messages != null && _currentChatPartnerId != 0)
        {
            UpdateMessages(messages);
        }
        UpdateBlockState(isBlocked, isBlocking);
        // DS14-end
    }

    // DS14-Start
    public void UpdateBlockState(bool isBlocked, bool isBlocking)
    {
        var inputHidden = isBlocked || isBlocking;
        BlockedLabel.Visible = inputHidden;
        InputContainer.Visible = !inputHidden;
        BlockedLabel.Text = Loc.GetString("messenger-blocked");

        _isBlocking = isBlocking;

        if (_currentChatPartnerId != 0)
        {
            BlockButton.Visible = true;
            BlockButton.Text = isBlocking ? Loc.GetString("messenger-unblock") : Loc.GetString("messenger-block");
        }
        else
        {
            BlockButton.Visible = false;
        }
    }

    private void OnBlockPressed(BaseButton.ButtonEventArgs args)
    {
        if (_currentChatPartnerId == 0)
            return;

        OnBlockUser?.Invoke(_currentChatPartnerId, !_isBlocking);
    }

    private void OnChatTogglePressed(BaseButton.ButtonEventArgs args)
    {
        OnSetIncomingDisabled?.Invoke(!_incomingMessagesDisabled);
    }
    // DS14-End

    // DS14-start
    private void RebuildUserList()
    {
        UserListContainer.RemoveAllChildren();

        var filteredUsers = _users.Values
            .Where(MatchesSearch)
            // DS14-start: dialogs with new messages are pinned to the very top of the list
            .OrderByDescending(u => u.UnreadCount > 0)
            .ThenByDescending(u => u.UnreadCount)
            // DS14-end
            .ThenBy(u => GetNameSortKey(u.Name), StringComparer.CurrentCultureIgnoreCase)
            .ThenBy(u => u.JobTitle, StringComparer.CurrentCultureIgnoreCase)
            .ToList();

        var showingChat = MessageBoxContainer.Visible;
        NoUsers.Visible = filteredUsers.Count == 0 && !showingChat;
        UserListScrollContainer.Visible = filteredUsers.Count > 0 && !showingChat;

        if (filteredUsers.Count == 0)
        {
            NoUsers.Text = string.IsNullOrWhiteSpace(_searchText)
                ? Loc.GetString("messenger-no-users")
                : Loc.GetString("messenger-search-empty");
            return;
        }

        var currentGroup = string.Empty;
        foreach (var user in filteredUsers)
        {
            // DS14-start: all unread dialogs are gathered under a dedicated "new message" header on top
            var group = user.UnreadCount > 0
                ? Loc.GetString("messenger-unread-header")
                : GetNameGroup(user.Name);
            // DS14-end
            if (group != currentGroup)
            {
                currentGroup = group;
                UserListContainer.AddChild(MakeGroupHeader(group));
            }

            var button = new Button
            {
                HorizontalExpand = true,
            };

            // DS14-start: noticeable highlight for dialogs with new messages
            if (user.UnreadCount > 0)
                button.StyleClasses.Add(DeadSpaceStyleClass.ListItemUnread);
            // DS14-end
            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };

            if (_prototypeManager.TryIndex<JobIconPrototype>(user.JobIconId, out var jobIconProto))
            {
                var icon = new TextureRect
                {
                    Texture = _spriteSystem.Frame0(jobIconProto.Icon),
                    TextureScale = new Vector2(2, 2),
                    VerticalAlignment = VAlignment.Center,
                    Margin = new Thickness(0, 0, 4, 0)
                };
                row.AddChild(icon);
            }

            var labels = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            labels.AddChild(new Label
            {
                Text = user.Name,
                ClipText = true,
                HorizontalExpand = true,
            });
            labels.AddChild(new Label
            {
                Text = user.JobTitle,
                ClipText = true,
                HorizontalExpand = true,
                StyleClasses = { DeadSpaceStyleClass.Subtitle },
            });
            row.AddChild(labels);

            if (user.UnreadCount > 0)
                row.AddChild(MakeUnreadBadge(user.UnreadCount));

            button.AddChild(row);
            var userId = user.Id;
            button.OnPressed += _ => OnUserSelected(userId);
            UserListContainer.AddChild(button);
        }
    }

    private bool MatchesSearch(MessengerUserEntry user)
    {
        if (string.IsNullOrWhiteSpace(_searchText))
            return true;

        return user.Name.Contains(_searchText, StringComparison.CurrentCultureIgnoreCase)
            || user.JobTitle.Contains(_searchText, StringComparison.CurrentCultureIgnoreCase);
    }

    private static string GetNameSortKey(string name)
    {
        var trimmed = name.Trim();
        return trimmed.Length == 0 ? "#" : trimmed;
    }

    private static string GetNameGroup(string name)
    {
        var trimmed = name.Trim();
        if (trimmed.Length == 0)
            return "#";

        return char.ToUpperInvariant(trimmed[0]).ToString();
    }

    private static Control MakeGroupHeader(string group)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(4, 6, 4, 2),
            StyleClasses = { DeadSpaceStyleClass.ListHeader },
        };

        panel.AddChild(new Label
        {
            Text = group,
            StyleClasses = { DeadSpaceStyleClass.ListHeader },
        });

        return panel;
    }

    private static Control MakeUnreadBadge(int unreadCount)
    {
        var panel = new PanelContainer
        {
            MinWidth = 24,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(6, 0, 0, 0),
            StyleClasses = { StyleClass.Positive }, // DS14
        };

        panel.AddChild(new Label
        {
            Text = unreadCount > 9 ? "!" : unreadCount.ToString(),
            Align = Label.AlignMode.Center,
            StyleClasses = { StyleClass.Positive }, // DS14
        });

        return panel;
    }
    // DS14-end

    private void OnUserSelected(int userId)
    {
        _currentChatPartnerId = userId;

        if (_users.TryGetValue(userId, out var user))
        {
            ChatPartnerLabel.Text = user.Name;
        }

        // DS14-start
        SearchHeader.Visible = false;
        NoUsers.Visible = false;
        UserListScrollContainer.Visible = false;
        MessageBoxContainer.Visible = true;
        BlockButton.Visible = true;
        BlockButton.Text = Loc.GetString("messenger-block");
        // DS14-end
        OnRequestMessages?.Invoke(userId);
    }

    private void OnBackPressed(BaseButton.ButtonEventArgs args)
    {
        // DS14-start
        MessageBoxContainer.Visible = false;
        SearchHeader.Visible = true;
        BlockButton.Visible = false;
        RebuildUserList();
        // DS14-end
        _currentChatPartnerId = 0;
        OnRequestMessages?.Invoke(0);
    }

    private void OnSendPressed(BaseButton.ButtonEventArgs args)
    {
        SendMessage();
    }

    private void OnMessageInputSubmit(LineEdit.LineEditEventArgs args)
    {
        SendMessage();
    }

    private void SendMessage()
    {
        var text = MessageInput.Text.Trim();
        if (string.IsNullOrEmpty(text) || _currentChatPartnerId == 0)
            return;

        OnSendMessage?.Invoke(_currentChatPartnerId, text);
        MessageInput.Clear();
    }

    private void UpdateMessages(List<MessengerMessageEntry> messages)
    {
        MessageContainer.RemoveAllChildren();

        var filteredMessages = messages.Where(m =>
            m.SenderId == _currentChatPartnerId || m.ReceiverId == _currentChatPartnerId);

        foreach (var msg in filteredMessages.OrderBy(m => m.Timestamp))
        {
            var timeStr = msg.Timestamp.ToString(@"hh\:mm\:ss");
            var color = msg.IsIncoming ? "aqua" : "white";
            // DS14-start
            var safeName = FormattedMessage.EscapeText(msg.SenderName);
            var safeContent = FormattedMessage.EscapeText(msg.Content);
            var safeTime = FormattedMessage.EscapeText(timeStr);
            var richLabel = new RichTextLabel { HorizontalExpand = true };
            richLabel.SetMessage(FormattedMessage.FromMarkup(
                $"[color={color}]{safeTime} {safeName}: {safeContent}[/color]"));
            // DS14-end
            MessageContainer.AddChild(richLabel);
        }
    }

    public event Action<int, string>? OnSendMessage;
    public event Action<int>? OnRequestMessages;
    public event Action? OnTyping;
    public event Action<int, bool>? OnBlockUser; // DS14
    public event Action<bool>? OnSetIncomingDisabled; // DS14
}
