using Content.Client.DeadSpace.Stylesheets;
using Content.Client.Message;
using Content.Client.RichText;
using Content.Client.UserInterface.RichText;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NewsReaderUiFragment : BoxContainer
{
    public event Action? OnNextButtonPressed;
    public event Action? OnPrevButtonPressed;
    public event Action? OnNotificationSwithPressed;
    public event Action? OnLikeButtonPressed;
    public event Action? OnDislikeButtonPressed;
    public event Action<string>? OnSendCommentPressed;

    public NewsReaderUiFragment()
    {
        RobustXamlLoader.Load(this);

        Next.OnPressed += _ => OnNextButtonPressed?.Invoke();
        Prev.OnPressed += _ => OnPrevButtonPressed?.Invoke();
        NotificationSwitch.OnPressed += _ => OnNotificationSwithPressed?.Invoke();

        // DS14-start
        LikeButton.OnPressed += _ => OnLikeButtonPressed?.Invoke();
        DislikeButton.OnPressed += _ => OnDislikeButtonPressed?.Invoke();
        SendCommentButton.OnPressed += _ => SubmitComment();
        CommentInput.OnTextEntered += _ => SubmitComment();
        // DS14-end
    }

    // DS14-start
    private void SubmitComment()
    {
        var comment = CommentInput.Text.Trim();
        if (string.IsNullOrWhiteSpace(comment))
            return;

        OnSendCommentPressed?.Invoke(comment);
        CommentInput.Text = string.Empty;
    }
    // DS14-end

    public void UpdateState(NewsArticle article, int targetNum, int totalNum, bool notificationOn)
    {
        PageNum.Visible = true;
        PageText.Visible = true;
        ShareTime.Visible = true;
        Author.Visible = true;

        PageName.Text = article.Title;
        PageText.SetMessage(FormattedMessage.FromMarkupPermissive(article.Content), UserFormattableTags.BaseAllowedTags);

        PageNum.Text = $"{targetNum}/{totalNum}";

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");

        var shareTime = article.ShareTime.ToString(@"hh\:mm\:ss");
        ShareTime.SetMarkup(Loc.GetString("news-read-ui-time-prefix-text") + " " + shareTime);

        var author = Loc.GetString("news-read-ui-author-prefix") + " " + (article.Author ?? Loc.GetString("news-read-ui-no-author"));
        Author.SetMessage(FormattedMessage.FromMarkupPermissive(author), UserFormattableTags.BaseAllowedTags);

        Prev.Disabled = targetNum <= 1;
        Next.Disabled = targetNum >= totalNum;

        InteractionPanel.Visible = true; // DS14

        LikeButton.Disabled = false;
        DislikeButton.Disabled = false;
        CommentInput.Editable = true;
        SendCommentButton.Disabled = false;

        LikeCount.Text = article.Likes.ToString();
        DislikeCount.Text = article.Dislikes.ToString();

        UpdateComments(article.Comments);
    }

    // DS14-start
    private void UpdateComments(IReadOnlyList<NewsComment>? comments)
    {
        CommentsContainer.DisposeAllChildren();

        if (comments == null || comments.Count == 0)
        {
            var noCommentsLabel = new RichTextLabel
            {
                Margin = new Thickness(4, 4, 4, 4),
                HorizontalAlignment = HAlignment.Center,
                StyleClasses = { DeadSpaceStyleClass.Subtitle },
            };
            noCommentsLabel.SetMarkup(Loc.GetString("news-read-ui-no-comments"));
            CommentsContainer.AddChild(noCommentsLabel);
            return;
        }

        foreach (var comment in comments)
        {
            var commentBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(6, 4, 6, 8),
            };

            var metaLabel = new RichTextLabel
            {
                Margin = new Thickness(0, 0, 0, 2)
            };

            var author = string.IsNullOrWhiteSpace(comment.Author)
                ? Loc.GetString("news-read-ui-anonymous")
                : comment.Author;
            var time = comment.CommentTime.ToString(@"hh\:mm\:ss");
            metaLabel.SetMarkup(Loc.GetString(
                "news-read-ui-comment-author",
                ("author", FormattedMessage.EscapeText(author)),
                ("time", time)));

            var contentLabel = new RichTextLabel();
            contentLabel.SetMessage(comment.Content);

            commentBox.AddChild(metaLabel);
            commentBox.AddChild(contentLabel);
            CommentsContainer.AddChild(commentBox);
        }
    }
    // DS14-end

    public void UpdateEmptyState(bool notificationOn)
    {
        PageNum.Visible = false;
        PageText.Visible = false;
        ShareTime.Visible = false;
        Author.Visible = false;

        PageName.Text = Loc.GetString("news-read-ui-not-found-text");

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");

        Prev.Disabled = true;
        Next.Disabled = true;

        InteractionPanel.Visible = false; // DS14

        LikeButton.Disabled = true;
        DislikeButton.Disabled = true;
        CommentInput.Editable = false;
        CommentInput.Text = string.Empty;
        SendCommentButton.Disabled = true;

        CommentsContainer.DisposeAllChildren();
        LikeCount.Text = "0";
        DislikeCount.Text = "0";
    }
}
