using System.Linq;
using Content.Client.DeadSpace.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.CriminalRecords.Systems;
using Content.Shared.Security;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class WantedListUiFragment : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private readonly SpriteSystem _spriteSystem;

    private string? _selectedTargetName;
    private List<WantedRecord> _wantedRecords = new();

    public WantedListUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        SearchBar.OnTextChanged += OnSearchBarTextChanged;
    }

    // DS14-start
    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        var found = !string.IsNullOrWhiteSpace(args.Text)
            ? _wantedRecords.FindAll(r =>
                r.TargetInfo.Name.Contains(args.Text, StringComparison.CurrentCultureIgnoreCase) ||
                (r.TargetInfo.JobTitle ?? string.Empty).Contains(args.Text, StringComparison.CurrentCultureIgnoreCase) ||
                GetStatusName(r.Status).Contains(args.Text, StringComparison.CurrentCultureIgnoreCase) ||
                r.Status.ToString().Contains(args.Text, StringComparison.OrdinalIgnoreCase))
            : _wantedRecords;

        UpdateState(found, false);
    }
    // DS14-end

    public void UpdateState(List<WantedRecord> records, bool refresh = true)
    {
        // DS14-start
        if (refresh)
            _wantedRecords = records;
        // DS14-end

        if (records.Count == 0)
        {
            NoRecords.Visible = true;
            RecordsList.Visible = false;
            RecordUnselected.Visible = false;
            PersonContainer.Visible = false;

            // DS14-start
            if (refresh)
                _selectedTargetName = null;
            // DS14-end

            RecordsList.PopulateList(new List<ListData>());

            return;
        }

        NoRecords.Visible = false;
        RecordsList.Visible = true;
        RecordUnselected.Visible = true;
        PersonContainer.Visible = false;

        // DS14-start
        var dataList = records
            .OrderBy(r => r.TargetInfo.Name, StringComparer.CurrentCultureIgnoreCase)
            .Select(r => new StatusListData(r))
            .ToList();
        // DS14-end

        RecordsList.GenerateItem = GenerateItem;
        RecordsList.ItemPressed = OnItemSelected;
        RecordsList.PopulateList(dataList);
    }

    private void OnItemSelected(BaseButton.ButtonEventArgs args, ListData data)
    {
        if (data is not StatusListData(var record))
            return;

        FormattedMessage GetLoc(string fluentId, params (string,object)[] args)
        {
            var msg = new FormattedMessage();
            var fluent = Loc.GetString(fluentId, args);
            msg.AddMarkupPermissive(fluent);
            return msg;
        }

        // Set personal info
        PersonName.Text = record.TargetInfo.Name;
        TargetAge.SetMessage(GetLoc(
            "wanted-list-age-label",
            ("age", record.TargetInfo.Age)
        ));
        TargetJob.SetMessage(GetLoc(
            "wanted-list-job-label",
            ("job", record.TargetInfo.JobTitle.ToLower())
        ));
        TargetSpecies.SetMessage(GetLoc(
            "wanted-list-species-label",
            ("species", record.TargetInfo.Species.ToLower())
        ));
        TargetGender.SetMessage(GetLoc(
            "wanted-list-gender-label",
            ("gender", record.TargetInfo.Gender)
        ));

        // Set reason
        WantedReason.SetMessage(GetLoc(
            "wanted-list-reason-label",
            ("reason", record.Reason ?? Loc.GetString("wanted-list-unknown-reason-label"))
        ));

        // Set status
        PersonState.SetMessage(GetLoc(
            "wanted-list-status-label",
            ("status", record.Status.ToString().ToLower())
        ));

        // Set initiator
        InitiatorName.SetMessage(GetLoc(
            "wanted-list-initiator-label",
            ("initiator", record.Initiator ?? Loc.GetString("wanted-list-unknown-initiator-label"))
        ));

        // DS14-start
        HistoryTable.RemoveAllChildren();
        HistoryTable.Visible = record.History.Count > 0;
        HistoryPanel.Visible = record.History.Count > 0;

        HistoryTable.AddChild(new Label()
        {
            Text = Loc.GetString("wanted-list-history-table-time-col"),
            StyleClasses = { "DS14MenuListHeader" },
            HorizontalAlignment = HAlignment.Center,
        });
        HistoryTable.AddChild(new Label()
        {
            Text = Loc.GetString("wanted-list-history-table-reason-col"),
            StyleClasses = { "DS14MenuListHeader" },
            HorizontalAlignment = HAlignment.Center,
            HorizontalExpand = true,
        });

        HistoryTable.AddChild(new Label()
        {
            Text = Loc.GetString("wanted-list-history-table-initiator-col"),
            StyleClasses = { "DS14MenuListHeader" },
            HorizontalAlignment = HAlignment.Center,
        });

        if (record.History.Count > 0)
        {
            HistoryTable.Visible = true;

            foreach (var history in record.History.OrderByDescending(h => h.AddTime))
            {
                HistoryTable.AddChild(new Label()
                {
                    Text = $"{history.AddTime.Hours:00}:{history.AddTime.Minutes:00}:{history.AddTime.Seconds:00}",
                    StyleClasses = { "DS14MenuProfileLabel" },
                    VerticalAlignment = VAlignment.Top,
                });

                HistoryTable.AddChild(new RichTextLabel()
                {
                    Text = $"[color=white]{FormattedMessage.EscapeText(history.Crime)}[/color]",
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Top,
                    Margin = new(10f, 0f),
                });

                HistoryTable.AddChild(new RichTextLabel()
                {
                    Text = $"[color=white]{FormattedMessage.EscapeText(history.InitiatorName ?? Loc.GetString("wanted-list-unknown-initiator-label"))}[/color]",
                    VerticalAlignment = VAlignment.Top,
                });
            }
        }
        // DS14-end

        RecordUnselected.Visible = false;
        PersonContainer.Visible = true;

        // Save selected item
        _selectedTargetName = record.TargetInfo.Name;
    }

    private void GenerateItem(ListData data, ListContainerButton button)
    {
        if (data is not StatusListData(var record))
            return;

        // DS14-start
        var box = new BoxContainer()
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };
        var rect = new TextureRect()
        {
            TextureScale = new(2.2f),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Margin = new(0f, 0f, 6f, 0f),
        };

        if (TryGetStatusIcon(record.Status, out var icon))
            rect.Texture = icon;

        var labels = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        labels.AddChild(new Label
        {
            Text = record.TargetInfo.Name,
            ClipText = true,
            HorizontalExpand = true,
            StyleClasses = { "DS14MenuProfileLabel" },
        });
        labels.AddChild(new Label
        {
            Text = $"{record.TargetInfo.JobTitle} - {GetStatusName(record.Status)}",
            ClipText = true,
            HorizontalExpand = true,
            StyleClasses = { "DS14MenuSubtitle" },
        });

        box.AddChild(rect);
        box.AddChild(labels);
        button.StyleBoxOverride = null;
        button.AddChild(box);
        button.AddStyleClass(button.Index % 2 == 0
            ? DeadSpaceMenuSheetlet.ListRow
            : DeadSpaceMenuSheetlet.ListRowAlt);
        // DS14-end

        if (record.TargetInfo.Name.Equals(_selectedTargetName))
        {
            button.Pressed = true;
            // For some reason the event is not called when `Pressed` changed, call it manually.
            OnItemSelected(
                new(button, new(new(), BoundKeyState.Down, new(), false, new(), new())),
                data);
        }
    }

    // DS14-start
    private bool TryGetStatusIcon(SecurityStatus status, out Texture? texture)
    {
        texture = null;

        if (status is SecurityStatus.None)
            return false;

        var proto = "SecurityIcon" + status switch
            {
                SecurityStatus.Detained => "Incarcerated",
                _ => status.ToString(),
            };

        if (!_prototypeManager.TryIndex<SecurityIconPrototype>(proto, out var prototype))
            return false;

        texture = _spriteSystem.Frame0(prototype.Icon);
        return true;
    }

    private static string GetStatusName(SecurityStatus status)
    {
        return Loc.GetString($"criminal-records-status-{status.ToString().ToLowerInvariant()}");
    }
    // DS14-end
}

internal record StatusListData(WantedRecord Record) : ListData;
