using System.Linq;
using Content.DeadSpace.Interfaces.Client;
using Content.Client.DeadSpace.HairGradient; // DS14
using Content.Client.Stylesheets;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class SingleMarkingPicker : BoxContainer
{
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private IClientSponsorsManager? _sponsorsManager; // DS14-sponsors

    private readonly SpriteSystem _sprite;

    /// <summary>
    ///     What happens if a marking is selected.
    ///     It will send the 'slot' (marking index)
    ///     and the selected marking's ID.
    /// </summary>
    public Action<(int slot, string id)>? OnMarkingSelect;
    /// <summary>
    ///     What happens if a slot is removed.
    ///     This will send the 'slot' (marking index).
    /// </summary>
    public Action<int>? OnSlotRemove;

    /// <summary>
    ///     What happens when a slot is added.
    /// </summary>
    public Action? OnSlotAdd;

    /// <summary>
    ///     What happens if a marking's color is changed.
    ///     Sends a 'slot' number, and the marking in question.
    /// </summary>
    public Action<(int slot, Marking marking)>? OnColorChanged;

    // DS14-start
    /// <summary>
    ///     градиент или цвет меняется.
    /// </summary>
    public Action<(bool enabled, Color color)>? OnGradientChanged;
    // DS14-end

    // current selected slot
    private int _slot = -1;
    private int Slot
    {
        get
        {
            if (_markings == null || _markings.Count == 0)
            {
                _slot = -1;
            }
            else if (_slot == -1)
            {
                _slot = 0;
            }

            return _slot;
        }
        set
        {
            if (_markings == null || _markings.Count == 0)
            {
                _slot = -1;
                return;
            }

            _slot = value;
            _ignoreItemSelected = true;

            foreach (var item in MarkingList)
            {
                item.Selected = (string) item.Metadata! == _markings[_slot].MarkingId;
            }

            _ignoreItemSelected = false;
            PopulateColors();
        }
    }

    // amount of slots to show
    private int _totalPoints;

    private bool _ignoreItemSelected;

    private MarkingCategories _category;
    public MarkingCategories Category
    {
        get => _category;
        set
        {
            _category = value;
            CategoryName.Text = Loc.GetString($"markings-category-{_category}");

            if (!string.IsNullOrEmpty(_species))
            {
                PopulateList(Search.Text);
            }
        }
    }
    private IReadOnlyDictionary<string, MarkingPrototype>? _markingPrototypeCache;

    private string? _species;
    private List<Marking>? _markings;
    private bool _useDs14MenuStyle; // DS14
    private readonly HairGradientControl? _hairGradient; // DS14

    private int PointsLeft
    {
        get
        {
            if (_markings == null)
            {
                return 0;
            }

            if (_totalPoints < 0)
            {
                return -1;
            }

            return _totalPoints - _markings.Count;
        }
    }

    private int PointsUsed => _markings?.Count ?? 0;

    public SingleMarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        IoCManager.Instance!.TryResolveType(out _sponsorsManager); // DS14-sponsors

        _sprite = _entityManager.System<SpriteSystem>();
        MarkingList.OnItemSelected += SelectMarking;
        AddButton.OnPressed += _ =>
        {
            OnSlotAdd!();
        };

        SlotSelector.OnItemSelected += args =>
        {
            Slot = args.Button.SelectedId;
        };

        RemoveButton.OnPressed += _ =>
        {
            OnSlotRemove!(_slot);
        };

        Search.OnTextChanged += args =>
        {
            PopulateList(args.Text);
        };

        // DS14-start
        _hairGradient = new HairGradientControl();
        GradientContainer.AddChild(_hairGradient);

        _hairGradient.OnGradientChanged += (enabled, color) =>
        {
            OnGradientChanged?.Invoke((enabled, color));
        };
        // DS14-end
    }

    // DS14-start
    public void UseDs14MenuStyle()
    {
        _useDs14MenuStyle = true;
        ApplyDs14MenuStyle(this);
    }

    private void ApplyDs14MenuStyle(Control control) // DS14
    {
        switch (control)
        {
            case Button button:
                button.RemoveStyleClass(StyleClass.ButtonOpenLeft);
                button.RemoveStyleClass(StyleClass.ButtonOpenRight);
                button.RemoveStyleClass(StyleClass.ButtonOpenBoth);
                button.AddStyleClass("DS14MenuProfileControl");
                break;
            case OptionButton option:
                option.RemoveStyleClass(StyleClass.ButtonOpenLeft);
                option.RemoveStyleClass(StyleClass.ButtonOpenRight);
                option.RemoveStyleClass(StyleClass.ButtonOpenBoth);
                option.AddStyleClass("DS14MenuProfileControl");
                if (!option.OptionStyleClasses.Contains("DS14MenuProfileControl"))
                    option.OptionStyleClasses.Add("DS14MenuProfileControl");
                break;
            case Label label:
                label.AddStyleClass("DS14MenuProfileLabel");
                break;
            // DS14-Start
            case CheckBox checkBox:
                checkBox.AddStyleClass("DS14MenuProfileLabel");
                break;
            // DS14-End
        }

        foreach (var child in control.Children)
        {
            ApplyDs14MenuStyle(child);
        }
    }

    public void ApplyDs14MenuStyleToColorSelector(ColorSelectorSliders selector)
    {
        foreach (var child in selector.Children)
        {
            switch (child)
            {
                case Slider slider:
                    slider.AddStyleClass("DS14MenuProfileControl");
                    break;
                case LineEdit lineEdit:
                    lineEdit.AddStyleClass("DS14MenuProfileControl");
                    break;
            }

            if (child is BoxContainer box)
            {
                foreach (var inner in box.Children)
                {
                    if (inner is Label label)
                        label.AddStyleClass("DS14MenuProfileLabel");
                }
            }
        }
    }
    // DS14-end

    public void UpdateData(List<Marking> markings, string species, int totalPoints)
    {
        _markings = markings;
        _species = species;
        _totalPoints = totalPoints;

        _markingPrototypeCache = _markingManager.MarkingsByCategoryAndSpecies(Category, _species);

        Visible = _markingPrototypeCache.Count != 0;
        if (_markingPrototypeCache.Count == 0)
        {
            return;
        }

        PopulateList(Search.Text);
        PopulateColors();
        PopulateSlotSelector();
    }

    public void PopulateList(string filter)
    {
        if (string.IsNullOrEmpty(_species))
        {
            throw new ArgumentException("Tried to populate marking list without a set species!");
        }

        _markingPrototypeCache ??= _markingManager.MarkingsByCategoryAndSpecies(Category, _species);

        MarkingSelectorContainer.Visible = _markings != null && _markings.Count != 0;
        if (_markings == null || _markings.Count == 0)
        {
            return;
        }

        MarkingList.Clear();

        var sortedMarkings = _markingPrototypeCache.Where(m =>
            !IsTechnicalHairGradient(m.Value) && // DS14
            (m.Key.ToLower().Contains(filter.ToLower()) ||
                GetMarkingName(m.Value).ToLower().Contains(filter.ToLower()))
        ).OrderBy(p => Loc.GetString($"marking-{p.Key}"));

        foreach (var (id, marking) in sortedMarkings)
        {
            var item = MarkingList.AddItem(Loc.GetString($"marking-{id}"), _sprite.Frame0(marking.Sprites[0]));
            item.Metadata = marking.ID;
            // DS14-sponsors-start
            if (_sponsorsManager != null && marking.SponsorOnly)
            {
                item.Disabled = true;
                if (_sponsorsManager.TryGetInfo(out var sponsor))
                {
                    item.Disabled = !sponsor.AllowedMarkings.Contains(marking.ID);
                }
            }
            // DS14-sponsors-end

            if (IsSelectedMarking(id)) // DS14
            {
                _ignoreItemSelected = true;
                item.Selected = true;
                _ignoreItemSelected = false;
            }
        }
    }

    private void PopulateColors()
    {
        if (_markings == null
            || _markings.Count == 0
            || !_markingManager.TryGetMarking(_markings[Slot], out var proto))
        {
            return;
        }

        var marking = _markings[Slot];

        ColorSelectorContainer.RemoveAllChildren();

        if (marking.MarkingColors.Count != proto.Sprites.Count)
        {
            marking = new Marking(marking.MarkingId, proto.Sprites.Count);
        }

        for (var i = 0; i < marking.MarkingColors.Count; i++)
        {
            // DS14-start
            if ((_hairGradient?.GradientEnabled ?? false) && i > 0 && _category == MarkingCategories.Hair)
                continue;
            // DS14-end

            var selector = new ColorSelectorSliders
            {
                HorizontalExpand = true
            };
            selector.Color = marking.MarkingColors[i];
            selector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV

            var colorIndex = i;
            selector.OnColorChanged += color =>
            {
                marking.SetColor(colorIndex, color);
                OnColorChanged!((_slot, marking));
            };

            ColorSelectorContainer.AddChild(selector);
            // DS14-start
            if (_useDs14MenuStyle)
                ApplyDs14MenuStyle(selector);
            // DS14-end
        }

        // DS14-start
        UpdateGradientVisibility();
        // DS14-end
    }

    // DS14-start
    public void SetGradientData(bool enabled, Color color)
    {
        if (_hairGradient != null)
        {
            _hairGradient.SetData(enabled, color);
            GradientContainer.Visible = _category == MarkingCategories.Hair;
        }
    }

    private void UpdateGradientVisibility()
    {
        if (_hairGradient == null)
            return;

        GradientContainer.Visible = _category == MarkingCategories.Hair
            && _markings != null
            && _markings.Count > 0
            && Slot >= 0;
    }
    // DS14-end

    private void SelectMarking(ItemList.ItemListSelectedEventArgs args)
    {
        if (_ignoreItemSelected)
        {
            return;
        }

        var id = (string) MarkingList[args.ItemIndex].Metadata!;
        if (!_markingManager.Markings.TryGetValue(id, out var proto))
        {
            throw new ArgumentException("Attempted to select non-existent marking.");
        }

        var oldMarking = _markings![Slot];
        _markings[Slot] = proto.AsMarking();

        for (var i = 0; i < _markings[Slot].MarkingColors.Count && i < oldMarking.MarkingColors.Count; i++)
        {
            _markings[Slot].SetColor(i, oldMarking.MarkingColors[i]);
        }

        PopulateColors();

        OnMarkingSelect!((_slot, id));
    }

    // Slot logic

    private void PopulateSlotSelector()
    {
        SlotSelector.Visible = Slot >= 0;
        Search.Visible = Slot >= 0;
        AddButton.HorizontalExpand = Slot < 0;
        RemoveButton.HorizontalExpand = Slot < 0;
        AddButton.Disabled = PointsLeft == 0 && _totalPoints > -1 ;
        RemoveButton.Disabled = PointsUsed == 0;
        SlotSelector.Clear();

        if (Slot < 0)
        {
            return;
        }

        for (var i = 0; i < PointsUsed; i++)
        {
            SlotSelector.AddItem(Loc.GetString("marking-slot", ("number", $"{i + 1}")), i);

            if (i == _slot)
            {
                SlotSelector.SelectId(i);
            }
        }
    }

    private string GetMarkingName(MarkingPrototype marking)
    {
        return Loc.GetString($"marking-{marking.ID}");
    }

    // DS14-start
    private bool IsSelectedMarking(string id)
    {
        var selectedId = _markings?[Slot].MarkingId;
        if (selectedId == id)
            return true;

        return _category == MarkingCategories.Hair
            && selectedId == id + "Gradient";
    }

    private static bool IsTechnicalHairGradient(MarkingPrototype marking)
    {
        return marking.MarkingCategory == MarkingCategories.Hair
            && marking.ID.Contains("Gradient", StringComparison.Ordinal);
    }
    // DS14-end
}
