// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using System.Numerics;
using Content.Client.DeadSpace.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.Corvax.TTS;
using Content.Shared.DeadSpace.Communications;
using Content.Shared.DeadSpace.Languages.Prototypes;
using Content.Shared.Decals;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Sources;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.Communications.UI;

[GenerateTypedNameReferences]
public sealed partial class EmagCommunicationsInterface : FancyWindow
{
    private static readonly Vector2 PasswordWindowSize = new(600, 260);
    private static readonly Vector2 FormWindowSize = new(840, 560);
    private static readonly Vector2 FormWindowMinSize = new(760, 520);
    private static readonly Vector2 ColorPaletteSize = new(360, 320);
    private static readonly ProtoId<LanguagePrototype> DefaultLanguageId = "GeneralLanguage";

    private const string SoundCollectionId = "EmagAnnouncementSounds";
    private const int ColorShortLength = 3;
    private const int ColorLongLength = 6;

    [Dependency] private readonly IAudioManager _audioManager = default!;
    [Dependency] private readonly IConfigurationManager _configuration = default!;
    [Dependency] private readonly ILocalizationManager _localization = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;

    private readonly int _maxAnnouncementLength;
    private EmagCommunicationsUiMode _mode = EmagCommunicationsUiMode.Unavailable;
    private IAudioSource? _previewSource;
    private Popup? _colorPalettePopup;
    private OptionButton? _colorPaletteSelector;
    private ItemList? _colorPaletteList;
    private TextureResource? _colorPaletteTexture;
    private bool _previewStarted;
    private bool _passwordRequestPending;
    private bool _announceRequestPending;
    private bool _serverCanAnnounce;
    private bool _showFormValidation;
    private string? _formServerErrorKey;

    public event Action<string>? OnSetPasswordRequested;
    public event Action<string>? OnUnlockRequested;
    public event Action<EmagCommunicationsConsoleAnnounceMessage>? OnAnnounceRequested;
    public event Action? OnReturnToNormalRequested;

    public EmagCommunicationsInterface()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _maxAnnouncementLength = _configuration.GetCVar(CCVars.ChatMaxAnnouncementLength);
        AnnouncementInput.Placeholder = new Rope.Leaf(
            _localization.GetString("emag-comms-announcement-placeholder"));

        PasswordInput.OnTextChanged += _ =>
        {
            SetPasswordError(null);
            UpdatePasswordControls();
        };
        PasswordInput.OnTextEntered += _ => SubmitPassword();
        PasswordConfirmButton.OnPressed += _ => SubmitPassword();
        PasswordReturnToNormalButton.OnPressed += _ => ReturnToNormal();

        AnnouncerInput.OnTextChanged += _ => OnAttributionChanged(AnnouncerInput);
        SignatureInput.OnTextChanged += _ => OnAttributionChanged(SignatureInput);
        ColorHexInput.OnTextChanged += _ => OnColorChanged();
        ColorPreview.OnPressed += _ => ToggleColorPalette();
        AnnouncementInput.OnTextChanged += _ => OnFormChanged();
        SoundSelector.OnItemSelected += OnSoundSelected;
        VoiceSelector.OnItemSelected += OnOptionSelected;
        LanguageSelector.OnItemSelected += OnOptionSelected;
        EnableTtsCheckBox.OnToggled += _ => OnTtsSettingsChanged();
        UseCustomTtsCheckBox.OnToggled += _ => OnTtsSettingsChanged();
        PreviewButton.OnPressed += _ => TogglePreview();
        ReturnToNormalButton.OnPressed += _ => ReturnToNormal();
        AnnounceButton.OnPressed += _ => SubmitAnnouncement();

        AddDs14OptionStyles(SoundSelector, VoiceSelector, LanguageSelector);
        EnableTtsCheckBox.Label.AddStyleClass(DeadSpaceMenuSheetlet.ProfileLabel);
        UseCustomTtsCheckBox.Label.AddStyleClass(DeadSpaceMenuSheetlet.ProfileLabel);

        PopulateVoices();
        PopulateLanguages();
        PopulateSounds();
        UpdateColorPreview();
        UpdateTtsControls();
        UpdatePasswordControls();
        UpdateFormControls();
    }

    public void SetAccessState(
        EmagCommunicationsUiMode mode,
        EmagCommunicationsUiError error,
        bool canAnnounce)
    {
        var previousMode = _mode;
        _mode = mode;
        _serverCanAnnounce = canAnnounce;
        _passwordRequestPending = false;
        _announceRequestPending = false;

        switch (mode)
        {
            case EmagCommunicationsUiMode.PasswordSetup:
                if (previousMode != mode || !PasswordView.Visible)
                    ShowPasswordView(isSetup: true);
                if (error != EmagCommunicationsUiError.None)
                    SetPasswordError(GetPasswordErrorKey(error));
                break;
            case EmagCommunicationsUiMode.Locked:
                if (previousMode != mode || !PasswordView.Visible)
                    ShowPasswordView(isSetup: false);
                if (error != EmagCommunicationsUiError.None)
                    SetPasswordError(GetPasswordErrorKey(error));
                break;
            case EmagCommunicationsUiMode.Authorized:
                if (previousMode != mode || !FormView.Visible)
                {
                    ShowFormView();
                    _formServerErrorKey = null;
                    _showFormValidation = false;
                }

                var formErrorKey = GetFormErrorKey(error);
                if (formErrorKey != null)
                    _formServerErrorKey = formErrorKey;
                else if (!canAnnounce)
                    _formServerErrorKey = "emag-comms-validation-cooldown";
                else if (_formServerErrorKey == "emag-comms-validation-cooldown")
                    _formServerErrorKey = null;
                break;
            case EmagCommunicationsUiMode.Unavailable:
                if (previousMode != mode || !PasswordView.Visible)
                    ShowPasswordView(isSetup: false);
                SetPasswordError("emag-comms-password-error-unavailable");
                break;
        }

        UpdatePasswordControls();
        UpdateFormControls();
    }

    /// <summary>
    /// Releases focus and transient controls before this interface is hidden or orphaned.
    /// </summary>
    public void PrepareToHide()
    {
        ReleaseDescendantFocus();
        StopPreview();
        CloseColorPalette();
    }

    public void StopPreview()
    {
        var source = _previewSource;
        _previewSource = null;
        _previewStarted = false;

        if (source != null)
        {
            if (source.Playing)
                source.StopPlaying();

            source.Dispose();
        }

        PreviewButton.Text = _localization.GetString("emag-comms-preview");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_previewSource != null && _previewStarted && !_previewSource.Playing)
            StopPreview();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            PrepareToHide();
            DisposeColorPalette();
        }

        base.Dispose(disposing);
    }

    private void ShowPasswordView(bool isSetup)
    {
        ReleaseDescendantFocus();
        CloseColorPalette();
        StopPreview();
        PasswordView.Visible = true;
        FormView.Visible = false;
        Resizable = false;
        MinSize = PasswordWindowSize;
        SetSize = PasswordWindowSize;

        PasswordTitle.Text = _localization.GetString(isSetup
            ? "emag-comms-password-setup-title"
            : "emag-comms-password-unlock-title");
        PasswordHint.Text = _localization.GetString(isSetup
            ? "emag-comms-password-setup-hint"
            : "emag-comms-password-unlock-hint");
        PasswordInput.Text = string.Empty;

        if (IsOpen)
            RecenterWindow(new Vector2(0.5f, 0.5f));
    }

    private void ShowFormView()
    {
        ReleaseDescendantFocus();
        CloseColorPalette();
        PasswordView.Visible = false;
        FormView.Visible = true;
        Resizable = true;
        MinSize = FormWindowMinSize;
        SetSize = FormWindowSize;
        PasswordInput.Text = string.Empty;
        SetPasswordError(null);

        if (IsOpen)
            RecenterWindow(new Vector2(0.5f, 0.5f));
    }

    private void PopulateVoices()
    {
        var voices = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .OrderBy(voice => _localization.GetString(voice.Name));

        foreach (var voice in voices)
        {
            var index = VoiceSelector.ItemCount;
            VoiceSelector.AddItem(_localization.GetString(voice.Name));
            VoiceSelector.SetItemMetadata(index, voice.ID);
        }

        if (VoiceSelector.ItemCount > 0)
            VoiceSelector.Select(0);
    }

    private void PopulateLanguages()
    {
        var languages = _prototypeManager
            .EnumeratePrototypes<LanguagePrototype>()
            .OrderBy(language => language.ID == DefaultLanguageId ? 0 : 1)
            .ThenBy(language => _localization.GetString(language.Name));

        foreach (var language in languages)
        {
            var index = LanguageSelector.ItemCount;
            LanguageSelector.AddItem(_localization.GetString(language.Name));
            LanguageSelector.SetItemMetadata(index, new ProtoId<LanguagePrototype>(language.ID));
        }

        if (LanguageSelector.ItemCount > 0)
            LanguageSelector.Select(0);
    }

    private void PopulateSounds()
    {
        if (!_prototypeManager.TryIndex<SoundCollectionPrototype>(SoundCollectionId, out var sounds))
            return;

        foreach (var path in sounds.PickFiles)
        {
            var index = SoundSelector.ItemCount;
            SoundSelector.AddItem(path.FilenameWithoutExtension);
            SoundSelector.SetItemMetadata(index, path);
        }

        if (SoundSelector.ItemCount == 0)
            return;

        SoundSelector.Select(0);
        UpdateSelectedSound();
    }

    private static void AddDs14OptionStyles(params OptionButton[] options)
    {
        foreach (var option in options)
        {
            option.AddStyleClass(DeadSpaceMenuSheetlet.ProfileControl);
            if (!option.OptionStyleClasses.Contains(DeadSpaceMenuSheetlet.ProfileControl))
                option.OptionStyleClasses.Add(DeadSpaceMenuSheetlet.ProfileControl);
        }
    }

    private void OnAttributionChanged(LineEdit input)
    {
        var sanitized = new string(input.Text.Where(character => !char.IsControl(character)).ToArray());
        if (sanitized.Length > EmagCommunicationsConsoleConstants.MaxAttributionLength)
            sanitized = sanitized[..EmagCommunicationsConsoleConstants.MaxAttributionLength];

        if (input.Text != sanitized)
        {
            input.Text = sanitized;
            return;
        }

        OnFormChanged();
    }

    private void OnColorChanged()
    {
        var color = ColorHexInput.Text.Trim();
        if (color.StartsWith('#'))
            color = color[1..];

        color = new string(color.Where(Uri.IsHexDigit).ToArray());
        if (color.Length > ColorLongLength)
            color = color[..ColorLongLength];

        if (ColorHexInput.Text != color)
        {
            ColorHexInput.Text = color;
            return;
        }

        UpdateColorPreview();
        OnFormChanged();
    }

    private void UpdateColorPreview()
    {
        var color = TryGetColor(out var selected)
            ? selected
            : Color.FromHex("#0b1118");

        ColorPreview.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = color,
            BorderColor = Color.FromHex("#3b4e60"),
            BorderThickness = new Thickness(1),
        };
    }

    private bool TryGetColor(out Color color)
    {
        color = default;
        var value = ColorHexInput.Text.Trim();
        if (value.Length != ColorShortLength && value.Length != ColorLongLength)
            return false;

        var parsed = Color.TryFromHex($"#{value}");
        if (parsed == null)
            return false;

        color = parsed.Value;
        return true;
    }

    private void ToggleColorPalette()
    {
        if (_colorPalettePopup is { Visible: true })
        {
            CloseColorPalette();
            return;
        }

        var root = Root;
        if (root == null)
            return;

        EnsureColorPalette();
        if (_colorPalettePopup == null)
            return;

        var popupPosition = ColorPreview.GlobalPosition + new Vector2(0, ColorPreview.Height + 4);
        var maximumX = Math.Max(0, root.Size.X - ColorPaletteSize.X);
        popupPosition.X = Math.Clamp(popupPosition.X, 0, maximumX);

        if (popupPosition.Y + ColorPaletteSize.Y > root.Size.Y)
            popupPosition.Y = Math.Max(0, ColorPreview.GlobalPosition.Y - ColorPaletteSize.Y - 4);

        root.ModalRoot.AddChild(_colorPalettePopup);
        _colorPalettePopup.Open(UIBox2.FromDimensions(popupPosition, ColorPaletteSize));
    }

    private void EnsureColorPalette()
    {
        if (_colorPalettePopup != null)
            return;

        _colorPaletteTexture = _resourceCache.GetResource<TextureResource>(
            "/Textures/Interface/Nano/button.svg.96dpi.png");

        _colorPaletteSelector = new OptionButton
        {
            HorizontalExpand = true,
        };
        AddDs14OptionStyles(_colorPaletteSelector);

        _colorPaletteList = new ItemList
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        _colorPaletteList.AddStyleClass(DeadSpaceMenuSheetlet.TextArea);

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
            SeparationOverride = 6,
            Children =
            {
                _colorPaletteSelector,
                _colorPaletteList,
            },
        };

        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            Children = { content },
        };
        panel.AddStyleClass(DeadSpaceMenuSheetlet.PopupPanel);

        _colorPalettePopup = new Popup
        {
            CloseOnClick = false,
            Children = { panel },
        };
        _colorPalettePopup.OnPopupHide += OnColorPaletteHidden;
        _colorPaletteSelector.OnItemSelected += OnColorPaletteSelected;
        _colorPaletteList.OnItemSelected += OnPaletteColorSelected;

        foreach (var palette in _prototypeManager
                     .EnumeratePrototypes<ColorPalettePrototype>()
                     .OrderBy(palette => palette.Name))
        {
            var index = _colorPaletteSelector.ItemCount;
            _colorPaletteSelector.AddItem(palette.Name);
            _colorPaletteSelector.SetItemMetadata(index, palette);
        }

        if (_colorPaletteSelector.ItemCount > 0)
        {
            _colorPaletteSelector.Select(0);
            PopulatePaletteColors();
        }
    }

    private void OnColorPaletteSelected(OptionButton.ItemSelectedEventArgs args)
    {
        _colorPaletteSelector?.Select(args.Id);
        PopulatePaletteColors();
    }

    private void PopulatePaletteColors()
    {
        if (_colorPaletteList == null ||
            _colorPaletteTexture == null ||
            _colorPaletteSelector?.SelectedMetadata is not ColorPalettePrototype palette)
        {
            return;
        }

        _colorPaletteList.Clear();
        foreach (var (name, color) in palette.Colors)
        {
            var item = _colorPaletteList.AddItem(name, _colorPaletteTexture.Texture);
            item.Metadata = color;
            item.IconModulate = color;
        }
    }

    private void OnPaletteColorSelected(ItemList.ItemListSelectedEventArgs args)
    {
        var selected = args.ItemList.GetSelected().FirstOrDefault();
        if (selected?.Metadata is not Color color)
            return;

        ReleaseDescendantFocus();
        ColorHexInput.Text = color.ToHexNoAlpha().TrimStart('#');
        UpdateColorPreview();
        OnFormChanged();
        CloseColorPalette();
    }

    private void CloseColorPalette()
    {
        if (_colorPalettePopup == null)
            return;

        ReleaseFocusWithin(_colorPalettePopup);
        if (_colorPalettePopup.Visible)
            _colorPalettePopup.Close();
        else
            _colorPalettePopup.Orphan();
    }

    private void OnColorPaletteHidden()
    {
        _colorPalettePopup?.Orphan();
    }

    private void DisposeColorPalette()
    {
        var popup = _colorPalettePopup;
        if (popup == null)
            return;

        popup.OnPopupHide -= OnColorPaletteHidden;
        popup.Orphan();
        popup.Dispose();
        _colorPalettePopup = null;
        _colorPaletteSelector = null;
        _colorPaletteList = null;
        _colorPaletteTexture = null;
    }

    private void OnSoundSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SoundSelector.Select(args.Id);
        StopPreview();
        UpdateSelectedSound();
        OnFormChanged();
    }

    private void UpdateSelectedSound()
    {
        if (SoundSelector.ItemCount == 0 ||
            SoundSelector.SelectedMetadata is not ResPath path ||
            !_resourceCache.TryGetResource<AudioResource>(path, out var audio))
        {
            SoundDuration.Text = "00:00";
            return;
        }

        SoundDuration.Text = audio.AudioStream.Length.ToString(@"mm\:ss");
    }

    private void TogglePreview()
    {
        if (_previewSource is { Playing: true })
        {
            StopPreview();
            return;
        }

        StopPreview();

        if (SoundSelector.ItemCount == 0 ||
            SoundSelector.SelectedMetadata is not ResPath path ||
            !_resourceCache.TryGetResource<AudioResource>(path, out var audio))
        {
            return;
        }

        var source = _audioManager.CreateAudioSource(audio.AudioStream);
        if (source == null)
            return;

        _previewSource = source;
        source.Global = true;
        source.StartPlaying();
        _previewStarted = true;
        PreviewButton.Text = _localization.GetString("emag-comms-stop");
    }

    private void OnOptionSelected(OptionButton.ItemSelectedEventArgs args)
    {
        args.Button.Select(args.Id);
        OnFormChanged();
    }

    private void OnTtsSettingsChanged()
    {
        UpdateTtsControls();
        OnFormChanged();
    }

    private void UpdateTtsControls()
    {
        VoiceSelector.Disabled = !EnableTtsCheckBox.Pressed || !UseCustomTtsCheckBox.Pressed;
    }

    private void SubmitPassword()
    {
        if (_passwordRequestPending || !IsPasswordValid(PasswordInput.Text))
            return;

        var password = PasswordInput.Text;
        var handler = _mode switch
        {
            EmagCommunicationsUiMode.PasswordSetup => OnSetPasswordRequested,
            EmagCommunicationsUiMode.Locked => OnUnlockRequested,
            _ => null,
        };
        if (handler == null)
            return;

        ReleaseDescendantFocus();
        _passwordRequestPending = true;
        SetPasswordError(null);
        UpdatePasswordControls();
        handler.Invoke(password);
    }

    private static bool IsPasswordValid(string password)
    {
        return password.Length is > 0 and <= EmagCommunicationsConsoleConstants.MaxPasswordLength &&
               !string.IsNullOrWhiteSpace(password) &&
               password.All(character => !char.IsControl(character));
    }

    private void UpdatePasswordControls()
    {
        PasswordConfirmButton.Disabled = _passwordRequestPending ||
                                         _mode is not (EmagCommunicationsUiMode.PasswordSetup or EmagCommunicationsUiMode.Locked) ||
                                         !IsPasswordValid(PasswordInput.Text);
    }

    private void SetPasswordError(string? localeKey)
    {
        var errorText = localeKey == null ? string.Empty : _localization.GetString(localeKey);
        PasswordError.Visible = localeKey != null;
        PasswordError.SetMessage(errorText, Color.FromHex("#E86767"));
        PasswordError.ToolTip = localeKey == null ? null : errorText;
    }

    private static string? GetPasswordErrorKey(EmagCommunicationsUiError error)
    {
        return error switch
        {
            EmagCommunicationsUiError.None => null,
            EmagCommunicationsUiError.InvalidPasswordFormat => "emag-comms-password-error-invalid",
            EmagCommunicationsUiError.IncorrectPassword => "emag-comms-password-error-incorrect",
            EmagCommunicationsUiError.PasswordAlreadySet => "emag-comms-password-error-already-set",
            EmagCommunicationsUiError.Unavailable => "emag-comms-password-error-unavailable",
            _ => "emag-comms-password-error-request-failed",
        };
    }

    private void SubmitAnnouncement()
    {
        if (_announceRequestPending || !_serverCanAnnounce)
            return;

        if (!TryBuildAnnouncement(out var message, out var validationErrorKey))
        {
            _showFormValidation = true;
            _formServerErrorKey = validationErrorKey;
            UpdateFormControls();
            return;
        }

        if (OnAnnounceRequested == null)
            return;

        ReleaseDescendantFocus();
        CloseColorPalette();
        _formServerErrorKey = null;
        _showFormValidation = false;
        _announceRequestPending = true;
        UpdateFormControls();
        OnAnnounceRequested.Invoke(message);
    }

    private bool TryBuildAnnouncement(
        out EmagCommunicationsConsoleAnnounceMessage message,
        out string? validationErrorKey)
    {
        message = default!;
        validationErrorKey = GetValidationErrorKey();
        if (validationErrorKey != null)
            return false;

        var language = (ProtoId<LanguagePrototype>) LanguageSelector.SelectedMetadata!;
        var sound = (ResPath) SoundSelector.SelectedMetadata!;
        var voice = VoiceSelector.ItemCount > 0 && VoiceSelector.SelectedMetadata is string voiceId
            ? voiceId
            : string.Empty;

        message = new EmagCommunicationsConsoleAnnounceMessage(
            AnnouncerInput.Text,
            SignatureInput.Text,
            Rope.Collapse(AnnouncementInput.TextRope),
            language,
            EnableTtsCheckBox.Pressed,
            UseCustomTtsCheckBox.Pressed,
            voice,
            ColorHexInput.Text,
            sound.ToString());
        return true;
    }

    private string? GetValidationErrorKey()
    {
        var announcement = Rope.Collapse(AnnouncementInput.TextRope);
        if (string.IsNullOrWhiteSpace(announcement))
            return "emag-comms-validation-required";

        if (AnnouncementInput.TextLength > _maxAnnouncementLength)
            return "emag-comms-validation-too-long";

        if (!TryGetColor(out _))
            return "emag-comms-validation-invalid-color";

        if (SoundSelector.ItemCount == 0 || SoundSelector.SelectedMetadata is not ResPath)
            return "emag-comms-validation-select-sound";

        if (LanguageSelector.ItemCount == 0 ||
            LanguageSelector.SelectedMetadata is not ProtoId<LanguagePrototype>)
        {
            return "emag-comms-validation-select-language";
        }

        if (EnableTtsCheckBox.Pressed &&
            UseCustomTtsCheckBox.Pressed &&
            (VoiceSelector.ItemCount == 0 || VoiceSelector.SelectedMetadata is not string))
        {
            return "emag-comms-validation-select-voice";
        }

        return null;
    }

    private void OnFormChanged()
    {
        if (_serverCanAnnounce)
            _formServerErrorKey = null;
        UpdateFormControls();
    }

    private void UpdateFormControls()
    {
        CharacterCounter.Text = _localization.GetString(
            "emag-comms-character-counter",
            ("current", AnnouncementInput.TextLength),
            ("maximum", _maxAnnouncementLength));

        var validationErrorKey = GetValidationErrorKey();
        var displayedErrorKey = (_showFormValidation ? validationErrorKey : null) ?? _formServerErrorKey;
        var displayedError = displayedErrorKey == null
            ? string.Empty
            : _localization.GetString(displayedErrorKey, ("maximum", _maxAnnouncementLength));
        FormStatus.Visible = displayedErrorKey != null;
        FormStatus.SetMessage(displayedError, Color.FromHex("#E86767"));
        FormStatus.ToolTip = displayedErrorKey == null ? null : displayedError;

        AnnounceButton.Disabled = _mode != EmagCommunicationsUiMode.Authorized ||
                                  !_serverCanAnnounce ||
                                  _announceRequestPending ||
                                  validationErrorKey != null;
    }

    private void ReturnToNormal()
    {
        PrepareToHide();
        OnReturnToNormalRequested?.Invoke();
    }

    private void ReleaseDescendantFocus()
    {
        ReleaseFocusWithin(this);

        if (_colorPalettePopup != null)
            ReleaseFocusWithin(_colorPalettePopup);
    }

    private void ReleaseFocusWithin(Control ancestor)
    {
        if (_uiManager.KeyboardFocused is { } keyboardFocused &&
            IsDescendantOrSelf(keyboardFocused, ancestor))
        {
            _uiManager.ReleaseKeyboardFocus();
        }

        if (_uiManager.ControlFocused is { } controlFocused &&
            IsDescendantOrSelf(controlFocused, ancestor))
        {
            _uiManager.ControlFocused = null;
        }
    }

    private static bool IsDescendantOrSelf(Control control, Control ancestor)
    {
        for (Control? current = control; current != null; current = current.Parent)
        {
            if (current == ancestor)
                return true;
        }

        return false;
    }

    private static string? GetFormErrorKey(EmagCommunicationsUiError error)
    {
        return error switch
        {
            EmagCommunicationsUiError.None => null,
            EmagCommunicationsUiError.Cooldown => "emag-comms-validation-cooldown",
            EmagCommunicationsUiError.InvalidAnnouncement => "emag-comms-validation-required",
            EmagCommunicationsUiError.InvalidSound => "emag-comms-validation-select-sound",
            EmagCommunicationsUiError.InvalidLanguage => "emag-comms-validation-select-language",
            EmagCommunicationsUiError.InvalidVoice => "emag-comms-validation-select-voice",
            _ => "emag-comms-validation-request-failed",
        };
    }
}
