// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.DeadSpace.Administration.GamePreset;
using Content.Shared.DeadSpace.Administration.GamePreset;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.GamePreset;

[GenerateTypedNameReferences]
public sealed partial class CreatePresetWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private GamePresetClientSystem _system = default!;
    private string? _editPresetId;
    private List<string> _availableModes = new();
    private readonly Dictionary<string, CheckBox> _modeCheckBoxes = new();
    private Color? _saveButtonOriginalColor;

    public CreatePresetWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entityManager.System<GamePresetClientSystem>();
        _saveButtonOriginalColor = SaveButton.ModulateSelfOverride;
        SaveButton.OnPressed += _ => Save();
    }

    public void LoadModes(List<string> modes, Dictionary<string, string> names)
    {
        _availableModes = modes;
        ModesGrid.RemoveAllChildren();
        _modeCheckBoxes.Clear();

        foreach (var mode in modes)
        {
            var checkBox = new CheckBox { Text = names.GetValueOrDefault(mode, mode) };
            _modeCheckBoxes[mode] = checkBox;
            ModesGrid.AddChild(checkBox);
        }
    }

    public void LoadPreset(CustomPresetData data)
    {
        _editPresetId = data.PresetId;
        PresetNameEdit.Text = data.PresetName;
        RdmCheckBox.Pressed = data.PresetType == "rdm";
        SecretCheckBox.Pressed = data.Secret;

        foreach (var mode in _availableModes)
        {
            if (_modeCheckBoxes.TryGetValue(mode, out var cb))
                cb.Pressed = data.Modes.Contains(mode);
        }
    }

    private void Save()
    {
        var name = PresetNameEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
        {
            SaveButton.ModulateSelfOverride = Color.FromHex("#f85149");
            Timer.Spawn(TimeSpan.FromSeconds(1), () =>
            {
                SaveButton.ModulateSelfOverride = _saveButtonOriginalColor;
            });
            return;
        }

        var selectedModes = new List<string>();
        foreach (var (mode, cb) in _modeCheckBoxes)
        {
            if (cb.Pressed)
                selectedModes.Add(mode);
        }

        if (selectedModes.Count == 0)
        {
            SaveButton.ModulateSelfOverride = Color.FromHex("#f85149");
            Timer.Spawn(TimeSpan.FromSeconds(1), () =>
            {
                SaveButton.ModulateSelfOverride = _saveButtonOriginalColor;
            });
            return;
        }

        var presetType = RdmCheckBox.Pressed ? "rdm" : "calm";
        var secret = SecretCheckBox.Pressed;

        if (_editPresetId != null)
            _system.UpdateCustomPreset(_editPresetId, name, selectedModes, presetType, secret);
        else
            _system.CreateCustomPreset(name, selectedModes, presetType, secret);

        _system.RequestPresets();
        Close();
    }
}