// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.DeadSpace.Administration.GamePreset;
using Content.Shared.DeadSpace.Administration.GamePreset;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.GamePreset;

[GenerateTypedNameReferences]
public sealed partial class CreateDemocracyPresetWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private GamePresetClientSystem _system = default!;
    private string? _editPresetId;
    private List<string> _availablePresetIds = new();
    private readonly Dictionary<string, CheckBox> _presetCheckBoxes = new();
    private Color? _saveButtonOriginalColor;

    public CreateDemocracyPresetWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entityManager.System<GamePresetClientSystem>();
        _saveButtonOriginalColor = SaveButton.ModulateSelfOverride;
        SaveButton.OnPressed += _ => Save();
    }

    public void SetPresets(List<string> presetIds, Dictionary<string, string> names)
    {
        _availablePresetIds = presetIds;
        PresetsGrid.RemoveAllChildren();
        _presetCheckBoxes.Clear();

        foreach (var id in presetIds)
        {
            var checkBox = new CheckBox { Text = names.GetValueOrDefault(id, id) };
            _presetCheckBoxes[id] = checkBox;
            PresetsGrid.AddChild(checkBox);
        }
    }

    public void LoadPreset(CustomPresetData data)
    {
        _editPresetId = data.PresetId;
        PresetNameEdit.Text = data.PresetName;

        foreach (var id in _availablePresetIds)
        {
            if (_presetCheckBoxes.TryGetValue(id, out var cb))
                cb.Pressed = data.Modes.Contains(id);
        }
    }

    private void Save()
    {
        var name = PresetNameEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
        {
            SaveButton.ModulateSelfOverride = Color.FromHex("#f85149");
            Timer.Spawn(TimeSpan.FromSeconds(1), () =>
            {
                SaveButton.ModulateSelfOverride = _saveButtonOriginalColor;
            });
            return;
        }

        var selectedPresets = new List<string>();
        foreach (var (id, cb) in _presetCheckBoxes)
        {
            if (cb.Pressed)
                selectedPresets.Add(id);
        }

        if (selectedPresets.Count == 0)
        {
            SaveButton.ModulateSelfOverride = Color.FromHex("#f85149");
            Timer.Spawn(TimeSpan.FromSeconds(1), () =>
            {
                SaveButton.ModulateSelfOverride = _saveButtonOriginalColor;
            });
            return;
        }

        if (_editPresetId != null)
            _system.UpdateCustomPreset(_editPresetId, name, selectedPresets, "democracy", false);
        else
            _system.CreateCustomPreset(name, selectedPresets, "democracy", false);

        _system.RequestPresets();
        Close();
    }
}