// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using System.Numerics;
using Content.Client.DeadSpace.Administration.GamePreset;
using Content.Shared.DeadSpace.Administration.GamePreset;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.GamePreset;

[GenerateTypedNameReferences]
public sealed partial class GamePresetWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private GamePresetClientSystem _system = default!;

    private List<string> _activePresetIds = new();
    private List<string> _pendingActivePresetIds = new();
    private List<CustomPresetData> _customPresets = new();
    private Dictionary<string, string> _presetNames = new();
    private Dictionary<string, string> _modeNames = new();
    private int _maxRdmRow;
    private int _voteDurationSeconds;
    private int _currentPresetIndex;
    private bool _systemEnabled;
    private bool _hasUnsavedChanges;
    private bool _disableOocDuringVote;
    private bool _preventRepeatMode;
    private bool _checkPlayerLimit;
    private List<string> _whitelistModeIds = new();
    private int _rdmStreak;
    private bool _isLobby;

    private CreatePresetWindow? _createWindow;
    private CreateDemocracyPresetWindow? _democracyWindow;
    private PresetSettingsWindow? _settingsWindow;

    private TimeSpan _updateAccumulator;
    private List<CustomPresetData> _lastCustomPresets = new();
    private bool _forceRefresh;

    private const int ActivePresetsPerRow = 5;

    public GamePresetWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entityManager.System<GamePresetClientSystem>();
        _system.PresetsUpdated += OnPresetsUpdated;

        SystemToggle.OnToggled += args =>
        {
            _system.SetSystemEnabled(args.Pressed);
        };

        RefreshButton.OnPressed += _ =>
        {
            _forceRefresh = true;
            _system.RequestPresets();
        };
        InitiateVoteButton.OnPressed += _ => _system.InitiateVoteNow();
        SkipPresetButton.OnPressed += _ => _system.SkipCurrentPreset();
        SettingsButton.OnPressed += _ => OpenSettingsWindow();
        SaveButton.OnPressed += _ => SaveChanges();

        OnClose += HandleClose;
    }

    protected override void Opened()
    {
        base.Opened();
        _system.RequestPresets();
        _updateAccumulator = TimeSpan.Zero;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _updateAccumulator += TimeSpan.FromSeconds(args.DeltaSeconds);
        if (_updateAccumulator < TimeSpan.FromSeconds(1))
            return;
        _updateAccumulator = TimeSpan.Zero;
        _system.RequestPresets();
    }

    private void HandleClose()
    {
        if (!_hasUnsavedChanges)
            return;

        var dialog = new DefaultWindow
        {
            Title = Loc.GetString("game-preset-unsaved-changes-title"),
            MinSize = new Vector2(350, 120),
            Resizable = false
        };
        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(12, 8),
            SeparationOverride = 12
        };
        vbox.AddChild(new Label
        {
            Text = Loc.GetString("game-preset-unsaved-changes-message")
        });
        var buttons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalAlignment = HAlignment.Center
        };
        var saveButton = new Button
        {
            Text = Loc.GetString("game-preset-unsaved-save"),
            MinWidth = 100,
            ModulateSelfOverride = Color.FromHex("#2ea043")
        };
        saveButton.OnPressed += _ =>
        {
            SaveChanges();
            dialog.Close();
            CloseChildren();
            _system.PresetsUpdated -= OnPresetsUpdated;
            _system = null!;
            _hasUnsavedChanges = false;
            base.Close();
        };
        var discardButton = new Button
        {
            Text = Loc.GetString("game-preset-unsaved-discard"),
            MinWidth = 100,
            ModulateSelfOverride = Color.FromHex("#f85149")
        };
        discardButton.OnPressed += _ =>
        {
            dialog.Close();
            CloseChildren();
            _system.PresetsUpdated -= OnPresetsUpdated;
            _system = null!;
            _hasUnsavedChanges = false;
            base.Close();
        };
        buttons.AddChild(saveButton);
        buttons.AddChild(discardButton);
        vbox.AddChild(buttons);
        dialog.Contents.AddChild(vbox);
        dialog.OpenCentered();
    }

    public override void Close()
    {
        if (_hasUnsavedChanges)
        {
            HandleClose();
            return;
        }
        CloseChildren();
        base.Close();
        _system.PresetsUpdated -= OnPresetsUpdated;
        _system = null!;
    }

    private void CloseChildren()
    {
        _createWindow?.Close();
        _democracyWindow?.Close();
        _settingsWindow?.Close();
    }

    private void OnPresetsUpdated(GamePresetsResponseMessage msg)
    {
        _activePresetIds = msg.ActivePresetIds;
        if (!_hasUnsavedChanges)
            _pendingActivePresetIds = new List<string>(_activePresetIds);
        _customPresets = msg.CustomPresets;
        _presetNames = msg.PresetNames;
        _modeNames = msg.ModeNames;
        _maxRdmRow = msg.MaxRdmRow;
        _voteDurationSeconds = msg.VoteDurationSeconds;
        _currentPresetIndex = msg.CurrentPresetIndex;
        _systemEnabled = msg.SystemEnabled;
        _disableOocDuringVote = msg.DisableOocDuringVote;
        _preventRepeatMode = msg.PreventRepeatMode;
        _checkPlayerLimit = msg.CheckPlayerLimit;
        _whitelistModeIds = msg.WhitelistModeIds ?? new List<string>();
        _rdmStreak = msg.RdmStreak;
        _isLobby = msg.IsLobby;

        SystemToggle.Pressed = _systemEnabled;

        RdmCounterLabel.Visible = _maxRdmRow > 0;
        RdmCounterLabel.Text = _maxRdmRow > 0 ? $"{_rdmStreak}/{_maxRdmRow} РДМ" : "";

        if (_forceRefresh || !PresetsEqual(_customPresets, _lastCustomPresets))
        {
            _lastCustomPresets = _customPresets.Select(p => new CustomPresetData(p.PresetId, p.PresetName, p.Modes, p.PresetType, p.Secret)).ToList();
            RebuildCustomPanel();
        }
        _forceRefresh = false;

        RebuildActivePanel();
    }

    private static bool PresetsEqual(List<CustomPresetData> a, List<CustomPresetData> b)
    {
        if (a.Count != b.Count)
            return false;

        for (int i = 0; i < a.Count; i++)
        {
            if (a[i].PresetId != b[i].PresetId ||
                a[i].PresetName != b[i].PresetName ||
                a[i].PresetType != b[i].PresetType ||
                a[i].Secret != b[i].Secret ||
                !a[i].Modes.SequenceEqual(b[i].Modes))
                return false;
        }
        return true;
    }

    private void SaveChanges()
    {
        _system.SetActivePresets(new List<string>(_pendingActivePresetIds));
        _hasUnsavedChanges = false;
        _system.RequestPresets();
    }

    private void MarkUnsaved()
    {
        _hasUnsavedChanges = true;
    }

    private void RebuildActivePanel()
    {
        ActivePresetRows.RemoveAllChildren();

        var rows = (int)Math.Ceiling((double)_pendingActivePresetIds.Count / ActivePresetsPerRow);
        var currentIndex = _currentPresetIndex;
        var isLobby = _isLobby;

        for (var row = 0; row < rows; row++)
        {
            var rowPanel = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                HorizontalExpand = true
            };

            var start = row * ActivePresetsPerRow;
            var end = Math.Min(start + ActivePresetsPerRow, _pendingActivePresetIds.Count);

            for (var i = start; i < end; i++)
            {
                var id = _pendingActivePresetIds[i];
                var card = CreateActivePresetCard(id, i == currentIndex && isLobby);
                rowPanel.AddChild(card);

                var arrow = new Label
                {
                    Text = "→",
                    VerticalAlignment = VAlignment.Center,
                    Margin = new Thickness(6, 0),
                    FontColorOverride = Color.FromHex("#aaaaaa")
                };
                if (!isLobby && i == currentIndex)
                {
                    arrow.FontColorOverride = Color.FromHex("#2ea043");
                }
                rowPanel.AddChild(arrow);
            }

            ActivePresetRows.AddChild(rowPanel);
        }
    }

    private void RebuildCustomPanel()
    {
        CustomPresetPanel.RemoveAllChildren();

        var addButtons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            VerticalAlignment = VAlignment.Top
        };

        var addPresetButton = new Button
        {
            Text = Loc.GetString("game-preset-add-button"),
            SetSize = new Vector2(180, 80),
            Margin = new Thickness(4),
            ToolTip = Loc.GetString("game-preset-add-button-tooltip")
        };
        addPresetButton.OnPressed += _ => OpenCreateWindow(false);
        addButtons.AddChild(addPresetButton);

        var addDemocracyButton = new Button
        {
            SetSize = new Vector2(180, 80),
            Margin = new Thickness(4),
            ToolTip = Loc.GetString("game-preset-add-democracy-button-tooltip")
        };

        var democracyText = Loc.GetString("game-preset-add-democracy-button");
        var lines = democracyText.Split('\n');
        var verticalBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            SeparationOverride = 2
        };
        foreach (var line in lines)
        {
            if (string.IsNullOrWhiteSpace(line))
                continue;

            verticalBox.AddChild(new Label
            {
                Text = line.Trim(),
                HorizontalAlignment = HAlignment.Center,
                ClipText = false
            });
        }
        addDemocracyButton.AddChild(verticalBox);
        addDemocracyButton.OnPressed += _ => OpenCreateWindow(true);
        addButtons.AddChild(addDemocracyButton);

        CustomPresetPanel.AddChild(addButtons);

        foreach (var preset in _customPresets)
        {
            var card = CreateCustomPresetCard(preset.PresetId);
            CustomPresetPanel.AddChild(card);
        }
    }

    private PanelContainer CreateActivePresetCard(string presetId, bool isCurrent)
    {
        var preset = _customPresets.FirstOrDefault(p => p.PresetId == presetId);
        var isRdm = preset != null && preset.PresetType == "rdm";
        var isSecret = preset?.Secret ?? false;

        var panel = new PanelContainer
        {
            StyleClasses = { "PanelDark" },
            MinSize = new Vector2(200, 44),
            Margin = new Thickness(4)
        };

        if (isCurrent && _pendingActivePresetIds.Count > 0)
        {
            panel.PanelOverride = new StyleBoxFlat
            {
                BorderColor = Color.FromHex("#2ea043"),
                BorderThickness = new Thickness(2),
                BackgroundColor = ResolveBackgroundColor(isRdm, isSecret)
            };
        }
        else
        {
            if (isRdm || isSecret)
            {
                panel.PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = ResolveBackgroundColor(isRdm, isSecret)
                };
            }
        }

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0)
        };

        var nameLabel = new Label
        {
            Text = _presetNames.GetValueOrDefault(presetId, presetId),
            ClipText = true,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center
        };
        var namePanel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#333333"),
                BorderThickness = new Thickness(1),
                BorderColor = Color.FromHex("#555555"),
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4
            },
            Children = { nameLabel }
        };
        header.AddChild(namePanel);

        var removeButton = CreateCloseButton(() =>
        {
            _pendingActivePresetIds.Remove(presetId);
            MarkUnsaved();
            RebuildActivePanel();
        });
        header.AddChild(removeButton);

        panel.AddChild(header);
        return panel;
    }

    private PanelContainer CreateCustomPresetCard(string presetId)
    {
        var preset = _customPresets.FirstOrDefault(p => p.PresetId == presetId);
        var isRdm = preset != null && preset.PresetType == "rdm";
        var isDemocracy = preset != null && preset.PresetType == "democracy";
        var isSecret = preset?.Secret ?? false;

        var panel = new PanelContainer
        {
            StyleClasses = { "PanelDark" },
            MinSize = new Vector2(200, 120),
            Margin = new Thickness(4)
        };

        if (isRdm || isSecret)
        {
            panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = ResolveBackgroundColor(isRdm, isSecret)
            };
        }

        var mainContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(6, 4),
            VerticalExpand = true
        };

        var topRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            VerticalAlignment = VAlignment.Center
        };

        if (isRdm)
        {
            topRow.AddChild(new Label
            {
                Text = "⚔",
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 4, 0)
            });
        }
        if (isSecret)
        {
            topRow.AddChild(new Label
            {
                Text = "?",
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 4, 0)
            });
        }

        var spacer = new Control
        {
            HorizontalExpand = true
        };
        topRow.AddChild(spacer);

        var editButton = new Button
        {
            Text = "⚙",
            MinWidth = 20,
            ToolTip = Loc.GetString("game-preset-edit-button"),
            VerticalAlignment = VAlignment.Center
        };
        editButton.OnPressed += _ => OpenEditWindow(presetId);
        topRow.AddChild(editButton);

        var removeButton = CreateCloseButton(() =>
        {
            _system.DeleteCustomPreset(presetId);
            _system.RequestPresets();
        });
        topRow.AddChild(removeButton);

        mainContainer.AddChild(topRow);

        var nameLabel = new Label
        {
            Text = preset?.PresetName ?? presetId,
            ClipText = true,
            HorizontalExpand = true
        };
        var namePanel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 2),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#333333"),
                BorderThickness = new Thickness(1),
                BorderColor = Color.FromHex("#555555"),
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4
            },
            Children = { nameLabel }
        };
        mainContainer.AddChild(namePanel);

        var modesList = new ScrollContainer
        {
            VerticalExpand = true,
            MinHeight = 60
        };
        var modesBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 2
        };

        if (preset != null)
        {
            foreach (var modeId in preset.Modes)
            {
                var displayName = isDemocracy
                    ? _presetNames.GetValueOrDefault(modeId, modeId)
                    : _modeNames.GetValueOrDefault(modeId, modeId);
                modesBox.AddChild(new Label
                {
                    Text = displayName,
                    ClipText = true
                });
            }
        }

        modesList.AddChild(modesBox);
        mainContainer.AddChild(modesList);

        var addButton = new Button
        {
            Text = Loc.GetString("game-preset-add-button"),
            HorizontalExpand = true
        };
        addButton.OnPressed += _ =>
        {
            _pendingActivePresetIds.Add(presetId);
            MarkUnsaved();
            RebuildActivePanel();
        };
        mainContainer.AddChild(addButton);

        panel.AddChild(mainContainer);
        return panel;
    }

    private Button CreateCloseButton(Action onPressed)
    {
        var button = new Button
        {
            Text = "×",
            MinWidth = 20,
            MinHeight = 20,
            StyleClasses = { "WindowCloseButton" },
            ModulateSelfOverride = Color.FromHex("#f85149")
        };

        button.OnPressed += _ => onPressed();
        return button;
    }

    private void OpenCreateWindow(bool isDemocracy)
    {
        if (isDemocracy)
        {
            if (_democracyWindow is { Disposed: false })
                _democracyWindow.Close();

            _democracyWindow = new CreateDemocracyPresetWindow();
            var customPresetIds = _customPresets.Select(p => p.PresetId).ToList();
            _democracyWindow.SetPresets(customPresetIds, _presetNames);
            _democracyWindow.OpenCentered();
        }
        else
        {
            OpenPresetWindow(null);
        }
    }

    private void OpenEditWindow(string presetId)
    {
        var data = _customPresets.Find(p => p.PresetId == presetId);
        if (data == null)
            return;

        if (data.PresetType == "democracy")
        {
            if (_democracyWindow is { Disposed: false })
                _democracyWindow.Close();

            _democracyWindow = new CreateDemocracyPresetWindow();
            var customPresetIds = _customPresets
                .Select(p => p.PresetId)
                .Where(id => id != presetId)
                .ToList();
            _democracyWindow.SetPresets(customPresetIds, _presetNames);
            _democracyWindow.LoadPreset(data);
            _democracyWindow.OpenCentered();
        }
        else
        {
            OpenPresetWindow(data);
        }
    }

    private void OpenPresetWindow(CustomPresetData? data)
    {
        if (_createWindow is { Disposed: false })
            _createWindow.Close();

        _createWindow = new CreatePresetWindow();
        _createWindow.LoadModes(
            _presetNames.Keys.Where(k => !k.StartsWith("custom_")).ToList(),
            _presetNames);

        if (data != null)
            _createWindow.LoadPreset(data);

        _createWindow.OpenCentered();
    }

    private void OpenSettingsWindow()
    {
        if (_settingsWindow is { Disposed: false })
            _settingsWindow.Close();

        _settingsWindow = new PresetSettingsWindow();
        _settingsWindow.LoadSettings(_maxRdmRow, _voteDurationSeconds, _disableOocDuringVote, _preventRepeatMode, _checkPlayerLimit, _whitelistModeIds);
        _settingsWindow.OpenCentered();
    }

    private Color ResolveBackgroundColor(bool isRdm, bool isSecret)
    {
        if (isRdm && isSecret)
            return Color.FromHex("#270a27");
        if (isRdm)
            return Color.FromHex("#270a0a");
        if (isSecret)
            return Color.FromHex("#0a0a27");
        return Color.FromHex("#1e1e1e");
    }
}