// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using Content.Client.DeadSpace.Administration.GamePreset;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.GamePreset;

[GenerateTypedNameReferences]
public sealed partial class PresetSettingsWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private GamePresetClientSystem _system = default!;
    private List<string> _currentWhitelist = new();

    public PresetSettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entityManager.System<GamePresetClientSystem>();
        SaveSettingsButton.OnPressed += _ => SaveSettings();

        EnableMaxRdmRowCheckBox.OnToggled += _ => UpdateSpinBoxes();
        WhitelistButton.OnPressed += _ => OpenWhitelistWindow();
    }

    public void LoadSettings(int maxRdmRow, int voteDurationSeconds, bool disableOoc, bool preventRepeat, bool checkPlayerLimit, List<string> whitelistModeIds)
    {
        EnableMaxRdmRowCheckBox.Pressed = maxRdmRow > 0;
        MaxRdmRowSpinBox.Value = maxRdmRow > 0 ? maxRdmRow : 2;
        VoteDurationSpinBox.Value = voteDurationSeconds > 0 ? voteDurationSeconds : 30;
        DisableOocCheckBox.Pressed = disableOoc;
        PreventRepeatCheckBox.Pressed = preventRepeat;
        CheckPlayerLimitCheckBox.Pressed = checkPlayerLimit;
        _currentWhitelist = whitelistModeIds ?? new List<string>();
        UpdateSpinBoxes();
    }

    private void UpdateSpinBoxes()
    {
        MaxRdmRowSpinBox.ModulateSelfOverride = EnableMaxRdmRowCheckBox.Pressed ? null : Color.FromHex("#666666");
    }

    private void SaveSettings()
    {
        var maxRow = EnableMaxRdmRowCheckBox.Pressed ? MaxRdmRowSpinBox.Value : 0;
        var voteDuration = VoteDurationSpinBox.Value;
        var disableOoc = DisableOocCheckBox.Pressed;
        var preventRepeat = PreventRepeatCheckBox.Pressed;
        var checkPlayerLimit = CheckPlayerLimitCheckBox.Pressed;

        _system.UpdatePresetSettings(maxRow, voteDuration, disableOoc, preventRepeat, checkPlayerLimit, _currentWhitelist);
        Close();
    }

    private void OpenWhitelistWindow()
    {
        var clientSystem = _entityManager.System<GamePresetClientSystem>();
        var window = new WhitelistWindow();
        window.LoadModes(
            clientSystem.PresetNames.Keys.Where(k => !k.StartsWith("custom_")).ToList(),
            clientSystem.PresetNames,
            _currentWhitelist);
        window.OnWhitelistSaved += (selected) =>
        {
            _currentWhitelist = selected;
        };
        window.OpenCentered();
    }
}