// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT
using System.Collections.Generic;
using System.Linq;
using Content.Client.DeadSpace.Administration.GamePreset;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.GamePreset;

[GenerateTypedNameReferences]
public sealed partial class WhitelistWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private GamePresetClientSystem _system = default!;
    private List<string> _availableModes = new();
    private readonly Dictionary<string, CheckBox> _modeCheckBoxes = new();
    private List<string> _initialWhitelist = new();

    public WhitelistWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _system = _entityManager.System<GamePresetClientSystem>();
        SaveButton.OnPressed += _ => Save();
    }

    public void LoadModes(List<string> modes, Dictionary<string, string> names, List<string> currentWhitelist)
    {
        _availableModes = modes;
        _initialWhitelist = currentWhitelist ?? new List<string>();
        ModesGrid.RemoveAllChildren();
        _modeCheckBoxes.Clear();

        foreach (var mode in modes)
        {
            var checkBox = new CheckBox { Text = names.GetValueOrDefault(mode, mode) };
            checkBox.Pressed = _initialWhitelist.Contains(mode);
            _modeCheckBoxes[mode] = checkBox;
            ModesGrid.AddChild(checkBox);
        }
    }

    private void Save()
    {
        var selected = _modeCheckBoxes
            .Where(kv => kv.Value.Pressed)
            .Select(kv => kv.Key)
            .ToList();

        OnWhitelistSaved?.Invoke(selected);
        Close();
    }

    public event System.Action<List<string>>? OnWhitelistSaved;
}