// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Shared.Telephone;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using System.Text;

namespace Content.Client.DeadSpace.RedPhone;

[GenerateTypedNameReferences]
public sealed partial class RedPhoneReportWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private EntityUid? _owner;
    private TelephoneState _currentState;
    private TelephoneState _previousState;
    private TimeSpan _buttonUnlockTime;
    private float _updateTimer = UpdateTime;

    private const float UpdateTime = 0.25f;
    private static readonly TimeSpan ButtonUnlockDelay = TimeSpan.FromSeconds(0.5f);

    public event Action<string>? Submit;
    public event Action? AnswerCall;
    public event Action? EndCall;

    public RedPhoneReportWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _buttonUnlockTime = _timing.CurTime + ButtonUnlockDelay;

        Title = Loc.GetString("red-phone-report-title");
        PromptLabel.Text = WrapCallText(Loc.GetString("red-phone-report-prompt"), 36);

        MessageInput.OnTextChanged += _ => UpdateButtons();
        MessageInput.OnTextEntered += args => TrySubmit(args.Text);

        OkButton.OnPressed += _ => TrySubmit(MessageInput.Text);
        CancelButton.OnPressed += _ => Close();
        AnswerCallButton.OnPressed += _ => AnswerCall?.Invoke();
        EndCallButton.OnPressed += _ => EndCall?.Invoke();

        UpdateButtons();
        UpdateAppearance();
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
        MessageInput.GrabKeyboardFocus();
        UpdateAppearance();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateTimer += args.DeltaSeconds;
        if (_updateTimer < UpdateTime)
            return;

        _updateTimer -= UpdateTime;
        UpdateAppearance();
    }

    private void TrySubmit(string message)
    {
        if (string.IsNullOrWhiteSpace(message))
            return;

        Submit?.Invoke(message.Trim());
    }

    private void UpdateButtons()
    {
        OkButton.Disabled = string.IsNullOrWhiteSpace(MessageInput.Text);
    }

    private void UpdateAppearance()
    {
        if (_owner == null ||
            !_entManager.TryGetComponent<TelephoneComponent>(_owner.Value, out var telephone))
        {
            return;
        }

        CallerIdText.Text = WrapCallText(FormatCallerText(telephone.LastCallerId.Item1, telephone.LastCallerId.Item2));
        DeviceIdText.Text = WrapCallText(FormatDeviceText(telephone.LastCallerId.Item3));

        if (_currentState != telephone.CurrentState)
        {
            _previousState = _currentState;
            _currentState = telephone.CurrentState;
            _buttonUnlockTime = _timing.CurTime + ButtonUnlockDelay;
        }

        var lockButtons = _timing.CurTime < _buttonUnlockTime;
        var canReport = _currentState == TelephoneState.Idle;
        var showCallSection = !canReport;

        CallStatusText.Text = Loc.GetString(_currentState switch
        {
            TelephoneState.Idle => "red-phone-call-window-no-calls",
            TelephoneState.Calling => "red-phone-call-window-outgoing-call",
            TelephoneState.Ringing => "red-phone-call-window-incoming-call",
            TelephoneState.InCall => "red-phone-call-window-call-in-progress",
            TelephoneState.EndingCall => _previousState == TelephoneState.Calling
                ? "red-phone-call-window-call-rejected"
                : "red-phone-call-window-call-ending",
            _ => "red-phone-call-window-no-calls"
        });

        ReportSection.Visible = canReport;
        CallSection.Visible = showCallSection;

        PromptLabel.ModulateSelfOverride = canReport ? null : Color.Gray;
        MessageInput.Editable = canReport;
        MessageInput.ModulateSelfOverride = canReport ? null : Color.Gray;
        OkButton.Disabled = !canReport || string.IsNullOrWhiteSpace(MessageInput.Text);

        CallerIdContainer.Visible = _currentState == TelephoneState.Ringing;
        AnswerCallButton.Visible = _currentState == TelephoneState.Ringing;
        AnswerCallButton.Disabled = _currentState != TelephoneState.Ringing || lockButtons;
        EndCallButton.Disabled = _currentState == TelephoneState.Idle || _currentState == TelephoneState.EndingCall || lockButtons;
    }

    private static string FormatCallerText(string? callerName, string? callerJob)
    {
        if (string.IsNullOrWhiteSpace(callerName))
            return Loc.GetString("red-phone-call-window-unknown-caller");

        var trimmedName = callerName.Trim();
        if (!string.IsNullOrWhiteSpace(callerJob))
        {
            return Loc.GetString("red-phone-call-window-caller-with-job",
                ("name", trimmedName),
                ("job", callerJob.Trim()));
        }

        return Loc.GetString("red-phone-call-window-caller-without-job", ("name", trimmedName));
    }

    private static string FormatDeviceText(string? deviceName)
    {
        if (string.IsNullOrWhiteSpace(deviceName))
            return Loc.GetString("red-phone-call-window-unknown-device");

        return deviceName.Trim();
    }

    private static string WrapCallText(string text, int maxLineLength = 30)
    {
        if (string.IsNullOrWhiteSpace(text))
            return string.Empty;

        var words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (words.Length == 0)
            return string.Empty;

        var builder = new StringBuilder();
        var lineLength = 0;

        foreach (var word in words)
        {
            if (lineLength == 0)
            {
                builder.Append(word);
                lineLength = word.Length;
                continue;
            }

            if (lineLength + 1 + word.Length > maxLineLength)
            {
                builder.Append('\n');
                builder.Append(word);
                lineLength = word.Length;
                continue;
            }

            builder.Append(' ');
            builder.Append(word);
            lineLength += 1 + word.Length;
        }

        return builder.ToString();
    }
}
