// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Globalization;
using System.Linq;
using Content.Client.Administration.Managers;
using Content.Shared.Administration;
using Content.Shared.DeadSpace.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AutoMapVoteConfigControl : Control
{
    [Dependency] private readonly IClientAdminManager _admin = default!;
    [Dependency] private readonly IClientConsoleHost _console = default!;

    private AutoMapVoteAdminState? _state;
    private bool _suppressTextEvents;

    public AutoMapVoteConfigControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _admin.AdminStatusUpdated += RefreshVisibility;

        VoteDurationSeconds.OnTextChanged += _ => OnInputChanged();
        SmallMaxPlayers.OnTextChanged += _ => OnInputChanged();
        MediumMaxPlayers.OnTextChanged += _ => OnInputChanged();
        LargeMaxPlayers.OnTextChanged += _ => OnInputChanged();
        SmallMaps.OnTextChanged += _ => OnInputChanged();
        MediumMaps.OnTextChanged += _ => OnInputChanged();
        LargeMaps.OnTextChanged += _ => OnInputChanged();
        BlacklistMaps.OnTextChanged += _ => OnBlacklistChanged();
        MapSearch.OnTextChanged += _ => OnInputChanged();
        ApplyButton.OnPressed += _ => ApplyConfiguration();

        RefreshVisibility();
        UpdateState(null);
    }

    public void UpdateState(AutoMapVoteAdminState? state)
    {
        _state = state;

        if (!Visible)
            return;

        if (state == null)
        {
            SummaryLabel.Text = Loc.GetString("auto-map-vote-config-loading");
            ApplyStatusLabel.Text = Loc.GetString("auto-map-vote-config-loading");
            ApplyStatusLabel.ModulateSelfOverride = Color.LightGray;
            VoteDurationSeconds.Text = string.Empty;
            BlacklistValidation.Text = Loc.GetString("auto-map-vote-config-blacklist-validation-loading");
            BlacklistPreview.Text = Loc.GetString("auto-map-vote-config-loading");
            SmallValidation.Text = Loc.GetString("auto-map-vote-config-validation-loading");
            MediumValidation.Text = Loc.GetString("auto-map-vote-config-validation-loading");
            LargeValidation.Text = Loc.GetString("auto-map-vote-config-validation-loading");
            BlacklistMapButtons.RemoveAllChildren();
            SmallMapButtons.RemoveAllChildren();
            MediumMapButtons.RemoveAllChildren();
            LargeMapButtons.RemoveAllChildren();
            return;
        }

        var small = GetCategoryStatus(state, AutoMapVoteCategory.Small);
        var medium = GetCategoryStatus(state, AutoMapVoteCategory.Medium);
        var large = GetCategoryStatus(state, AutoMapVoteCategory.Large);

        _suppressTextEvents = true;
        VoteDurationSeconds.Text = state.VoteDurationSeconds.ToString(CultureInfo.InvariantCulture);
        BlacklistMaps.Text = state.Blacklist.MapsCsv;
        SmallMaxPlayers.Text = small.MaxPlayers.ToString(CultureInfo.InvariantCulture);
        MediumMaxPlayers.Text = medium.MaxPlayers.ToString(CultureInfo.InvariantCulture);
        LargeMaxPlayers.Text = large.MaxPlayers.ToString(CultureInfo.InvariantCulture);
        SmallMaps.Text = small.MapsCsv;
        MediumMaps.Text = medium.MapsCsv;
        LargeMaps.Text = large.MapsCsv;
        _suppressTextEvents = false;

        SummaryLabel.Text =
            Loc.GetString("auto-map-vote-config-summary-players", ("players", state.CurrentPlayerCount)) +
            "\n" +
            Loc.GetString("auto-map-vote-config-summary-category", ("category", GetCategoryName(state.CurrentCategory)));
        ApplyStatusLabel.Text = Loc.GetString("auto-map-vote-config-saved");
        ApplyStatusLabel.ModulateSelfOverride = Color.FromHex("#3fb950");

        RefreshPreview();
    }

    private void ApplyConfiguration()
    {
        if (!TryParseVoteDuration(out var voteDurationSeconds))
        {
            ApplyStatusLabel.Text = Loc.GetString("auto-map-vote-config-invalid-duration");
            ApplyStatusLabel.ModulateSelfOverride = Color.FromHex("#f85149");
            return;
        }

        if (!TryParseMaxPlayers(out var smallMax, out var mediumMax, out var largeMax))
        {
            ApplyStatusLabel.Text = Loc.GetString("auto-map-vote-config-invalid-player-count");
            ApplyStatusLabel.ModulateSelfOverride = Color.FromHex("#f85149");
            return;
        }

        if (smallMax < 0 || mediumMax < 0 || largeMax < 0)
        {
            ApplyStatusLabel.Text = Loc.GetString("auto-map-vote-config-invalid-player-count");
            ApplyStatusLabel.ModulateSelfOverride = Color.FromHex("#f85149");
            return;
        }

        var command =
            $"setautomapvoteconfig {smallMax} {mediumMax} {largeMax} " +
            $"\"{CommandParsing.Escape(SmallMaps.Text)}\" " +
            $"\"{CommandParsing.Escape(MediumMaps.Text)}\" " +
            $"\"{CommandParsing.Escape(LargeMaps.Text)}\" " +
            $"\"{CommandParsing.Escape(BlacklistMaps.Text)}\" " +
            $"{voteDurationSeconds.ToString(CultureInfo.InvariantCulture)}";

        _console.ExecuteCommand(command);
        ApplyStatusLabel.Text = Loc.GetString("auto-map-vote-config-applying");
        ApplyStatusLabel.ModulateSelfOverride = Color.FromHex("#58a6ff");
    }

    private bool TryParseVoteDuration(out int voteDurationSeconds)
    {
        var parsedDuration = int.TryParse(VoteDurationSeconds.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out voteDurationSeconds);
        return parsedDuration && voteDurationSeconds > 0;
    }

    private bool TryParseMaxPlayers(out int smallMax, out int mediumMax, out int largeMax)
    {
        var parsedSmall = int.TryParse(SmallMaxPlayers.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out smallMax);
        var parsedMedium = int.TryParse(MediumMaxPlayers.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out mediumMax);
        var parsedLarge = int.TryParse(LargeMaxPlayers.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out largeMax);
        return parsedSmall && parsedMedium && parsedLarge;
    }

    private void RefreshPreview()
    {
        if (!Visible)
            return;

        UpdateBlacklistPreview(
            BlacklistPreview,
            BlacklistValidation,
            BlacklistMapButtons,
            BlacklistMaps.Text,
            _state?.Blacklist);
        UpdateCategoryPreview(
            SmallPreview,
            SmallValidation,
            SmallMapButtons,
            AutoMapVoteCategory.Small,
            SmallMaps.Text,
            _state is null ? null : GetCategoryStatus(_state, AutoMapVoteCategory.Small));
        UpdateCategoryPreview(
            MediumPreview,
            MediumValidation,
            MediumMapButtons,
            AutoMapVoteCategory.Medium,
            MediumMaps.Text,
            _state is null ? null : GetCategoryStatus(_state, AutoMapVoteCategory.Medium));
        UpdateCategoryPreview(
            LargePreview,
            LargeValidation,
            LargeMapButtons,
            AutoMapVoteCategory.Large,
            LargeMaps.Text,
            _state is null ? null : GetCategoryStatus(_state, AutoMapVoteCategory.Large));
    }

    private void UpdateBlacklistPreview(
        Label previewLabel,
        Label validationLabel,
        BoxContainer mapButtons,
        string csv,
        AutoMapVoteBlacklistStatus? savedStatus)
    {
        var ids = ParseMapIds(csv);
        var knownMaps = (_state?.AvailableMaps ?? Array.Empty<AutoMapVoteMapEntry>())
            .ToDictionary(map => map.Id);
        var valid = 0;
        var unknown = new List<string>();

        foreach (var id in ids)
        {
            if (knownMaps.ContainsKey(id))
                valid++;
            else
                unknown.Add(id);
        }

        validationLabel.Text = savedStatus == null
            ? Loc.GetString("auto-map-vote-config-blacklist-validation-loading")
            : Loc.GetString("auto-map-vote-config-blacklist-validation",
                ("valid", savedStatus.ValidMapCount));

        previewLabel.Text = unknown.Count == 0
            ? Loc.GetString("auto-map-vote-config-preview",
                ("configured", ids.Count),
                ("valid", valid))
            : Loc.GetString("auto-map-vote-config-preview-with-unknown",
                ("configured", ids.Count),
                ("valid", valid),
                ("unknown", string.Join(", ", unknown)));

        previewLabel.ModulateSelfOverride = unknown.Count == 0
            ? Color.LightGray
            : Color.FromHex("#f0883e");

        RebuildMapRows(
            mapButtons,
            GetFilteredMaps(includeBlacklisted: true),
            ids,
            AutoMapVoteMapListKind.Blacklist);
    }

    private void UpdateCategoryPreview(
        Label previewLabel,
        Label validationLabel,
        BoxContainer mapButtons,
        AutoMapVoteCategory category,
        string csv,
        AutoMapVoteCategoryStatus? savedStatus)
    {
        var ids = ParseMapIds(csv);
        var knownMaps = (_state?.AvailableMaps ?? Array.Empty<AutoMapVoteMapEntry>())
            .ToDictionary(map => map.Id);
        var valid = 0;
        var unknown = new List<string>();

        foreach (var id in ids)
        {
            if (knownMaps.ContainsKey(id))
                valid++;
            else
                unknown.Add(id);
        }

        validationLabel.Text = savedStatus == null
            ? Loc.GetString("auto-map-vote-config-validation-loading")
            : Loc.GetString("auto-map-vote-config-validation",
                ("valid", savedStatus.ValidMapCount),
                ("eligible", savedStatus.EligibleMapCount));

        previewLabel.Text = unknown.Count == 0
            ? Loc.GetString("auto-map-vote-config-preview",
                ("configured", ids.Count),
                ("valid", valid))
            : Loc.GetString("auto-map-vote-config-preview-with-unknown",
                ("configured", ids.Count),
                ("valid", valid),
                ("unknown", string.Join(", ", unknown)));

        previewLabel.ModulateSelfOverride = unknown.Count == 0
            ? Color.LightGray
            : Color.FromHex("#f0883e");

        RebuildMapRows(
            mapButtons,
            GetFilteredMaps(includeBlacklisted: false),
            ids,
            AutoMapVoteMapListKind.Pool,
            category);
    }

    private static AutoMapVoteCategoryStatus GetCategoryStatus(AutoMapVoteAdminState state, AutoMapVoteCategory category)
    {
        return state.Categories.First(status => status.Category == category);
    }

    private static string GetCategoryName(AutoMapVoteCategory category)
    {
        return category switch
        {
            AutoMapVoteCategory.Small => Loc.GetString("auto-map-vote-category-small"),
            AutoMapVoteCategory.Medium => Loc.GetString("auto-map-vote-category-medium"),
            _ => Loc.GetString("auto-map-vote-category-large")
        };
    }

    private void RebuildMapRows(
        BoxContainer container,
        AutoMapVoteMapEntry[] maps,
        List<string> selectedIds,
        AutoMapVoteMapListKind kind,
        AutoMapVoteCategory? category = null)
    {
        container.RemoveAllChildren();

        var selected = selectedIds.ToHashSet();

        if (maps.Length == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("auto-map-vote-config-map-picker-empty"),
                ModulateSelfOverride = Color.LightGray
            });
            return;
        }

        foreach (var map in maps)
        {
            var rowPanel = new PanelContainer
            {
                StyleClasses = { "PanelDark" },
                HorizontalExpand = true
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(8, 6, 8, 6),
                SeparationOverride = 8,
                HorizontalExpand = true
            };

            var info = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true
            };

            info.AddChild(new Label
            {
                Text = map.Name,
                ClipText = true,
                HorizontalExpand = true
            });

            var stateText = Loc.GetString(map.Blacklisted
                ? "auto-map-vote-config-map-blacklisted"
                : "auto-map-vote-config-map-eligible");

            info.AddChild(new Label
            {
                Text = $"{map.Id} · {stateText}",
                ClipText = true,
                HorizontalExpand = true,
                StyleClasses = { "LabelSubText" },
                FontColorOverride = map.Blacklisted ? Color.FromHex("#8b949e") : Color.LightGray
            });

            var button = new Button
            {
                ToggleMode = true,
                Pressed = selected.Contains(map.Id),
                MinWidth = 120,
                ClipText = true,
                ToolTip = Loc.GetString("auto-map-vote-config-map-button-tooltip",
                    ("id", map.Id),
                    ("status", stateText))
            };

            UpdateMapActionButton(button, kind, button.Pressed);
            button.OnToggled += args =>
            {
                UpdateMapActionButton((Button) args.Button, kind, args.Pressed);

                if (kind == AutoMapVoteMapListKind.Blacklist)
                {
                    ToggleBlacklist(map.Id, args.Pressed);
                    return;
                }

                if (category != null)
                    ToggleMap(category.Value, map.Id, args.Pressed);
            };

            row.AddChild(info);
            row.AddChild(button);
            rowPanel.AddChild(row);
            container.AddChild(rowPanel);
        }
    }

    private void ToggleMap(AutoMapVoteCategory category, string mapId, bool selected)
    {
        ToggleMapInLineEdit(GetMapsLineEdit(category), mapId, selected);
    }

    private void ToggleBlacklist(string mapId, bool selected)
    {
        ToggleMapInLineEdit(BlacklistMaps, mapId, selected);

        if (selected)
            SanitizeCategoryInputsByBlacklist();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _admin.AdminStatusUpdated -= RefreshVisibility;
    }

    private void RefreshVisibility()
    {
        Visible = _admin.HasFlag(AdminFlags.Server);

        if (Visible)
            UpdateState(_state);
    }

    private void OnInputChanged()
    {
        if (_suppressTextEvents)
            return;

        RefreshPreview();
    }

    private void OnBlacklistChanged()
    {
        if (_suppressTextEvents)
            return;

        SanitizeCategoryInputsByBlacklist();
        RefreshPreview();
    }

    private void SanitizeCategoryInputsByBlacklist()
    {
        var blacklisted = GetBlacklistedIds();

        SanitizeLineEditByBlacklist(SmallMaps, blacklisted);
        SanitizeLineEditByBlacklist(MediumMaps, blacklisted);
        SanitizeLineEditByBlacklist(LargeMaps, blacklisted);
    }

    private void SanitizeLineEditByBlacklist(LineEdit lineEdit, HashSet<string> blacklisted)
    {
        var ids = ParseMapIds(lineEdit.Text);
        ids.RemoveAll(blacklisted.Contains);
        SetLineEditIds(lineEdit, ids);
    }

    private void ToggleMapInLineEdit(LineEdit lineEdit, string mapId, bool selected)
    {
        var ids = ParseMapIds(lineEdit.Text);

        if (selected)
        {
            if (!ids.Contains(mapId))
                ids.Add(mapId);
        }
        else
        {
            ids.RemoveAll(id => id == mapId);
        }

        SetLineEditIds(lineEdit, ids);
    }

    private static void SetLineEditIds(LineEdit lineEdit, List<string> ids)
    {
        var joined = string.Join(", ", ids);

        if (lineEdit.Text == joined)
            return;

        lineEdit.Text = joined;
    }

    private AutoMapVoteMapEntry[] GetFilteredMaps(bool includeBlacklisted)
    {
        if (_state == null)
            return Array.Empty<AutoMapVoteMapEntry>();

        var search = MapSearch.Text.Trim();
        var blacklisted = GetBlacklistedIds();

        return _state.AvailableMaps
            .Where(map => includeBlacklisted || !blacklisted.Contains(map.Id))
            .Where(map =>
                string.IsNullOrWhiteSpace(search) ||
                map.Name.Contains(search, StringComparison.CurrentCultureIgnoreCase) ||
                map.Id.Contains(search, StringComparison.OrdinalIgnoreCase))
            .ToArray();
    }

    private HashSet<string> GetBlacklistedIds()
    {
        return ParseMapIds(BlacklistMaps.Text).ToHashSet();
    }

    private static void UpdateMapActionButton(Button button, AutoMapVoteMapListKind kind, bool selected)
    {
        if (kind == AutoMapVoteMapListKind.Blacklist)
        {
            button.Text = Loc.GetString(selected
                ? "auto-map-vote-config-blacklist-remove"
                : "auto-map-vote-config-blacklist-add");
            button.ModulateSelfOverride = selected
                ? Color.FromHex("#f85149")
                : Color.FromHex("#f0883e");
            return;
        }

        button.Text = Loc.GetString(selected
            ? "auto-map-vote-config-map-remove"
            : "auto-map-vote-config-map-add");
        button.ModulateSelfOverride = selected
            ? Color.FromHex("#f0883e")
            : Color.FromHex("#2ea043");
    }

    private LineEdit GetMapsLineEdit(AutoMapVoteCategory category)
    {
        return category switch
        {
            AutoMapVoteCategory.Small => SmallMaps,
            AutoMapVoteCategory.Medium => MediumMaps,
            _ => LargeMaps
        };
    }

    private static List<string> ParseMapIds(string csv)
    {
        var result = new List<string>();
        var seen = new HashSet<string>();

        foreach (var entry in csv.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries))
        {
            if (!seen.Add(entry))
                continue;

            result.Add(entry);
        }

        return result;
    }

    private enum AutoMapVoteMapListKind
    {
        Pool,
        Blacklist
    }
}
