// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.Administration.Managers;
using Content.Shared.Administration;
using Content.Shared.DeadSpace.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AutoMapVoteRoundControl : Control
{
    [Dependency] private readonly IClientAdminManager _admin = default!;
    [Dependency] private readonly IClientConsoleHost _console = default!;
    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    private AutoMapVoteAdminState? _state;
    private RoundGameModeHistoryWindow? _gameModeHistoryWindow;

    public AutoMapVoteRoundControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _admin.AdminStatusUpdated += RefreshVisibility;
        StartVoteButton.OnPressed += _ => _console.ExecuteCommand("initautomapvote");
        ToggleButton.OnPressed += _ => _console.ExecuteCommand("toggleautomapvote");
        GameModeHistoryButton.OnPressed += _ => OpenGameModeHistoryWindow();

        RefreshVisibility();
        UpdateState(null);
    }

    public void UpdateState(AutoMapVoteAdminState? state)
    {
        _state = state;

        if (!Visible)
            return;

        if (state == null)
        {
            StateBadge.Text = Loc.GetString("auto-map-vote-round-state-loading");
            StateBadge.ModulateSelfOverride = Color.LightGray;
            StatusLabel.Text = Loc.GetString("auto-map-vote-round-state-loading");
            CategoryLabel.Text = Loc.GetString("auto-map-vote-round-category-loading");
            HintLabel.Text = Loc.GetString("auto-map-vote-round-hint");
            StartVoteButton.Text = Loc.GetString("auto-map-vote-round-start");
            StartVoteButton.ModulateSelfOverride = Color.FromHex("#1f6feb");
            StartVoteButton.Disabled = true;
            ToggleButton.Text = Loc.GetString("auto-map-vote-round-toggle-loading");
            ToggleButton.ModulateSelfOverride = null;
            ToggleButton.Disabled = true;
            return;
        }

        var enabled = state.Enabled;
        var blocked = enabled && state.VoteBlocked;
        StateBadge.Text = Loc.GetString(!enabled
            ? "auto-map-vote-round-state-disabled-short"
            : blocked
                ? "auto-map-vote-round-state-blocked-short"
                : "auto-map-vote-round-state-enabled-short");
        StateBadge.ModulateSelfOverride = !enabled
            ? Color.FromHex("#f85149")
            : blocked
                ? Color.FromHex("#f0883e")
                : Color.FromHex("#3fb950");

        StatusLabel.Text = Loc.GetString(!enabled
            ? "auto-map-vote-round-state-disabled"
            : blocked
                ? "auto-map-vote-round-state-blocked"
                : "auto-map-vote-round-state-enabled");
        StatusLabel.ModulateSelfOverride = !enabled
            ? Color.FromHex("#f85149")
            : blocked
                ? Color.FromHex("#f0883e")
                : Color.FromHex("#3fb950");

        CategoryLabel.Text = GetCategoryName(state.CurrentCategory);
        HintLabel.Text = Loc.GetString(blocked
            ? "auto-map-vote-round-hint-blocked"
            : "auto-map-vote-round-hint");
        StartVoteButton.Text = Loc.GetString("auto-map-vote-round-start");
        StartVoteButton.ModulateSelfOverride = Color.FromHex("#1f6feb");
        StartVoteButton.Disabled = state.VoteActive || state.VoteBlocked;
        ToggleButton.Text = Loc.GetString(enabled
            ? "auto-map-vote-round-toggle-disable"
            : "auto-map-vote-round-toggle-enable");
        ToggleButton.ModulateSelfOverride = enabled ? Color.FromHex("#f0883e") : Color.FromHex("#2ea043");
        ToggleButton.Disabled = false;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            _admin.AdminStatusUpdated -= RefreshVisibility;

            if (_gameModeHistoryWindow is { Disposed: false })
                _gameModeHistoryWindow.Dispose();
        }
    }

    private void RefreshVisibility()
    {
        Visible = _admin.HasFlag(AdminFlags.Round);

        if (Visible)
            UpdateState(_state);
        else if (_gameModeHistoryWindow is { IsOpen: true })
            _gameModeHistoryWindow.Close();
    }

    private void OpenGameModeHistoryWindow()
    {
        if (_gameModeHistoryWindow is not { Disposed: false })
            _gameModeHistoryWindow = _ui.CreateWindow<RoundGameModeHistoryWindow>();

        _gameModeHistoryWindow.OpenCentered();
        _gameModeHistoryWindow.MoveToFront();
    }

    private static string GetCategoryName(AutoMapVoteCategory category)
    {
        return category switch
        {
            AutoMapVoteCategory.Small => Loc.GetString("auto-map-vote-category-small"),
            AutoMapVoteCategory.Medium => Loc.GetString("auto-map-vote-category-medium"),
            _ => Loc.GetString("auto-map-vote-category-large")
        };
    }
}
