// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.DeadSpace.Administration;
using Content.Shared.DeadSpace.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class RoundGameModeHistoryWindow : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    private readonly RoundGameModeHistorySystem _history;

    public RoundGameModeHistoryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _history = _entitySystem.GetEntitySystem<RoundGameModeHistorySystem>();
        HistoryTabs.SetTabTitle(0, Loc.GetString("round-game-mode-history-tab-today"));
        HistoryTabs.SetTabTitle(1, Loc.GetString("round-game-mode-history-tab-yesterday"));
        HistoryTabs.SetTabTitle(2, Loc.GetString("round-game-mode-history-tab-before-yesterday"));

        RefreshButton.OnPressed += OnRefreshPressed;
        _history.HistoryUpdated += UpdateHistory;
        _history.RequestHistory();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            RefreshButton.OnPressed -= OnRefreshPressed;
            _history.HistoryUpdated -= UpdateHistory;
        }

        base.Dispose(disposing);
    }

    private void OnRefreshPressed(BaseButton.ButtonEventArgs _)
    {
        _history.RequestHistory();
    }

    private void UpdateHistory()
    {
        TodayEntriesContainer.RemoveAllChildren();
        YesterdayEntriesContainer.RemoveAllChildren();
        BeforeYesterdayEntriesContainer.RemoveAllChildren();

        var entries = _history.Entries;
        if (entries == null)
        {
            StatusLabel.Text = Loc.GetString("round-game-mode-history-loading");
            AddStatusToAllTabs("round-game-mode-history-loading");
            return;
        }

        if (entries.Length == 0)
        {
            StatusLabel.Text = Loc.GetString("round-game-mode-history-empty");
            AddEmptyStateToTabs();
            return;
        }

        StatusLabel.Text = Loc.GetString("round-game-mode-history-summary", ("count", entries.Length));

        AddEntries(TodayEntriesContainer, entries, 0);
        AddEntries(YesterdayEntriesContainer, entries, 1);
        AddEntries(BeforeYesterdayEntriesContainer, entries, 2);
    }

    private static void AddEntries(BoxContainer container, RoundGameModeHistoryEntry[] entries, int dayOffset)
    {
        var found = false;
        foreach (var entry in entries)
        {
            if (entry.DayOffset != dayOffset)
                continue;

            found = true;
            container.AddChild(new Label
            {
                Text = FormatEntry(entry),
                HorizontalExpand = true
            });
        }

        if (!found)
            AddStatus(container, "round-game-mode-history-empty-tab");
    }

    private void AddStatusToAllTabs(string locId)
    {
        AddStatus(TodayEntriesContainer, locId);
        AddStatus(YesterdayEntriesContainer, locId);
        AddStatus(BeforeYesterdayEntriesContainer, locId);
    }

    private void AddEmptyStateToTabs()
    {
        AddStatus(TodayEntriesContainer, "round-game-mode-history-empty-tab");
        AddStatus(YesterdayEntriesContainer, "round-game-mode-history-empty-tab");
        AddStatus(BeforeYesterdayEntriesContainer, "round-game-mode-history-empty-tab");
    }

    private static void AddStatus(BoxContainer container, string locId)
    {
        container.AddChild(new Label
        {
            Text = Loc.GetString(locId),
            StyleClasses = { "LabelSubText" },
            HorizontalExpand = true
        });
    }

    private static string FormatEntry(RoundGameModeHistoryEntry entry)
    {
        if (entry.PlayerCount < 0 || string.IsNullOrWhiteSpace(entry.MapName))
        {
            return Loc.GetString(
                "round-game-mode-history-row",
                ("round", entry.RoundId),
                ("started", entry.StartedAt),
                ("mode", entry.GameMode));
        }

        return Loc.GetString(
            "round-game-mode-history-row-with-details",
            ("round", entry.RoundId),
            ("started", entry.StartedAt),
            ("mode", entry.GameMode),
            ("map", entry.MapName),
            ("players", entry.PlayerCount));
    }
}
