using System.Linq;
using Content.Client.DeadSpace.Stylesheets;
using Content.Client.Stylesheets.Palette;
using Content.Shared.DeadSpace.AppHub;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.DeadSpace.AppHub;

[GenerateTypedNameReferences]
public sealed partial class AppHubMenu : DefaultWindow
{
    public event Action<string>? OnInstallPressed;
    public event Action<string>? OnUninstallPressed;
    public event Action<string>? OnCategorySelected;
    public event Action? OnEjectPdaPressed;

    private string _currentCategory = "All";

    public AppHubMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CategoryAll.OnPressed += _ => SetCategory("All");
        CategoryTools.OnPressed += _ => SetCategory("Tools");
        CategoryEquipment.OnPressed += _ => SetCategory("Equipment");
        CategoryGames.OnPressed += _ => SetCategory("Games");
        EjectPdaButton.OnPressed += _ => OnEjectPdaPressed?.Invoke();
    }

    public void UpdateState(AppHubUiState state)
    {
        _currentCategory = state.SelectedCategory;

        StatusNetwork.Text = "Сеть: Подключено";
        StatusPda.Text = state.HasPda ? "КПК подключён" : "Нет КПК";
        StatusPda.FontColorOverride = state.HasPda ? Palettes.Green.Text : Palettes.Red.Text;

        MemoryLabel.Text = $"Память: {state.UsedDiskSpace}/{state.MaxDiskSpace}";
        MemoryBar.MaxValue = Math.Max(state.MaxDiskSpace, 1);
        MemoryBar.Value = state.UsedDiskSpace;

        NoPdaLabel.Visible = !state.HasPda;
        EjectPdaButton.Visible = state.HasPda;

        UpdateCategoryButtons();
        PopulateProgramList(state.CatalogEntries, state.HasPda);
    }

    private void SetCategory(string category)
    {
        _currentCategory = category;
        OnCategorySelected?.Invoke(category);
    }

    private void UpdateCategoryButtons()
    {
        var buttons = new[] { ("All", CategoryAll), ("Tools", CategoryTools), ("Equipment", CategoryEquipment), ("Games", CategoryGames) };
        foreach (var (cat, btn) in buttons)
        {
            btn.Modulate = cat == _currentCategory ? DeadSpaceStylePalette.CyanBright : Color.White;
        }
    }

    private void PopulateProgramList(List<AppHubCatalogEntry> entries, bool hasPda)
    {
        ProgramListContainer.RemoveAllChildren();

        if (entries.Count == 0)
        {
            ProgramListContainer.AddChild(new Label
            {
                Text = Loc.GetString("app-hub-no-programs"),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                VerticalExpand = true,
            });
            return;
        }

        foreach (var entry in entries.OrderBy(e => e.Name))
        {
            var card = new PanelContainer
            {
                HorizontalExpand = true,
                Margin = new Thickness(2),
                StyleClasses = { DeadSpaceStyleClass.ListItem },
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(6, 4),
                SeparationOverride = 8,
            };

            var infoColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = true,
                SeparationOverride = 2,
            };

            var nameLabel = new Label
            {
                Text = entry.Name,
                StyleClasses = { "LabelBig" },
                HorizontalExpand = true,
            };
            infoColumn.AddChild(nameLabel);

            var descLabel = new Label
            {
                Text = entry.Description,
                StyleClasses = { DeadSpaceStyleClass.Subtitle },
                HorizontalExpand = true,
            };
            infoColumn.AddChild(descLabel);

            row.AddChild(infoColumn);

            var actionButton = new Button
            {
                MinWidth = 100,
                VerticalAlignment = VAlignment.Center,
            };

            if (!hasPda)
            {
                actionButton.Text = "Нет доступа";
                actionButton.Disabled = true;
            }
            else if (entry.IsInstalled)
            {
                actionButton.Text = "Удалить";
                var capturedId = entry.Id;
                actionButton.OnPressed += _ => OnUninstallPressed?.Invoke(capturedId);
            }
            else
            {
                actionButton.Text = "Загрузить";
                var capturedId = entry.Id;
                actionButton.OnPressed += _ => OnInstallPressed?.Invoke(capturedId);
            }

            row.AddChild(actionButton);
            card.AddChild(row);
            ProgramListContainer.AddChild(card);
        }
    }
}
