using System.Numerics;
using Content.Client.DeadSpace.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaNavigationButton : ContainerButton
{

    private bool _isCurrent;
    private bool _isActive = true;

    private Thickness _borderThickness = new(0, 0, 0, 2);
    private Thickness _currentTabBorderThickness = new(2, 0, 2, 0);

    // DS14-start
    private readonly StyleBoxFlat _styleBox = new()
    {
        BorderThickness = new Thickness(0, 0, 0, 2)
    };

    private Color? _inactiveBgColor;
    private Color? _activeBgColor;
    private Color? _inactiveFgColor;
    private Color? _activeFgColor;

    public Color InactiveBgColor
    {
        get => _inactiveBgColor ?? DefaultInactiveBgColor;
        set
        {
            _inactiveBgColor = value;
            UpdateVisuals();
        }
    }

    public Color ActiveBgColor
    {
        get => _activeBgColor ?? DefaultActiveBgColor;
        set
        {
            _activeBgColor = value;
            UpdateVisuals();
        }
    }

    public Color InactiveFgColor
    {
        get => _inactiveFgColor ?? DefaultInactiveFgColor;
        set
        {
            _inactiveFgColor = value;
            UpdateVisuals();
        }
    }

    public Color ActiveFgColor
    {
        get => _activeFgColor ?? DefaultActiveFgColor;
        set
        {
            _activeFgColor = value;
            UpdateVisuals();
        }
    }

    private static Color DefaultInactiveBgColor => DeadSpaceStylePalette.ClassicChrome
        ? Color.FromHex("#202023")
        : DeadSpaceStylePalette.Control;

    private static Color DefaultActiveBgColor => DeadSpaceStylePalette.ClassicChrome
        ? Color.FromHex("#25252A")
        : DeadSpaceStylePalette.ListItemPressed;

    private static Color DefaultInactiveFgColor => DeadSpaceStylePalette.ClassicChrome
        ? Color.FromHex("#5A5A5A")
        : DeadSpaceStylePalette.TextInactive;

    private static Color DefaultActiveFgColor => DeadSpaceStylePalette.ClassicChrome
        ? Color.White
        : DeadSpaceStylePalette.Text;
    // DS14-end

    public SpriteSpecifier? IconTexture
    {
        set
        {
            Icon.Visible = value != null;
            Label.Visible = value == null;

            if (value is not null)
                Icon.SetFromSpriteSpecifier(value);
        }
    }

    public Vector2 IconScale
    {
        get => Icon.DisplayRect.TextureScale;
        set => Icon.DisplayRect.TextureScale = value;
    }

    public string? LabelText
    {
        get => Label.Text;
        set => Label.Text = value;
    }

    /// <summary>
    /// Sets the border thickness when the tab is not the currently active one
    /// </summary>
    public Thickness BorderThickness
    {
        get => _borderThickness;
        set
        {
            _borderThickness = value;
            _styleBox.BorderThickness = _isCurrent ? _currentTabBorderThickness : value;
        }
    }

    /// <summary>
    /// Sets the border thickness when this tab is the currently active tab
    /// </summary>
    public Thickness CurrentTabBorderThickness
    {
        get => _currentTabBorderThickness;
        set
        {
            _currentTabBorderThickness = value;
            _styleBox.BorderThickness = _isCurrent ? value : _borderThickness;
        }
    }

    public bool IsCurrent
    {
        get => _isCurrent;
        set
        {
            _isCurrent = value;
            UpdateVisuals(); // DS14
        }
    }

    public bool IsActive
    {
        get => _isActive;
        set
        {
            _isActive = value;
            UpdateVisuals(); // DS14
        }
    }

    public PdaNavigationButton()
    {
        RobustXamlLoader.Load(this);
        Background.PanelOverride = _styleBox;
        UpdateVisuals(); // DS14
    }

    // DS14-start
    protected override void StylePropertiesChanged()
    {
        base.StylePropertiesChanged();
        UpdateVisuals();
    }

    private void UpdateVisuals()
    {
        _styleBox.BackgroundColor = _isCurrent ? ActiveBgColor : InactiveBgColor;
        _styleBox.BorderColor = DeadSpaceStylePalette.ClassicChrome
            ? Color.FromHex("#5A5A5A")
            : DeadSpaceStylePalette.CyanDim;
        _styleBox.BorderThickness = _isCurrent ? CurrentTabBorderThickness : BorderThickness;

        if (Icon == null || Label == null)
            return;

        var foreground = _isActive ? ActiveFgColor : InactiveFgColor;
        Icon.Modulate = foreground;
        Label.FontColorOverride = foreground;
    }
    // DS14-end
}
