// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Shared.DeadSpace.ERT;
using Content.Shared.DeadSpace.ERT.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.DeadSpace.ERT.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ErtResponseConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IPrototypeManager _prototype = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;

        private ErtResponseConsoleBoundUserInterfaceState? _lastUpdate;
        private readonly List<ErtTeamPrototype> _availableTeams = new();

        public ErtResponseConsoleWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            AvailableTeamsList.OnItemSelected += OnAvailableTeamsSelected;
        }

        public void Populate(ErtResponseConsoleBoundUserInterfaceState state)
        {
            _lastUpdate = state;

            AvailableTeamsList.Clear();
            _availableTeams.Clear();

            var ertSystem = _entityManager.System<ErtResponseSystem>();

            BalanceLabel.Text = Loc.GetString(
                "ert-response-balance-label",
                ("cost", state.Money));

            AuthorizationLabel.Visible = !state.IsAuthorized;
            AuthorizationLabel.Text = state.AuthorizationMessage ?? string.Empty;

            foreach (var team in state.Teams)
            {
                var price = ertSystem.GetErtPrice(team);

                if (!_prototype.TryIndex(team, out var prototype))
                    continue;

                AvailableTeamsList.AddItem(
                    $"{prototype.Name} ({price})",
                    metadata: team.ToString());

                _availableTeams.Add(prototype);
            }

            TeamDescriptionLabel.Text = string.Empty;
            ResponseTeamButton.Disabled = !state.IsAuthorized;
        }

        private void OnAvailableTeamsSelected(ItemList.ItemListSelectedEventArgs args)
        {
            if (_lastUpdate == null || args.ItemIndex < 0)
            {
                ResponseTeamButton.Disabled = true;
                TeamDescriptionLabel.Text = string.Empty;
                return;
            }

            var selectedTeam = _availableTeams[args.ItemIndex];
            TeamDescriptionLabel.Text = selectedTeam.Description;

            var ertSystem = _entityManager.System<ErtResponseSystem>();
            var price = ertSystem.GetErtPrice(selectedTeam.ID);

            ResponseTeamButton.Disabled = !_lastUpdate.IsAuthorized || _lastUpdate.Money < price;
        }
    }
}
