using System.Linq;
using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _protomanager = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        private readonly Button _createNewCharacterButton;
        private readonly HumanoidProfileEditor _profileEditor; // DS14

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _profileEditor = profileEditor; // DS14

            _createNewCharacterButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-button"),
                // DS14-start
                ClipText = true,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Stretch,
                StyleClasses = { "DS14MenuProfileControl" },
                // DS14-end
            };

            _createNewCharacterButton.OnPressed += args =>
            {
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());
                ReloadCharacterPickers();
                args.Event.Handle();
            };

            CharEditor.AddChild(profileEditor);
            RulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();

            StatsButton.OnPressed += _ => new PlaytimeStatsWindow().OpenCentered();

            _cfg.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            _createNewCharacterButton.Orphan();
            Characters.RemoveAllChildren();
            // DS14-start
            InaccessibleCharacters.RemoveAllChildren();
            InaccessibleCharactersHeader.Visible = false;
            InaccessibleCharacters.Visible = false;
            // DS14-end

            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            _createNewCharacterButton.ToolTip =
                Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                    ("maxCharacters", _preferencesManager.Settings!.MaxCharacterSlots));

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;

            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters.OrderBy(p => p.Key)) // DS14
            {
                numberOfFullSlots++;
                var characterPickerButton = new CharacterPickerButton(_entManager,
                    _protomanager,
                    characterButtonsGroup,
                    character,
                    slot == selectedSlot);

                Characters.AddChild(characterPickerButton);

                characterPickerButton.OnPressed += args =>
                {
                    SelectCharacter?.Invoke(slot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };
            }
            // DS14-start
            foreach (var (slot, character) in _preferencesManager.Preferences.InaccessibleCharacters.OrderBy(p => p.Key))
            {
                InaccessibleCharactersHeader.Visible = true;
                InaccessibleCharacters.Visible = true;

                var characterPickerButton = new CharacterPickerButton(_entManager,
                    _protomanager,
                    null,
                    character,
                    false,
                    true);

                InaccessibleCharacters.AddChild(characterPickerButton);

                characterPickerButton.OnPressed += args =>
                {
                    if (character is HumanoidCharacterProfile humanoid)
                        _profileEditor.SetProfile(humanoid, slot, true);

                    args.Event.Handle();
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };
            }
            // DS14-end

            _createNewCharacterButton.Disabled = numberOfFullSlots >= _preferencesManager.Settings.MaxCharacterSlots;
            Characters.AddChild(_createNewCharacterButton);
        }
    }
}
