// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Administration.Managers;
using Content.Client.DeadSpace.Administration.GameRules;
using Content.Shared.Administration;
using Content.Shared.DeadSpace.Administration.GameRules;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.GameRules;

[GenerateTypedNameReferences]
public sealed partial class GameRulesWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IClientAdminManager _adminManager = default!;

    private GameRulesClientSystem _system = default!;
    private string? _selectedRuleId;
    private Button? _selectedButton;
    private readonly Dictionary<Button, string> _ruleButtons = new();

    private List<GameRuleCategoryPrototype> _categories = new();

    private bool _roundActive;
    private TimeSpan _lastRoundDuration;
    private TimeSpan _lastServerUpdateTime;
    private TimeSpan _updateAccumulator;

    public GameRulesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _system = _entityManager.System<GameRulesClientSystem>();
        _system.RulesUpdated += OnRulesUpdated;

        ShowIdCheckBox.OnToggled += _ =>
        {
            UpdateButtonTexts(ShowIdCheckBox.Pressed);
        };

        LoadCategories();
        BuildCategoryTabs();

        AddRuleButton.OnPressed += _ =>
        {
            if (!_adminManager.HasFlag(AdminFlags.Fun))
                return;

            if (_selectedRuleId != null && _prototypeManager.HasIndex<EntityPrototype>(_selectedRuleId))
            {
                _system.AddRule(_selectedRuleId);
                _selectedRuleId = null;
                if (_selectedButton != null)
                {
                    _selectedButton.Pressed = false;
                    _selectedButton = null;
                }
                _system.RequestRules();
            }
        };

        _adminManager.AdminStatusUpdated += UpdateButtonStates;
        UpdateButtonStates();
    }

    private void LoadCategories()
    {
        _categories = _prototypeManager.EnumeratePrototypes<GameRuleCategoryPrototype>()
            .OrderBy(c => c.Order)
            .ToList();
    }

    protected override void Opened()
    {
        base.Opened();
        _system.RequestRules();
        _updateAccumulator = TimeSpan.Zero;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var delta = TimeSpan.FromSeconds(args.DeltaSeconds);
        _updateAccumulator += delta;

        if (_updateAccumulator < TimeSpan.FromSeconds(1))
            return;

        _updateAccumulator = TimeSpan.Zero;
        UpdateRoundTimeDisplay();
        _system.RequestRules();
    }

    public override void Close()
    {
        base.Close();
        _adminManager.AdminStatusUpdated -= UpdateButtonStates;
        _system.RulesUpdated -= OnRulesUpdated;
        _system = null!;
    }

    private void UpdateButtonStates()
    {
        var canAdd = _adminManager.HasFlag(AdminFlags.Fun);
        AddRuleButton.Disabled = !canAdd;
    }

    private void OnRulesUpdated(GameRulesListResponseMessage msg)
    {
        _roundActive = msg.RoundActive;
        if (_roundActive)
        {
            _lastRoundDuration = msg.RoundDuration;
            _lastServerUpdateTime = DateTime.Now.TimeOfDay;
        }
        UpdateRoundTimeDisplay();

        RulesList.RemoveAllChildren();
        foreach (var entry in msg.Entries)
        {
            var formattedTime = entry.Time.ToString(@"hh\:mm\:ss");
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6
            };
            row.AddChild(new Label { Text = $"[{formattedTime}] {entry.RuleName}" });
            if (!string.IsNullOrEmpty(entry.AddedByAdmin))
            {
                row.AddChild(new Label
                {
                    Text = $"by {entry.AddedByAdmin}",
                    FontColorOverride = Color.FromHex("#f1c40f")
                });
            }
            RulesList.AddChild(row);
        }
    }

    private void UpdateRoundTimeDisplay()
    {
        if (!_roundActive)
        {
            RoundTimeLabel.Text = Loc.GetString("admin-game-rules-round-not-started");
            return;
        }

        var now = DateTime.Now.TimeOfDay;
        var elapsed = _lastRoundDuration + (now - _lastServerUpdateTime);
        if (elapsed < TimeSpan.Zero)
            elapsed = TimeSpan.Zero;

        RoundTimeLabel.Text = Loc.GetString("admin-game-rules-round-time",
            ("hours", elapsed.Hours.ToString("D2")),
            ("minutes", elapsed.Minutes.ToString("D2")),
            ("seconds", elapsed.Seconds.ToString("D2")));
    }

    private void BuildCategoryTabs()
    {
        CategoryTabs.RemoveAllChildren();
        var showId = ShowIdCheckBox.Pressed;

        foreach (var category in _categories)
        {
            var tabContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 4,
                Margin = new Thickness(4)
            };
            var scroll = new ScrollContainer
            {
                VerticalExpand = true,
                Children = { tabContainer }
            };

            CategoryTabs.AddChild(scroll);
            CategoryTabs.SetTabTitle(CategoryTabs.ChildCount - 1, Loc.GetString(category.Name));

            foreach (var ruleId in category.Rules)
            {
                var displayName = showId
                    ? ruleId
                    : _prototypeManager.Index<GameRuleDisplayNamePrototype>(ruleId).Name;

                var exists = _prototypeManager.HasIndex<EntityPrototype>(ruleId);
                var button = new Button
                {
                    Text = displayName,
                    ToggleMode = true,
                    HorizontalExpand = true
                };
                if (!exists)
                    button.ModulateSelfOverride = Color.FromHex("#f85149");

                _ruleButtons[button] = ruleId;
                button.OnToggled += args =>
                {
                    if (args.Pressed)
                    {
                        var rule = _ruleButtons[(Button) args.Button];
                        if (_selectedRuleId != rule)
                        {
                            if (_selectedButton != null)
                                _selectedButton.Pressed = false;
                            _selectedButton = (Button) args.Button;
                            _selectedRuleId = rule;
                        }
                    }
                    else
                    {
                        var rule = _ruleButtons[(Button) args.Button];
                        if (_selectedRuleId == rule)
                        {
                            _selectedRuleId = null;
                            _selectedButton = null;
                        }
                    }
                };
                tabContainer.AddChild(button);
            }
        }
    }
    private void UpdateButtonTexts(bool showId)
    {
        foreach (var (button, ruleId) in _ruleButtons)
        {
            button.Text = showId
                ? ruleId
                : _prototypeManager.Index<GameRuleDisplayNamePrototype>(ruleId).Name;
        }
    }
}
