using Content.Client.Pinpointer.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Utility;
using Content.Shared.DeadSpace.StationAi;
using Content.Shared.DeadSpace.StationAI.UI;

namespace Content.Client.DeadSpace.StationAI.UI;

[GenerateTypedNameReferences]
public sealed partial class AICameraList : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action<NetEntity>? WarpToCamera;
    public event Action<string, AiCameraSearchType>? SearchRequested;
    public event Action<NetEntity>? WarpToTarget;

    private readonly EntityUid _owner;

    public AICameraList(EntityUid? mapUid, EntityUid? trackedEntity)
    {
        _owner = trackedEntity ?? EntityUid.Invalid;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        NavMapScreen.MapUid = mapUid;
        NavMapScreen.TrackedEntitySelectedAction += ItemSelected;

        Tabs.SetTabTitle(0, Loc.GetString("station-ai-camera-tab-cameras"));
        Tabs.SetTabTitle(1, Loc.GetString("station-ai-camera-tab-search"));

        SearchType.AddItem(Loc.GetString("station-ai-camera-search-type-all"), (int) AiCameraSearchType.All);
        SearchType.AddItem(Loc.GetString("station-ai-camera-search-type-characters"), (int) AiCameraSearchType.Characters);
        SearchType.AddItem(Loc.GetString("station-ai-camera-search-type-items"), (int) AiCameraSearchType.Items);
        SearchType.SelectId((int) AiCameraSearchType.All);

        SearchButton.OnPressed += _ => RequestSearch();
        SearchInput.OnTextEntered += _ => RequestSearch();
        SearchResults.OnItemSelected += OnSearchResultSelected;

        UpdateCameras();
    }

    public void UpdateCameras()
    {
        if (!_entityManager.TryGetComponent<AiEyeComponent>(_owner, out var eyeComponent))
            return;

        NavMapScreen.TrackedEntities.Clear();

        foreach (var (camera, pos) in eyeComponent.Cameras)
        {
            if (pos.X == 0 && pos.Y == 0)
                continue;

            var texture = _entityManager.System<SpriteSystem>().Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
            var blip = new NavMapBlip(_entityManager.GetCoordinates(pos), texture, Color.Cyan, false, true);
            NavMapScreen.TrackedEntities[camera] = blip;
        }

        NavMapScreen.ForceNavMapUpdate();
    }

    private void ItemSelected(NetEntity? obj)
    {
        if (obj != null)
            WarpToCamera?.Invoke(obj.Value);
    }

    private void RequestSearch()
    {
        SearchRequested?.Invoke(SearchInput.Text, (AiCameraSearchType) SearchType.SelectedId);
    }

    private void OnSearchResultSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemList[args.ItemIndex].Metadata is NetEntity target)
            WarpToTarget?.Invoke(target);
    }

    public void UpdateSearchResults(AiCameraSearchResultsState state)
    {
        SearchResults.Clear();
        SearchStatus.Text = state.Message;

        foreach (var result in state.Results)
        {
            var type = result.Type == AiCameraSearchResultType.Character
                ? Loc.GetString("station-ai-camera-search-result-character")
                : Loc.GetString("station-ai-camera-search-result-item");

            SearchResults.Add(new ItemList.Item(SearchResults)
            {
                Text = Loc.GetString("station-ai-camera-search-result", ("name", result.Name), ("type", type)),
                Metadata = result.Entity,
            });
        }
    }
}
