// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.StationAI.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.StationAI.UI;

[GenerateTypedNameReferences]
public sealed partial class StationAiCentCommFaxWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    private bool _canSend = true;
    private bool _updatingText;
    private int _lastCooldownSecond = -1;
    private TimeSpan? _cooldownEnd;
    private TimeSpan _statusHoldEnd;

    public event Action<string>? SubmitPressed;

    public StationAiCentCommFaxWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MessageEdit.Placeholder = new Rope.Leaf(Loc.GetString("station-ai-centcomm-fax-content-placeholder"));
        MessageEdit.OnTextChanged += _ =>
        {
            EnforceContentLimit();
            RefreshControls();
        };

        TransmitButton.OnPressed += _ => Submit();
        RefreshControls();
    }

    public void SetState(StationAiCentCommFaxUiState state)
    {
        _canSend = state.CanSend;
        StatusLabel.Text = state.Status;
        _cooldownEnd = state.CooldownRemainingSeconds > 0
            ? _timing.CurTime + TimeSpan.FromSeconds(state.CooldownRemainingSeconds)
            : null;
        _lastCooldownSecond = state.CooldownRemainingSeconds;
        _statusHoldEnd = state.ClearForm
            ? _timing.CurTime + TimeSpan.FromSeconds(1.5)
            : TimeSpan.Zero;

        if (state.ClearForm)
        {
            MessageEdit.TextRope = Rope.Leaf.Empty;
            MessageEdit.CursorPosition = new TextEdit.CursorPos(0, TextEdit.LineBreakBias.Top);
        }

        RefreshControls();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCooldownCountdown();
    }

    private void Submit()
    {
        var content = GetContent().Trim();

        if (!_canSend || content.Length == 0)
        {
            return;
        }

        SubmitPressed?.Invoke(content);
    }

    private void EnforceContentLimit()
    {
        if (_updatingText)
            return;

        var content = GetContent();
        if (content.Length <= StationAiCentCommFaxConstants.MaxContentLength)
            return;

        _updatingText = true;
        content = content[..StationAiCentCommFaxConstants.MaxContentLength];
        MessageEdit.TextRope = new Rope.Leaf(content);
        MessageEdit.CursorPosition = new TextEdit.CursorPos(content.Length, TextEdit.LineBreakBias.Bottom);
        _updatingText = false;
    }

    private void RefreshControls()
    {
        var content = GetContent().Trim();

        TransmitButton.Disabled = !_canSend || content.Length == 0;
        LimitLabel.Text = Loc.GetString("station-ai-centcomm-fax-content-limit",
            ("count", GetContent().Length),
            ("max", StationAiCentCommFaxConstants.MaxContentLength));
    }

    private string GetContent()
    {
        return Rope.Collapse(MessageEdit.TextRope);
    }

    private void UpdateCooldownCountdown()
    {
        if (_cooldownEnd == null)
            return;

        var remaining = (int) Math.Ceiling((_cooldownEnd.Value - _timing.CurTime).TotalSeconds);
        if (remaining <= 0)
        {
            _cooldownEnd = null;
            _canSend = true;

            if (_canSend && _timing.CurTime >= _statusHoldEnd)
                StatusLabel.Text = Loc.GetString("station-ai-centcomm-fax-status-ready");

            RefreshControls();
            return;
        }

        _canSend = false;
        if (remaining == _lastCooldownSecond)
            return;

        _lastCooldownSecond = remaining;

        if (_timing.CurTime >= _statusHoldEnd)
        {
            StatusLabel.Text = Loc.GetString("station-ai-centcomm-fax-status-cooldown",
                ("seconds", remaining));
        }

        RefreshControls();
    }
}
