using Content.Client.Administration.Managers;
using Content.Client.DeadSpace.Administration.UI;
using Content.Shared.Administration;
using Content.Shared.CCVar;
using Content.Shared.DeadSpace.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class ServerTab : Control
    {
        [Dependency] private readonly IConfigurationManager _config = default!;
        [Dependency] private readonly IClientConsoleHost _console = default!;

        // DS14-start
        [Dependency] private readonly IClientAdminManager _admin = default!;
        [Dependency] private readonly IUserInterfaceManager _ui = default!;

        private AutoMapVoteAdminState? _autoMapVoteState;
        private AutoMapVoteConfigWindow? _autoMapVoteWindow;
        // DS14-end

        public ServerTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _config.OnValueChanged(CCVars.OocEnabled, OocEnabledChanged, true);
            _config.OnValueChanged(CCVars.LoocEnabled, LoocEnabledChanged, true);
            _admin.AdminStatusUpdated += RefreshAutoMapVoteVisibility; // DS14

            ServerShutdownButton.OnPressed += _ => _console.ExecuteCommand("shutdown");

            // DS14-start
            OpenAutoMapVoteConfigButton.OnPressed += _ => OpenAutoMapVoteConfigWindow();
            RefreshAutoMapVoteVisibility();
            // DS14-end
        }

        private void OocEnabledChanged(bool value)
        {
            SetOocButton.Pressed = value;
        }

        private void LoocEnabledChanged(bool value)
        {
            SetLoocButton.Pressed = value;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                _config.UnsubValueChanged(CCVars.OocEnabled, OocEnabledChanged);
                _config.UnsubValueChanged(CCVars.LoocEnabled, LoocEnabledChanged);

                // DS14-start
                _admin.AdminStatusUpdated -= RefreshAutoMapVoteVisibility;

                if (_autoMapVoteWindow is { Disposed: false })
                    _autoMapVoteWindow.Dispose();
                // DS14-end
            }
        }

        // DS14-start
        public void UpdateAutoMapVoteState(AutoMapVoteAdminState? state)
        {
            _autoMapVoteState = state;
            _autoMapVoteWindow?.UpdateState(state);
        }

        private void OpenAutoMapVoteConfigWindow()
        {
            if (!_admin.HasFlag(AdminFlags.Server))
                return;

            EnsureAutoMapVoteWindow();
            _autoMapVoteWindow!.UpdateState(_autoMapVoteState);
            _autoMapVoteWindow.OpenCentered();
            _autoMapVoteWindow.MoveToFront();
        }

        private void EnsureAutoMapVoteWindow()
        {
            if (_autoMapVoteWindow is { Disposed: false })
                return;

            _autoMapVoteWindow = _ui.CreateWindow<AutoMapVoteConfigWindow>();
        }

        private void RefreshAutoMapVoteVisibility()
        {
            OpenAutoMapVoteConfigButton.Visible = _admin.HasFlag(AdminFlags.Server);

            if (!OpenAutoMapVoteConfigButton.Visible && _autoMapVoteWindow is { IsOpen: true })
                _autoMapVoteWindow.Close();
        }
        // DS14-end
    }
}
