- type: job
  id: ClownSponsor
  name: job-name-clown-sponsor
  description: job-description-clown-sponsor
  playTimeTracker: JobClownSponsor
  sponsorOnly: true
  startingGear: ClownGear
  icon: "JobIconClown"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    # - type: CustomNameOnSpawn
    # - type: ClownBibleUser #Lets them honk with bibles
    - type: PermanentStatusEffects
      statusEffects:
      - StatusEffectClumsyClown
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]
  - !type:AddComponentSpecial
    components:
    # DS14-Start
    - type: Skill
      group: BaseSkills
    # DS14-End
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 50
  #end-backmen: currency

- type: chameleonOutfit
  id: ClownSponsorChameleonOutfit
  job: ClownSponsor
  equipment:
    head: ClothingHeadHatXmasCrown
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingHeadHatFlowerWreath
    outerClothing: ClothingOuterClownPriest
    gloves: ClothingHandsGlovesColorYellowBudget
