using Content.Shared.Localizations;
using Content.Client.DeadSpace.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Info.PlaytimeStats;

[GenerateTypedNameReferences]
public sealed partial class PlaytimeStatsEntry : ContainerButton
{
    public TimeSpan Playtime { get; private set; }

    // DS14-start
    public PlaytimeStatsEntry(string role, TimeSpan playtime, bool useAltStyle)
    {
        RobustXamlLoader.Load(this);

        RoleLabel.Text = role;
        Playtime = playtime;
        PlaytimeLabel.Text = ContentLocalizationManager.FormatPlaytime(playtime);
        UpdateShading(useAltStyle);
    }

    public void UpdateShading(bool useAltStyle)
    {
        RemoveStyleClass(DeadSpaceStyleClass.ListItemAlternate);
        if (useAltStyle)
            AddStyleClass(DeadSpaceStyleClass.ListItemAlternate);
    }
    // DS14-end

    public string? PlaytimeText => PlaytimeLabel.Text;

    public string? RoleText => RoleLabel.Text;
}
