using System.Linq;
using System.Text;
using Content.Client.Actions;
using Content.Client.Message;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Store.Ui;

[GenerateTypedNameReferences]
public sealed partial class StoreMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private StoreWithdrawWindow? _withdrawWindow;

    public event EventHandler<string>? SearchTextUpdated;
    public event Action<BaseButton.ButtonEventArgs, ListingDataWithCostModifiers>? OnListingButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string>? OnCategoryButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string, int>? OnWithdrawAttempt;
    public event Action<BaseButton.ButtonEventArgs>? OnRefundAttempt;

    public Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> Balance = new();
    public string CurrentCategory = string.Empty;

    private List<ListingDataWithCostModifiers> _cachedListings = new();

    // DS14-start
    private readonly Dictionary<string, StoreListingControl> _listingControls = new();
    private readonly Dictionary<string, StoreCategoryButton> _categoryButtons = new();
    private readonly ButtonGroup _categoryGroup = new();
    // DS14-end

    public StoreMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
        RefundButton.OnButtonDown += OnRefundButtonDown;
        SearchBar.OnTextChanged += _ => SearchTextUpdated?.Invoke(this, SearchBar.Text);
    }

    // begin: backmen-currency
    public bool CanBuyFromBank = false;
    public void SetCanBuyFromBank(bool hasComponent)
    {
        CanBuyFromBank = hasComponent;
    }

    // end: backmen-currency

    public void UpdateBalance(Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> balance)
    {
        Balance = balance;

        var currency = balance.ToDictionary(type =>
            (type.Key, type.Value), type => _prototypeManager.Index(type.Key));

        var balanceStr = string.Empty;
        foreach (var ((_, amount), proto) in currency)
        {
            balanceStr += Loc.GetString("store-ui-balance-display", ("amount", amount),
                ("currency", Loc.GetString(proto.DisplayName, ("amount", 1)))) + "\n";
        }

        BalanceInfo.SetMarkup(balanceStr.TrimEnd());

        var disabled = true;
        foreach (var type in currency)
        {
            if (type.Value.CanWithdraw && type.Value.Cash != null && type.Key.Item2 > 0)
            {
                disabled = false;
                break;
            }
        }

        WithdrawButton.Disabled = disabled;
    }

    // DS14-start
    public void UpdateListing(
        List<ListingDataWithCostModifiers> listings,
        HashSet<string> availableListingIds,
        bool resetScroll = false)
    {
        _cachedListings = listings;

        foreach (var id in _listingControls.Keys.Where(id => !availableListingIds.Contains(id)).ToList())
        {
            _listingControls[id].Orphan();
            _listingControls.Remove(id);
        }

        UpdateListing(resetScroll);
    }

    public void UpdateListing(bool resetScroll = false)
    {
        var sorted = _cachedListings.OrderBy(l => l.Priority)
                                    .ThenBy(l => l.Cost.Values.Sum())
                                    .Where(l => l.Categories.Contains(CurrentCategory))
                                    .ToList();

        var visibleIds = sorted.Select(listing => listing.ID).ToHashSet();
        foreach (var control in _listingControls.Values)
        {
            if (control.Parent == StoreListingsContainer && !visibleIds.Contains(control.Listing.ID))
                control.Orphan();
        }

        for (var index = 0; index < sorted.Count; index++)
        {
            var listing = sorted[index];
            if (!_listingControls.TryGetValue(listing.ID, out var control))
            {
                control = CreateListingControl(listing);
                _listingControls.Add(listing.ID, control);
            }
            else
            {
                UpdateListingControl(control, listing);
            }

            if (control.Parent == null)
                StoreListingsContainer.AddChild(control);

            control.SetPositionInParent(index);
        }

        StoreListingsContainer.InvalidateMeasure();

        if (resetScroll)
        {
            StoreListingsScroll.VScroll = 0;
            StoreListingsScroll.VScrollTarget = 0;
        }
    }
    // DS14-end

    public void SetFooterVisibility(bool visible)
    {
        TraitorFooter.Visible = visible;
    }

    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        // check if window is already open
        if (_withdrawWindow != null && _withdrawWindow.IsOpen)
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        // open a new one
        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();

        _withdrawWindow.CreateCurrencyButtons(Balance);
        _withdrawWindow.OnWithdrawAttempt += OnWithdrawAttempt;
    }

    private void OnRefundButtonDown(BaseButton.ButtonEventArgs args)
    {
        OnRefundAttempt?.Invoke(args);
    }

    // DS14-start
    private StoreListingControl CreateListingControl(ListingDataWithCostModifiers listing)
    {
        var spriteSys = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();

        Texture? texture = null;
        EntProtoId? productEntity = null;
        if (listing.Icon != null)
            texture = spriteSys.Frame0(listing.Icon);

        if (listing.ProductEntity != null)
        {
            if (texture == null)
                productEntity = listing.ProductEntity;
        }
        else if (listing.ProductAction != null)
        {
            var actionId = _entityManager.Spawn(listing.ProductAction);
            if (_entityManager.System<ActionsSystem>().GetAction(actionId)?.Comp?.Icon is {} icon)
                texture = spriteSys.Frame0(icon);
        }

        var newListing = new StoreListingControl(
            listing,
            GetListingPriceString(listing),
            GetDiscountString(listing),
            listing.CanBuyWith(Balance) || CanBuyFromBank,
            texture,
            productEntity);
        newListing.StoreItemBuyButton.OnButtonDown += args
            => OnListingButtonPressed?.Invoke(args, newListing.Listing);

        return newListing;
    }

    private void UpdateListingControl(StoreListingControl control, ListingDataWithCostModifiers listing)
    {
        control.Update(
            listing,
            GetListingPriceString(listing),
            GetDiscountString(listing),
            listing.CanBuyWith(Balance) || CanBuyFromBank);
    }
    // DS14-end

    private string GetListingPriceString(ListingDataWithCostModifiers listing)
    {
        var text = string.Empty;

        if (listing.Cost.Count < 1)
            text = Loc.GetString("store-currency-free");
        else
        {
            foreach (var (type, amount) in listing.Cost)
            {
                var currency = _prototypeManager.Index(type);

                text += Loc.GetString(
                    "store-ui-price-display",
                    ("amount", amount),
                    ("currency", Loc.GetString(currency.DisplayName, ("amount", amount)))
                );
            }
        }

        return text.TrimEnd();
    }

    private string GetDiscountString(ListingDataWithCostModifiers listingDataWithCostModifiers)
    {
        string discountMessage;

        if (!listingDataWithCostModifiers.IsCostModified)
        {
            return string.Empty;
        }

        var relativeModifiersSummary = listingDataWithCostModifiers.GetModifiersSummaryRelative();
        if (relativeModifiersSummary.Count > 1)
        {
            var sb = new StringBuilder();
            sb.Append('(');
            foreach (var (currency, amount) in relativeModifiersSummary)
            {
                var currencyPrototype = _prototypeManager.Index(currency);
                if (sb.Length != 0)
                {
                    sb.Append(", ");
                }
                var currentDiscountMessage = Loc.GetString(
                    "store-ui-discount-display-with-currency",
                    ("amount", amount.ToString("P0")),
                    ("currency", Loc.GetString(currencyPrototype.DisplayName))
                );
                sb.Append(currentDiscountMessage);
            }

            sb.Append(')');
            discountMessage = sb.ToString();
        }
        else
        {
            // if cost was modified - it should have diff relatively to original cost in 1 or more currency
            // ReSharper disable once GenericEnumeratorNotDisposed Dictionary enumerator doesn't require dispose
            var enumerator = relativeModifiersSummary.GetEnumerator();
            enumerator.MoveNext();
            var amount = enumerator.Current.Value;
            discountMessage = Loc.GetString(
                "store-ui-discount-display",
                ("amount", (amount.ToString("P0")))
            );
        }

        return discountMessage;
    }

    // DS14-start
    public void PopulateStoreCategoryButtons(
        HashSet<ListingDataWithCostModifiers> listings,
        HashSet<ProtoId<StoreCategoryPrototype>> allowedCategories)
    {
        var categoryIds = new HashSet<ProtoId<StoreCategoryPrototype>>();
        foreach (var listing in listings)
        {
            foreach (var cat in listing.Categories)
            {
                if (!allowedCategories.Contains(cat))
                    continue;

                categoryIds.Add(cat);
            }
        }

        var allCategories = categoryIds.Select(id => _prototypeManager.Index(id))
                                       .OrderBy(category => category.Priority)
                                       .ToList();

        // Preserve the selected category while it remains visible.
        if (allCategories.All(category => category.ID != CurrentCategory))
            CurrentCategory = string.Empty;

        if (CurrentCategory == string.Empty && allCategories.Count > 0)
            CurrentCategory = allCategories.First().ID;

        var allowedIds = allowedCategories.Select(category => category.Id).ToHashSet();
        foreach (var id in _categoryButtons.Keys.Where(id => !allowedIds.Contains(id)).ToList())
        {
            var button = _categoryButtons[id];
            button.Orphan();
            button.Group = null;
            _categoryButtons.Remove(id);
        }

        var visibleIds = allCategories.Select(category => category.ID).ToHashSet();
        foreach (var button in _categoryButtons.Values)
        {
            if (button.Parent == CategoryListContainer && !visibleIds.Contains(button.Id))
                button.Orphan();
        }

        for (var index = 0; index < allCategories.Count; index++)
        {
            var proto = allCategories[index];
            if (!_categoryButtons.TryGetValue(proto.ID, out var catButton))
            {
                catButton = new StoreCategoryButton
                {
                    Id = proto.ID,
                    Group = _categoryGroup,
                    StyleClasses = { "OpenBoth" }
                };

                catButton.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, catButton.Id);
                _categoryButtons.Add(proto.ID, catButton);
            }

            catButton.Text = Loc.GetString(proto.Name);
            if (catButton.Parent == null)
                CategoryListContainer.AddChild(catButton);

            catButton.SetPositionInParent(index);
        }

        foreach (var button in _categoryButtons.Values)
            button.Pressed = button.Id == CurrentCategory;

        CategoryListContainer.InvalidateMeasure();
    }
    // DS14-end

    public override void Close()
    {
        base.Close();
        _withdrawWindow?.Close();
    }

    public void UpdateRefund(bool allowRefund)
    {
        RefundButton.Visible = allowRefund;
    }

    private sealed class StoreCategoryButton : Button
    {
        public string Id = string.Empty; // DS14
    }
}
