using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Systems.Chat.Widgets;

namespace Content.Client.UserInterface.Systems.Chat;

/// <summary>
/// Window which only holds a single chatbox, useful for monitoring multiple chats simultaneously.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ChatWindow : FancyWindow
{
    // DS14-start
    [Dependency] private readonly IClyde _clyde = default!;

    private readonly Button _popOutButton = new()
    {
        StyleClasses = { "OpenBoth" },
        Margin = new Thickness(0, 0, 4, 0),
        VerticalAlignment = VAlignment.Center,
        Disabled = false,
        Visible = true,
    };

    private IClydeWindow? _poppedOutWindow;
    public event Action? PoppedOutClosed;
    // DS14-end

    public ChatWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // DS14-start
        CloseButton.Parent!.AddChild(_popOutButton);
        _popOutButton.SetPositionInParent(CloseButton.GetPositionInParent());
        _popOutButton.OnPressed += _ => PopOut();
        // DS14-end

        // These are necessary for the controls inside the chatbox to initialize correctly:
        Chatbox.Repopulate();
        var controller = UserInterfaceManager.GetUIController<ChatUIController>();
        controller.UpdateSelectedChannel(Chatbox);
    }

    /// <summary>
    /// Helper method to configure this window to be useful for admins.
    /// Sets incoming filters to only admin chats and output to admin channel
    /// </summary>
    public void ConfigureForAdminChat()
    {
        // DS14-start
        Title = Loc.GetString("chat-window-admin-title");
        _popOutButton.Text = Loc.GetString("chat-window-pop-out");
        _popOutButton.ToolTip = Loc.GetString("chat-window-pop-out-tooltip");
        _popOutButton.Disabled = false;
        _popOutButton.Visible = true;
        // DS14-end

        Chatbox.ChatInput.ChannelSelector.Select(ChatSelectChannel.Admin);

        var filter = Chatbox.ChatInput.FilterButton.Popup;
        foreach (var c in Enum.GetValues(typeof(ChatChannel)))
        {
            var channel = (ChatChannel)c;
            var isAdminInterest = channel == ChatChannel.Admin
                                  || channel == ChatChannel.AdminChat
                                  || channel == ChatChannel.AdminAlert
                                  || channel == ChatChannel.AdminRelated;
            filter.SetActive(channel, isAdminInterest);
        }
    }

    // DS14-start
    private void PopOut()
    {
        if (_poppedOutWindow != null)
            return;

        var monitor = _clyde.EnumerateMonitors().First();
        var width = Math.Max((int) Size.X, 650);
        var height = Math.Max((int) Size.Y, 420);

        _poppedOutWindow = _clyde.CreateWindow(new WindowCreateParameters
        {
            Maximized = false,
            Title = Title ?? Loc.GetString("chat-window-admin-title"),
            Monitor = monitor,
            Width = width,
            Height = height,
        });

        _poppedOutWindow.RequestClosed += OnPoppedOutWindowRequestClosed;

        var poppedOutRoot = UserInterfaceManager.CreateWindowRoot(_poppedOutWindow);
        poppedOutRoot.BackgroundColor = Color.FromHex("#25252A");

        var poppedOutBackground = new PanelContainer
        {
            StyleClasses = { "BackgroundDark" },
            HorizontalAlignment = HAlignment.Stretch,
            VerticalAlignment = VAlignment.Stretch,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        poppedOutRoot.AddChild(poppedOutBackground);
        Chatbox.Orphan();
        poppedOutBackground.AddChild(Chatbox);
        poppedOutRoot.CreateRootControls();
        MoveChatPopupsTo(poppedOutRoot);

        _popOutButton.Disabled = true;
        _popOutButton.Visible = false;
        Close();
    }

    private void OnPoppedOutWindowRequestClosed(WindowRequestClosedEventArgs args)
    {
        DisposePoppedOutWindow();
    }

    private void DisposePoppedOutWindow()
    {
        if (_poppedOutWindow == null)
            return;

        Chatbox.ClearInputs();
        CloseChatPopups();
        _poppedOutWindow.RequestClosed -= OnPoppedOutWindowRequestClosed;
        ((IDisposable)Chatbox).Dispose();
        _poppedOutWindow.Dispose();
        _poppedOutWindow = null;
        PoppedOutClosed?.Invoke();
    }

    public void ClosePoppedOutWindow()
    {
        DisposePoppedOutWindow();
    }

    private void MoveChatPopupsTo(WindowRoot root)
    {
        CloseChatPopups();

        var channelSelectorPopup = Chatbox.ChatInput.ChannelSelector.Popup;
        var filterPopup = Chatbox.ChatInput.FilterButton.Popup;

        channelSelectorPopup.Orphan();
        filterPopup.Orphan();

        root.ModalRoot.AddChild(channelSelectorPopup);
        root.ModalRoot.AddChild(filterPopup);
    }

    private void CloseChatPopups()
    {
        Chatbox.ChatInput.ChannelSelector.Popup.Close();
        Chatbox.ChatInput.FilterButton.Popup.Close();
    }
    public void PopOutChatRef(ref ChatBox box)
    {
        if (_poppedOutWindow != null)
        {
            Chatbox.SetInputs(ref box);
            return;
        }

        var monitor = _clyde.EnumerateMonitors().First();
        var width = Math.Max((int) Size.X, 650);
        var height = Math.Max((int) Size.Y, 420);

        _poppedOutWindow = _clyde.CreateWindow(new WindowCreateParameters
        {
            Maximized = false,
            Title = Title ?? Loc.GetString("chat-window-admin-title"),
            Monitor = monitor,
            Width = width,
            Height = height,
            Styles = OSWindowStyles.NoTitleOptions,
        });

        _poppedOutWindow.RequestClosed += OnPoppedOutWindowRequestClosed;

        var poppedOutRoot = UserInterfaceManager.CreateWindowRoot(_poppedOutWindow);
        poppedOutRoot.BackgroundColor = Color.FromHex("#25252A");

        var poppedOutBackground = new PanelContainer
        {
            StyleClasses = { "BackgroundDark" },
            HorizontalAlignment = HAlignment.Stretch,
            VerticalAlignment = VAlignment.Stretch,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        poppedOutRoot.AddChild(poppedOutBackground);
        Chatbox.Orphan();
        Chatbox.SetInputs(ref box);
        poppedOutBackground.AddChild(Chatbox);
        poppedOutRoot.CreateRootControls();
        MoveChatPopupsTo(poppedOutRoot);

        _popOutButton.Disabled = true;
        _popOutButton.Visible = false;
        Close();
    }

    public void DetachMainChat()
    {
        Chatbox.ClearInputs();
    }
    // DS14-end
}
