// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using System.Numerics;
using Content.Shared.Corvax.TTS;
using Content.Shared.DeadSpace.AdminToy;
using Content.Shared.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.AdminToy.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminToySelectionMenu : DefaultWindow
{
    private const string RandomTtsVoice = "";

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private EntityPrototype? _selectedToy;

    public event Action<string, string, string, string>? ToySelected;

    public AdminToySelectionMenu()
    {
        MinSize = SetSize = new Vector2(420, 620);
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("admin-toy-menu-title");
        ConfirmButton.Text = Loc.GetString("admin-toy-menu-confirm");
        ConfirmButton.Disabled = true;
        DescriptionEdit.Placeholder = new Rope.Leaf(Loc.GetString("admin-toy-description-placeholder"));

        ConfirmButton.OnPressed += _ => ConfirmSelected();
        SearchBar.OnTextChanged += _ => Populate(SearchBar.Text);
        TtsSelector.OnItemSelected += args => TtsSelector.SelectId(args.Id);
        ToyList.OnItemSelected += OnToySelected;
        ToyList.OnItemDeselected += _ =>
        {
            _selectedToy = null;
            ConfirmButton.Disabled = true;
        };

        PopulateTtsVoices();
        Populate(string.Empty);
    }

    public void SetTargetName(string targetName)
    {
        TargetLabel.Text = Loc.GetString("admin-toy-menu-target", ("target", targetName));
    }

    private void ConfirmSelected()
    {
        if (_selectedToy == null)
            return;

        ToySelected?.Invoke(
            _selectedToy.ID,
            NameEdit.Text,
            Rope.Collapse(DescriptionEdit.TextRope),
            TtsSelector.SelectedMetadata as string ?? RandomTtsVoice);
        Close();
    }

    private void PopulateTtsVoices()
    {
        TtsSelector.Clear();
        TtsSelector.AddItem(Loc.GetString("admin-toy-tts-random"));
        TtsSelector.SetItemMetadata(0, RandomTtsVoice);
        TtsSelector.SelectId(0);

        var voices = _prototype.EnumeratePrototypes<TTSVoicePrototype>()
            .OrderBy(proto => Loc.GetString(proto.Name))
            .ThenBy(proto => proto.ID)
            .ToList();

        for (var i = 0; i < voices.Count; i++)
        {
            var voice = voices[i];
            var id = i + 1;
            TtsSelector.AddItem($"{Loc.GetString(voice.Name)} ({voice.ID})");
            TtsSelector.SetItemMetadata(id, voice.ID);
        }
    }

    private void OnToySelected(ItemList.ItemListSelectedEventArgs args)
    {
        _selectedToy = (EntityPrototype) args.ItemList[args.ItemIndex].Metadata!;
        ConfirmButton.Disabled = false;
    }

    private void Populate(string filter)
    {
        ToyList.Clear();
        var trimmed = filter.Trim();

        foreach (var toy in GetToys())
        {
            if (!MatchesFilter(toy, trimmed))
                continue;

            ToyList.Add(new ItemList.Item(ToyList)
            {
                Metadata = toy,
                Text = $"{toy.Name} ({toy.ID})",
            });
        }
    }

    private IEnumerable<EntityPrototype> GetToys()
    {
        return _prototype.EnumeratePrototypes<EntityPrototype>()
            .Where(proto => !proto.Abstract &&
                            proto.HasComponent<AdminToySpawnableComponent>(_entityManager.ComponentFactory))
            .OrderBy(proto => proto.Name);
    }

    private static bool MatchesFilter(EntityPrototype proto, string filter)
    {
        if (string.IsNullOrEmpty(filter))
            return true;

        return proto.ID.Contains(filter, StringComparison.InvariantCultureIgnoreCase) ||
               proto.Name.Contains(filter, StringComparison.InvariantCultureIgnoreCase) ||
               proto.Description.Contains(filter, StringComparison.InvariantCultureIgnoreCase);
    }
}
